### ISSUE TITLE
Use batch to insert values

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#100]
Update the code to use bulk insert with addBatch methods

**Comment by ebocher** [comment]
Example : 

datasource.withBatch {stmt-> 
    100.times {
      stmt.addBatch("insert into dummyTable(number) values(${it})")
    }
    stmt.executeBatch()
}

**Comment by j3r3m1** [comment]
I do not get it, the example is used to insert values in a Table (thing we can currently do directly with SQL). Is the advantage of this method reduce the number of connexion to the Database ?

**Comment by ebocher** [comment]
Have a look here https://blog.jooq.org/2018/04/19/the-performance-difference-between-sql-row-by-row-updating-batch-updating-and-bulk-updating/

**Comment by ebocher** [comment]
Fixed
