### ISSUE TITLE
BUILDING_HEIGHT_DIST indicator name

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#1002]
At grid scale we compute the distribution of horizontal roof area fraction for each layer of the canopy. eg levels : [0, 5, 10, 15, 20, 25, 30]

See :

https://github.com/orbisgis/geoclimate/blob/master/geoindicators/src/main/groovy/org/orbisgis/geoclimate/geoindicators/WorkflowGeoIndicators.groovy#L1808

The name used to define this indicator is not very clear.

Moreover, this indicator is not mentioned in the documentation : https://github.com/orbisgis/geoclimate/wiki/Grid-indicators

@j3r3m1

**Comment by j3r3m1** [comment]
Yes we can change the name to BUILDING_HEIGHT_DISTRIBUTION.
We can also add the building average distance to have all TARGET inputs.

**Comment by j3r3m1** [comment]
Documentation updated for BUILDING_HEIGHT_DISTRIBUTION

**Comment by j3r3m1** [comment]
Fixed in #1003 + documentation OK

**Comment by ebocher** [comment]
Fixed
