### ISSUE TITLE
List of the tests to be written

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#103]
Below are listed the tests that have to be written concerning the data.
These tests are not `unit tests` since they are not based on a generic data set. They are just executed to check if the process outputs are error free. If the tests shows errors, then the following processes can not be executed.

Everybody is welcome to feed this list.

#### For buildings

- [ ] only POLYGONS are accepted
- [ ] null TYPE is not allowed
- [ ] the TYPE has to have an equivalent in the abstract list
- [ ] HEIGHT_WALL has to be lower than 1000
- [ ] NB_LEV has to be lower than 200
- [ ] check if the expected fields are present
- [ ] Consider the possibility to have no objects in the table

#### For roads

- [ ] only LINESTRINGS are accepted
- [ ] null TYPE is not allowed
- [ ] the TYPE has to have an equivalent in the abstract list
- [ ] WIDTH has to be lower than 100
- [ ] check if the expected fields are present
- [ ] Consider the possibility to have no objects in the table

#### For rails

- [ ] only LINESTRINGS are accepted
- [ ] null TYPE is not allowed
- [ ] the TYPE has to have an equivalent in the abstract list
- [ ] check if the expected fields are present
- [ ] Consider the possibility to have no objects in the table

#### For hydrographic area

- [ ] only POLYGONS are accepted
- [ ] check if the expected fields are present
- [ ] Consider the possibility to have no objects in the table

#### For vegetation area

- [ ] only POLYGONS are accepted
- [ ] null TYPE is not allowed
- [ ] the TYPE has to have an equivalent in the abstract list
- [ ] check if the expected fields are present
- [ ] Consider the possibility to have no objects in the table

#### For the table `buildings`

- [ ] check if the expected fields are present (THE_GEOM, ID_BUILD, ID_SOURCE, HEIGHT_WALL, HEIGHT_ROOF, NB_LEV, TYPE, MAIN_USE, ZINDEX, ID_ZONE)

Check if the following fields have null values (in theory it's not possible. If so, warning!)
- [ ] TYPE
- [ ] HEIGHT_WALL
- [ ] HEIGHT_ROOF
- [ ] NB_LEV

#### For the table `roads`

- [ ] check if the expected fields are present (THE_GEOM, ID_ROAD, ID_SOURCE, WIDTH, TYPE, SURFACE, SIDEWALK, ZINDEX)

Check if the following fields have null values (in theory it's not possible. If so, warning!)
- [ ] TYPE
- [ ]  WIDTH

#### For the table `rails`

- [ ] check if the expected fields are present (THE_GEOM, ID_RAIL, ID_SOURCE, TYPE, ZINDEX)

Check if the following fields have null values (in theory it's not possible. If so, warning!)
- [ ] TYPE

#### For the table `hydro`

- [ ] check if the expected fields are present (THE_GEOM, ID_HYDRO, ID_SOURCE)

#### For the table `veget`

- [ ] check if the expected fields are present (THE_GEOM, ID_VEGET, ID_SOURCE, TYPE, HEIGHT_CLASS)

Check if the following fields have null values (in theory it's not possible. If so, warning!)
- [ ] TYPE
- [ ] HEIGHT_CLASS

**Comment by ebocher** [comment]
hot hot fix.
Seems there are several pbs with inputDataFormatting process.
@j3r3m1

**Comment by ebocher** [comment]
To be updated

**Comment by ebocher** [comment]
Fixed ?

**Comment by ebocher** [comment]
To be updated ?
