### ISSUE TITLE
indexes created twice

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#105]
The index are create twice due to the following query that could have a different id_name along a "mapper"...
```
create index if not exists id_name on...
```

**Comment by ebocher** [comment]
With @SPalominos  we decided to add two methods  : one to test if an index exist and the other to create it.
The syntax will be be : 

datasource.getTable("building").the_geom.isIndexed -> true or false
datasource.getTable("building").the_geom.index -> create the index with a default name

**Comment by j3r3m1** [comment]
OK works for spatial and non spatial indexes ?

**Comment by ebocher** [comment]
orbisgis/orbisdata#111
