### ISSUE TITLE
Building preparation from OSM data: what a long time 

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#113]
I have applied the test "osmGeoIndicatorsFromApi" that call the processing chain coded within "PrepareOSM.prepareOSMDefaultConfig()". With the INSEE code given by Erwan (for the La-Roche-Bernard city - \#whatacity), it works perfectly but if I try for the Paris commune (OK may be my mistake), the processing chain is spending too much time (more than 3h, then I had to stop the process) at the step that logs:
"Buildings preparation starts" (right after "Transform OSM data to GIS tables.")

@ELSW56 @ebocher any idea to speed up this step (I think that this is the IProcess called "defineBuildingScript" that takes so much time) ?

**Comment by ebocher** [comment]
Yep we have a serious problem to create the building from  the local OSM schema in H2GIS.
We must check all SQL queries to find what's wrong.

**Comment by ELSW56** [comment]
I've never tried with very big cities ...
I'm sorry but I've got no time to inquire at the moment.
The indexes are set on the OSM tables just after they have been loaded (the "createIndexesOnOSMTables" funtion is called).
Indexes are also set during the "prepareBuildings" process on the temporary tables.
Maybe you should have a look at the SQL script (defined in the "defineBuildingScript") and verify if all necessary indexes are correctly set and if all the temporary tables are dropped ...

**Comment by ebocher** [comment]
Fixed
