### ISSUE TITLE
RSU in Fontainebleau (INSEE 77186)

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#115]
The created RSU for the commune of Fontainebleau are strange. Some of them are defined outside the commune limits and they even not intersect the other RSU within the buildings (they look like island in an ocean of empty...).
We probably have forgotten one of the last steps of the RSU creation used to select the RSU that are located within the commune zone ?

**Comment by ebocher** [comment]
I will look right now

**Comment by ebocher** [comment]
Fixed. 
The zone table can be used to select the RSU that are inside.

![fontainebleau](https://user-images.githubusercontent.com/1820572/65147149-d0976400-da1d-11e9-8d73-db0f0cbfc768.png)
