### ISSUE TITLE
OSM in Nozay (INSEE code 91458)

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#117]
I have downloaded the OSM data for the city of Nozay (Essone) and when I wanted to compute the RSU, I got an error saying that the column "the_geom" was not found in the "rail" table.
The reason is that there is no rail and it seems that when H2 save an empty table in the geojson format, the column names are not conserved when we load it back (the table is emptied of its lines and its columns as well...).
If there is no opportunity to change the H2 behaviour, what could we do ? Add a test on the input loaded data to create an empty table with the right column names if the table is empty ?

**Comment by ebocher** [comment]
The best way is to fix on the geoclimate side. We must adapt the processes according the input layers.  It will be the same pb for vegetation, water ...

**Comment by ebocher** [comment]
Fixed a default table is created for each null result
