### ISSUE TITLE
References for indicators

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#12]
We do not describe well the indicators we calculate yet. Should we add the reference source ?

For example for buildingConcavity:
References:
 * Bocher, E., Petit, G., Bernard, J., & Palominos, S. (2018). A geoprocessing framework to cototompute urban indicators: The MApUCE tools chain. Urban climate, 24, 153-174.
 * Adolphe, L., 2001. A simplified model of urban morphology: application to an analysis of the environmental performance of cities. Environ. Plann. B. Plann. Des. 28, 183–200.
 * Atelier Parisien d’URbanisme (APUR), A. P., 2007. Consommations d'énergie et émissions de gaz à effet de serre liées au chauffage des résidences principales parisiennes. Technical Report. Atelier Parisien d’URbanisme (APUR).

Or at least one of the reference (the one of Bocher for example) ? Or only for new indicators and for the others we add only the Bocher reference at the beginning of each script ?

**Comment by j3r3m1** [comment]
Or at least a short description of each indicator ?

**Comment by ebocher** [comment]
We must add both a short description and a ref to a paper.
You can put it as a javadoc annotation, here an example

/**
 *  This process is used to compute...
*  The operator .... is based on the folowinsg method, described in 
 */

**Comment by j3r3m1** [comment]
Should be updated. @ebocher can you close the issue after verification ?
