### ISSUE TITLE
Created RSU problem

### ISSUE THREAD

**Issue by nahtanojoal** [orbisgis/geoclimate#127]
There are two problems with CREATED_RSU layer :
- Some RSU are outside COMMUNE_SELECTED footprint
- Some RSU are isolated, e.g. not adjacent to other RSU of the same layer

City which has been tested : 56195

![Capture du 2019-06-24 12-40-19](https://user-images.githubusercontent.com/33353321/60013343-83a22c80-967e-11e9-91a3-d415e2624a82.png)
![Capture du 2019-06-24 12-40-43](https://user-images.githubusercontent.com/33353321/60013344-83a22c80-967e-11e9-8c3a-3d68dcf45276.png)

**Comment by ebocher** [comment]
Fixed
