### ISSUE TITLE
Trouble with extra column and buildLCZ

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#130]
When I want to build the LCZ from a table containing an other column than the_geom and id_rsu, a duplicate error appears (when some of the indicators are joinded).

**Comment by ebocher** [comment]
Do you have a test case ?

**Comment by j3r3m1** [comment]
I think that my point was about the join method that would need further flexibility. In case I want to join an existing table with id, the_geom and build_dens with the LCZ table that also contains the build_dens indicator, there is a duplicate column build_dens. Is a left or a right join in the "join" fonction could make the job and avoid the duplicate error ?

**Comment by j3r3m1** [comment]
I do not face the problem anymore
