### ISSUE TITLE
LCZ type names

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#131]
We use VARCHAR to store the LCZ type of an area. Should we modify to integer (like in WUDAPT, they use 1, 2, 3, etc. for built types and 101, 102, etc. for natural types) ?

**Comment by ebocher** [comment]
If the value is an int, yes please store it as int.

**Comment by j3r3m1** [comment]
It could either be integer for LCZ built types (LCZ1, LCZ2, etc.) or letters for natural types (LCZA, LCZ B, etc.). In WUDAPT, they have chosen to replace LCZ1, LCZ2, etc. by 1, 2, etc. and LCZA, LCZB, etc. by 101, 102, etc.

Do we follow the same conversion to keep only integer values ?

**Comment by gpetit** [comment]
It seems we all agree to encode into integer. So we will have this ?

| Before (varchar) | After (integer) | Definition |
| :------------: | :-------------: | :-------------: |
| 1  | 1 | LCZ 1: Compact high-rise |
| 2  | 2 | LCZ 2: Compact mid-rise |
| 3  | 3 | LCZ 3: Compact low-rise |
| 4  | 4 | LCZ 4: Open high-rise |
| 5  | 5 | LCZ 5: Open mid-rise |
| 6  | 6 | LCZ 6: Open low-rise |
| 7  | 7 | LCZ 7: Lightweight low-rise |
| 8  | 8 | LCZ 8: Large low-rise |
| 9  | 9 | LCZ 9: Sparsely built |
| 10  | 10 | LCZ 10: Heavy industry |
| A  | 101 | LCZ A: Dense trees |
| B  | 102 | LCZ B: Scattered trees |
| C  | 103 | LCZ C: Bush,scrub |
| D  | 104 | LCZ D: Low plants |
| E  | 105 | LCZ E: Bare rock or paved |
| F  | 106 | LCZ F: Bare soil or sand |
| G  | 107 | LCZ G: Water |

**Comment by j3r3m1** [comment]
yes

**Comment by j3r3m1** [comment]
OK I am trying to fix this one but I am currently facing the following issue :
when I classify a RSU to a LCZ, I first calculate how far is the RSU from each LCZ and then I keep the ones that are the closest. At the end of the first step I have a Table with for each RSU (as row) a distance to each LCZ (as column). The problem is that I can not used a numeric as column. Then two solutions:
1. I cast the number to varchar and convert it back at the end (but does it work with POSTGIS ?)
2. I convert the values LCZ1, LCZ2, etc. to 1, 2, etc. only at the end of the algorithm ?
3. We find a new solution to d

**Comment by gpetit** [comment]
> The problem is that I can not used a numeric as column
Even if you use " " ?

**Comment by j3r3m1** [comment]
It is OK with the ". See #196. Will it work with PostGIS ?

**Comment by j3r3m1** [comment]
I imagine the answer is yes since the PR has been accepted
