### ISSUE TITLE
prefix prepare data

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#137]
At the end of the prepare data step, the table names are fixed. In case we run several commune, there is a risk of conflict. Then we must add a prefix name for bdtopo and osm processes in prepare data.

**Comment by j3r3m1** [comment]
This issue has been taken into account but actually a suffix (uuid) has been used instead of a prefix which makes harder to visually gather all tables of a geoclimate chain calculation into a same GIS.

**Comment by ebocher** [comment]
Fixed ?

**Comment by j3r3m1** [comment]
let's say yes (maybe partly I did not check all) and I will open it again if needed.
