### ISSUE TITLE
Still problem with z data

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#144]
The RSU creation works now but there is still a problem with the block creation (when executing the "osmGeoIndicatorsFromTestFiles" processing chain using the PR #143. The problem again comes from an union of data having z values as NaN.

The error message is the following:
[main] INFO org.orbisgis.geoindicators.Geoindicators - Building spatial clusters...
[main] INFO gui.class org.h2gis.network.functions.GraphCreator - Loading graph into memory...
[main] INFO gui.class org.h2gis.network.functions.GraphCreator -     0.089 seconds
[main] INFO gui.class org.h2gis.network.functions.ST_ConnectedComponents - Calculating connected components... 
[main] INFO gui.class org.h2gis.network.functions.ST_ConnectedComponents -     0.038 seconds
[main] INFO gui.class org.h2gis.network.functions.ST_ConnectedComponents - Storing node connected components... 
[main] INFO gui.class org.h2gis.network.functions.ST_ConnectedComponents -     0.286 seconds
[main] INFO gui.class org.h2gis.network.functions.ST_ConnectedComponents - Storing edge connected components...
[main] INFO gui.class org.h2gis.network.functions.ST_ConnectedComponents -     0.198 seconds
[main] INFO org.orbisgis.geoindicators.Geoindicators - Merging spatial clusters...
[main] ERROR org.orbisgis.processmanager.Process - Error while executing the process.
Exception lors de l'appel de la fonction définie par l'utilisateur: "union(MULTIPOLYGON (((516872.94233278395 5277759.794728824, 516880.52041002514 5277762.039496896, 516888.17325328063 5277764.39563172, 516887.7939132827 5277765.728210717, 516854.78013486054 5277756.0744980145, 516864.9842706023 5277759.104829133, 516865.5144383675 5277757.550405747, 516872.94233278395 5277759.794728824)), ((516865.5144383675 5277757.550405747, 516866.045572383 5277755.662565364, 516873.5485633215 5277757.907106766, 516872.94233278395 5277759.794728824, 516865.5144383675 5277757.550405747)), ((516872.94233278395 5277759.794728824, 516873.5485633215 5277757.907106766, 516881.126642796 5277760.151875611, 516880.52041002514 5277762.039496896, 516872.94233278395 5277759.794728824)), ((516880.52041002514 5277762.039496896, 516881.126642796 5277760.151875611, 516888.7047164715 5277762.396654348, 516888.47653194936 5277763.396251952, 516888.17325328063 5277764.39563172, 516880.52041002514 5277762.039496896)))): found non-noded intersection between LINESTRING ( 516887.7939132827 5277765.728210717, 516854.78013486054 5277756.0744980145 ) and LINESTRING ( 516864.9842706023 5277759.104829133, 516865.5144383675 5277757.550405747 ) [ (516864.9986896651, 5277759.062553216, NaN) ]"
Exception calling user-defined function: "union(MULTIPOLYGON (((516872.94233278395 5277759.794728824, 516880.52041002514 5277762.039496896, 516888.17325328063 5277764.39563172, 516887.7939132827 5277765.728210717, 516854.78013486054 5277756.0744980145, 516864.9842706023 5277759.104829133, 516865.5144383675 5277757.550405747, 516872.94233278395 5277759.794728824)), ((516865.5144383675 5277757.550405747, 516866.045572383 5277755.662565364, 516873.5485633215 5277757.907106766, 516872.94233278395 5277759.794728824, 516865.5144383675 5277757.550405747)), ((516872.94233278395 5277759.794728824, 516873.5485633215 5277757.907106766, 516881.126642796 5277760.151875611, 516880.52041002514 5277762.039496896, 516872.94233278395 5277759.794728824)), ((516880.52041002514 5277762.039496896, 516881.126642796 5277760.151875611, 516888.7047164715 5277762.396654348, 516888.47653194936 5277763.396251952, 516888.17325328063 5277764.39563172, 516880.52041002514 5277762.039496896)))): found non-noded intersection between LINESTRING ( 516887.7939132827 5277765.728210717, 516854.78013486054 5277756.0744980145 ) and LINESTRING ( 516864.9842706023 5277759.104829133, 516865.5144383675 5277757.550405747 ) [ (516864.9986896651, 5277759.062553216, NaN) ]"; SQL statement:

            CREATE INDEX ON spatial_clustersccd79a52_f37b_47f2_b27b_cf521b207259_NODE_CC(NODE_ID); [90105-199]

**Comment by ebocher** [comment]
I'm on it.

**Comment by ebocher** [comment]
Fixed in master
