### ISSUE TITLE
Replace update in geoclimate/geoIndicators

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#15]
Currently, IProcess such as "buildingMinimumBuildingSpacing" or "buildingMinimumRoadDistance" use an update query at the end to set a default value when the field is null...

An alternative solution to save time could be to define a default value when creating the table
`CREATE TABLE $OutputTable($field AS Double DEFAULT 0, ...)`
However, using this solution would imply to get rid of the "inputFields" arguments in each IProcess since we do not know their type neither their potential default values, etc.

The third solution would be to get rid of these "inputFields". In this case, the result of each process will be gathered only at the end of all processes.

**Comment by j3r3m1** [comment]
It seems that the default value does not work... I have tried the following in the buildingRoadDistance IProcess:
```groovy
sql.execute("CREATE TABLE $outputTableName(building_road_distance DOUBLE DEFAULT 100.0, $idFieldBu INTEGER) AS (SELECT LEAST(st_distance(a.$geometricField, b.$geometricField)), a.$idFieldBu FROM $road_within_buffer b RIGHT JOIN $inputBuildingTableName a ON a.$idFieldBu = b.$idFieldBu GROUP BY a.$idFieldBu)".toString())
```
And when the condition is not fullfilled, the value of the field building_road_distance is null...

Then I have replace the previous by:
```groovy
sql.execute("CREATE TABLE $outputTableName(building_road_distance DOUBLE, $idFieldBu INTEGER) AS (SELECT COALESCE(LEAST(st_distance(a.$geometricField, b.$geometricField)), 100.0), a.$idFieldBu FROM $road_within_buffer b RIGHT JOIN $inputBuildingTableName a ON a.$idFieldBu = b.$idFieldBu GROUP BY a.$idFieldBu)".toString())
```
It works but I do not know about the performances. Probably better than the UPDATE but not confirmed...

**Comment by ebocher** [comment]
Could you test

sql.execute("CREATE TABLE $outputTableName(building_road_distance double precision DEFAULT 0.5::double precision , $idFieldBu INTEGER) AS (SELECT LEAST(st_distance(a.$geometricField, b.$geometricField)), a.$idFieldBu FROM $road_within_buffer b RIGHT JOIN $inputBuildingTableName a ON a.$idFieldBu = b.$idFieldBu GROUP BY a.$idFieldBu)".toString())

**Comment by j3r3m1** [comment]
Same

**Comment by ebocher** [comment]
humm
I will check H2

**Comment by j3r3m1** [comment]
The default values currently set do not work. I temporary use the "COALESCE" to set the null values to 0.

**Comment by ebocher** [comment]
Fixed ?

**Comment by j3r3m1** [comment]
we still have a lot of coalesce in the code

**Comment by ebocher** [comment]
Fixed ?

**Comment by j3r3m1** [comment]
what do you mean by fixed ? Is the default value problem is fixed in H2 or did we replace all the update in the code ?

**Comment by ebocher** [comment]
did we replace all the update in the code ?

**Comment by j3r3m1** [comment]
I will check that up

**Comment by j3r3m1** [comment]
Twice in geoindicators.SpatialUnits.prepareRSUData() but not sure how to replace it by coalesce.
Several times in almost all prepare data sql files.
That's it, otherwise it is clean.

**Comment by ebocher** [comment]
Thanks. We can close it.
