### ISSUE TITLE
building_likelihood_large_building

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#16]
For the building_likelihood_large_building calculation, I need the building_number_building_neighbors.
I could recalculate it but it is probably costly (not a direct calculation).

The alternative is to consider that we know the number of neighbors of each building and I simply create the process from there. It means that if the user does not have this information he will have to create a mapper to connect several IProcesses.

**Comment by ebocher** [comment]
So we decide to use the number of building neighbors as input value.

**Comment by j3r3m1** [comment]
Sorry we still have to code this one I prefer keep it open until I code it

**Comment by ebocher** [comment]
My fault. You are rigth

**Comment by j3r3m1** [comment]
now it is done
