### ISSUE TITLE
Update the use of spatial index

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#177]
The syntax for the creation of (spatial) indexes is not aligned with PostGreSQL/PostGIS (see https://github.com/h2database/h2database/issues/2171).
So when the problem will be resolved on the H2/H2GIS side, we will have to update the .sql (and maybe .groovy) files in GeoClimate. For example :

- https://github.com/orbisgis/geoclimate/blob/master/prepare_data/src/main/resources/org/orbisgis/bdtopo/importPreprocess.sql (line 37)
- https://github.com/orbisgis/geoclimate/blob/master/prepare_data/src/main/resources/org/orbisgis/common/inputDataFormatting.sql (line 28)

@ebocher @SPalominos @j3r3m1 @ELSW56

**Comment by ebocher** [comment]
Still valid ?

**Comment by gpetit** [comment]
No. Resolved in #239
