### ISSUE TITLE
IProcess not at the right scale

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#18]
The "unweightedOperationFromLowerScale" IProcess should be a parent of the current BlockIndicator where it is located since it allows to summarize information from building to block, building to rsu or block to rsu scale.

The "geometryProperties" IProcess should also be at a parent directory since it can be applicable identically for each scale.

**Comment by ebocher** [comment]
You mean about a group of processes that can be used at several places ?

**Comment by j3r3m1** [comment]
yes

**Comment by j3r3m1** [comment]
This is the same for other processes such as "geometryProperties" useful for calculating the area of any object (then any scale)

**Comment by j3r3m1** [comment]
We create a class called GenericIndicators

**Comment by j3r3m1** [comment]
done in #77
