### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#182]
Add default SLD styles with the output results

- [x] Style for LCZ  ([see more](https://github.com/orbisgis/geoclimate/blob/master/docs/chain_documentation/classsifications/lcz.md#cartography)) 
- [x] Style for the Urban Typo ([see more](https://github.com/orbisgis/geoclimate/blob/master/docs/chain_documentation/classsifications/territorial_typologies.md#cartography)) 

The styles are stored here https://github.com/orbisgis/geoclimate/tree/master/processingchain/src/main/resources/styles

**Comment by gpetit** [comment]
Not sure there is an "official" way to represent LCZs.
So what about the style we used here http://mapuce.orbisgis.org/ ?

**Comment by gpetit** [comment]
They are the same. So the `lcz.sld` file is ready to be added in the project.
@ebocher in which folder do you want to store those kind of files ? Do we have like a `/styles/` folder ?

**Comment by gpetit** [comment]
Ok. So the files will be stored in `/processing_chain/src/main/resources/styles/` folder.
We will have the following files (maybe some other will come after) :
- `lcz1.sld` : the style ready to be used for the field `LCZ1`in the `xxxx.RSU_LCZ` table
- `lcz2.sld` : the style ready to be used for the field `LCZ2`in the `xxxx.RSU_LCZ` table
- `lcz.png` : a graphic illustration of the expected result

The PR is in the pipe (with some other modifications)

**Comment by j3r3m1** [comment]
brilliant

**Comment by ebocher** [comment]
excelleeeeeeeeeeeeeent
