### ISSUE TITLE
Metadata files

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#183]
Generate for each output files some metadata :  a readme or a pdf document that describe all variables stored in the tables and output files

**Comment by gpetit** [comment]
Ok, I'm on it. So we will have two ways to document the outputs
- add comments in the tables (using the `COMMENT ON COLUMN schema.table.field IS 'xxxx';` syntax
- create a "user" doc, thanks to `.md` files that will be stored in the `/geoclimate/docs/` folder

**Comment by gpetit** [comment]
I guess we can assume it's done, since the outputs are described in the online doc: https://github.com/orbisgis/geoclimate/blob/master/docs/chain_documentation/workflow/outputs.md
