### ISSUE TITLE
Update syntax for POSTGIS compatibility

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#195]
We should replace all 
1. casewhen(;;) by CASE WHEN THEN ELSE END
2. double by double precision

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
PostGIS db tests planed here https://github.com/orbisgis/geoclimate/issues/200

@gpetit @SPalominos

**Comment by ebocher** [comment]
Done
