### ISSUE TITLE
CONVEXHULL_PERIMETER_DENSITY

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#202]
This indicator is defined as the perimeter of the building convex hull / building perimeter.
The concavity is quite similar although it uses the area BUT the fraction is inverted (building area / area of the building convex hull).

I propose to homogenize the indicators (dividing both of you by the convex hull). The names could rename identical. What do you think ?

**Comment by gpetit** [comment]
So we will have:

- `CONVEXHULL_PERIMETER_DENSITY` = Building perimeter / area of the building convex hull
- `CONCAVITY` : Building area / area of the building convex hull

?
@ebocher

**Comment by j3r3m1** [comment]
for me, yes except that the first you divide by the perimeter not the area... =)

**Comment by gpetit** [comment]
My bad. I made the modification

**Comment by gpetit** [comment]
@ebocher agree with this proposal !

**Comment by j3r3m1** [comment]
OK, more complicated than expected. @gpetit underlined the fact that the name is not really appropriate (we have concavity for the building area one, why not convexity for the other ?). If we set convexity to building_perimeter / perimeter of the convex hull, we expect the building being more convex when the ratio increases, which is actually the contrary behaviour. Then instead of modifying the calculation, I propose to keep the initial one (perimeter of convex hull / building perimeter) and change the name.
`CONVEXHULL_PERIMETER_DENSITY` --> `perimeter_convexity`
`concavity` --> `area_concavity`

Both indicators will be included within a [0, 1] range, they will be respectively the most convex and concave when their value is 1 and the prefix perimeter and area informs about the quantity used to qualify them as concave or convex. It is a long issue for not a big deal but at least it would seems more consistent like that.

**Comment by gpetit** [comment]
Fine for me

**Comment by j3r3m1** [comment]
done in #209
