### ISSUE TITLE
Perkins Skill Score

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#203]
Maybe not appropriate for LCZ neither main direction since it is used for unequity analysis while we would like to know "if the king is the only king"...

**Comment by gpetit** [comment]
As you wan (@ebocher ?).
No problem to remove this indicator (I guess you are talking about `PERKINS_SKILL_SCORE_BUILDING_DIRECTION` at both block and RSU levels ?)

**Comment by j3r3m1** [comment]
I just want to replace it by a simpler indicator. I propose the weight of the main direction / the weight of the second main direction (the weight being in the case of building direction the length of facade within a given direction range)

**Comment by j3r3m1** [comment]
OK this is done for the building direction. But since the PSS is also used for the LCZ, I wonder if I should not make a process dedicated to the calculation of indicators characterizing a distribution of values...
This IProcess could then be used for any distribution of values (such as the LCZ one).

**Comment by ebocher** [comment]
@j3r3m1
the perkins skill score building direction is long long process... We need to think about a better algorithm.

**Comment by j3r3m1** [comment]
I start the LCZ modification creating a generic IProcess to calculate uniqueness and unequity indicators (that could be then used at least in building direction, lcz and urban classif for now)

**Comment by j3r3m1** [comment]
OK done in #324

**Comment by j3r3m1** [comment]
@gpetit 
Note that I have slightly changed the way the calculation of the uniqueness parameter is calculated in order to have results included between 0 and 1.
If you can correct it in the doc, it is here:
https://github.com/orbisgis/geoclimate/blob/master/docs/chain_documentation/indicators/rsu.md#uniqueness_building_direction

**Comment by ebocher** [comment]
Fixed ?

**Comment by j3r3m1** [comment]
the documentation is not updated and the "generic indicator" has not been applied to the LCZ yet

**Comment by j3r3m1** [comment]
The generic aspect has been solved in #401. I have also updated the documentation.

**Comment by j3r3m1** [comment]
Yes done
