### ISSUE TITLE
Test without assertion

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/geoclimate#206]
The test processingchain/ProcessingChainOSMTest.testOSMLCZ() is not passing. Travis doesn't detect it because it doesn't have any assertion. If you replace it with : 
``` groovy
@Test
    void testOSMLCZ() {
        String directory ="./target/geoclimate_chain${uuid()}"
        File dirFile = new File(directory)
        dirFile.delete()
        assertFalse dirFile.exists()
        dirFile.mkdir()
        H2GIS datasource = H2GIS.open(dirFile.absolutePath+File.separator+"geoclimate_chain_db;AUTO_SERVER=TRUE")
        IProcess process = ProcessingChain.GeoclimateChain.OSMLCZ()
        assertTrue process.execute(datasource: datasource, placeName: "romainville")
        IProcess saveTables = ProcessingChain.DataUtils.saveTablesAsFiles()
        assertTrue saveTables.execute( [inputTableNames: process.getResults().values() , directory: directory, datasource: datasource])
    }
```

The process ProcessingChain.GeoclimateChain.OSMLCZ fails on 
file GeoclimateChain line 194 which fails on
file GeoclimateChain line 329 which fails on
file BuildLCZ line 116 because the column DENS_AREA doesn't exists at this point.

This is probably why the issue #200 doesn't compile on Jenkins.

I have tried to run it removing in file BuildLCZ the line 70 (which contains DENS_AREA) and the the test works.

**Comment by ebocher** [comment]
Done
