### ISSUE TITLE
Missing/incomplete/wrong polygons due to OSM data retrieval method

### ISSUE THREAD

**Issue by ELSW56** [orbisgis/geoclimate#211]
The way we collect the OSM data doesn't permit to create all the polygons that we should.
And those created don't always have the shape that they should.

The **first problem** appears when the first and last nodes are outside the bbox : the condition `WHERE ST_GEOMETRYN(the_geom, 1) = ST_GEOMETRYN(the_geom, ST_NUMGEOMETRIES(the_geom))` can't be true.

The **second problem**  appears when some points are missing. It can lead to building shapes that don't exists in addition to partial shapes. Let's take this example from the redon.osm resource file :
![image](https://user-images.githubusercontent.com/31065426/67759051-0f6a0200-fa3f-11e9-9dc2-094bbe3b23f1.png)

The **red rectangle** is the bounding box used to filter the OSM data extraction.
The **blue shapes** are the real residential areas.
The **dotted shapes** are the residential areas computed by OSMTools.Transform.toPolygons()

We can see that the area in the south-west has not been created (first problem) and that the north area is both incomplete and wrong.

To be sure these problems won't happen, we could retrieve all the nodes for all the ways of the zone.

**Comment by ebocher** [comment]
Thanks for the ping.
This problem appears at the borders of the boundingbox and when a geometry is greater than the extracted area. It is not easy to solve because it depends on the spatial location of the nodes.
A solution would be to use the topological direction of the nodes and the order of the lines to see if it is possible either to make correct geometries or to detect invalid areas. A step-by-step debugging seems necessary.

**Comment by ebocher** [comment]
With @ELSW56  we decided to change the overpass query to return a xml file with all relations (including node out of the bbox).
As a consequence, some changes will be necessary in the process that extracts OSM data but also during the data formatting step. 
I'm on it.
@j3r3m1 @gpetit

**Comment by gpetit** [comment]
> As a consequence, some changes will be necessary in ... the data formatting step.

What kind of modifications ?

**Comment by ebocher** [comment]
Don't worry. It's just for OSM.

**Comment by gpetit** [comment]
Wow, you scared me ;-)
