### ISSUE TITLE
Geoindicator use table

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#220]
A certain use of geoclimate (LCZ, TEB, URBAN TYPOLOGY) induces the calculation of a certain number of geoindicators. Currently, the relation between a use and an indicator is directly included in the code. This should be modified.
Moreover, the calculation of a geoindicator may depends on the calculation of an other geoindicator. This is currently directly taken into account in the code. Again in the future it would be nice to have something that automatically calculate the indicator that will be needed by some other indicator (and in the right order since some indicators could be used in the calculation of several other indicators).

**Comment by ebocher** [comment]
Still available ? Is doc enough ?

**Comment by j3r3m1** [comment]
Can still be modified but it is not a priority
