### ISSUE TITLE
Urban typology classification

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#221]
I wrote the main steps to calculate the urban typology and I need your opinion about the main data that will be asked to the user.
**inputs**:
- buildingIndicators: String - name of the table where are stored the bu indic
- blockIndicators : String - idem previous
- rsuIndicators: String - idem
- modelToUse: String ("OSM" or "BDTOPO" or "USER_MODEL") - modèle smile qui sera enregistré dans le dépôt geoclimate sauf pour le "USER_MODEL" qui devra être fournir via l'input _pathForModel_
- indicatorsToUse: {'building": [list of indicators - two examples will be given (the one with all indicators, the second only with indicators with no height],
"bloc": [idem], "rsu": [idem]}
- pathForModel: String - only if the user chose "USER_MODEL" (its own model)

**outputs**:
building_typology, rsu_typology (the second one having type1, type2 and indicators of inequality such as in the LCZ classif)

**Comment by j3r3m1** [comment]
one question is relative to the script that will be used for the model creation. Should it be included inside the geoclimate tool as a process (in order to keep the same methodology if we want to update the training data for example) ? Then a given user could use its own data to train the model, save it and then use the previous function to predict the type of each building/rsu of the city of its choice ?

**Comment by gpetit** [comment]
Not really clear for me.
So if I understand well :
- there is one specific script per model (one for OSM, BD Topo, ...)
- this is not an input to the process you described above

The question is where do we store theses files ?
- just next to the .groovy file where the process is written
- in a resource folder, inside geoclimate
- somewhere else (outside geoclimate) since we consider this is something "private" and independent

Correct ?

**Comment by j3r3m1** [comment]
>     * there is one specific script per model (one for OSM, BD Topo, ...)
nop there is one script (IProcess) and two models stored in a separate file which will be loaded dependendly of the 'modelToUse' parameter.

>     * just next to the .groovy file where the process is written
> 
>     * in a resource folder, inside geoclimate
> 
>     * somewhere else (outside geoclimate) since we consider this is something "private" and independent
> 
> 
> Correct ?

nop again (seems my message was very far from clear... shame on me). The first process I have described was about the model use but actually it is necessary to create the model before.
Then cames the question of the model creation IProcess.

**Comment by gpetit** [comment]
This issue has been resolved no ?

**Comment by j3r3m1** [comment]
I prefer keep it open as long as the urban typo is not performed

**Comment by ebocher** [comment]
Done but some issues with OSM data
