### ISSUE TITLE
Error when executing Paris using OSM

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#231]
When I execute OSM for Paris, all steps are OK up to the following problem when formatting the building layer:

> [INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Formating building layer
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
Erreur lors de la conversion de données "MULTIPOLYGON (((448100.8441455475 5413891.714878206, 448101.9592703201 5413890.98188699, 448106.1205941128 5413888.208348199, 448106.6172913337 5413888.954203755, 448119.14407122834 5413845.653079207, 448092.6749742952 5413897.204952865, 448100.8441455475 5413891.714878206)), ((448106.6172913337 5413888.954203755, 448100.67237835645 5413909.503891656, 448106.7869587879 5413905.444822483, 448109.62918978377 5413903.550697134, 448120.64824890136 5413896.199807953, 448121.5933127337 5413897.680712297, 448123.2713462651 5413894.396665344, 448122.05952597706 5413892.618079591, 448124.83604189946 5413886.811342596, 448120.10543935397 5413878.839895083, 448113.88899419684 5413882.98883365, 448115.2517064707 5413885.221816312, 448114.7051928522 5413885.593766304, 448116.0211177631 5413887.527021834, 448116.59004200075 5413887.199332007, 448117.82427589374 5413889.022176619, 448109.03617948655 5413894.984904597, 448109.5364449597 5413895.9474404175, 448107.9979064148 5413896.884478368, 448105.6989061025 5413893.3261537785, 448105.99631370284 5413892.189438628, 448107.27946236933 5413891.3881821735, 448107.40297444514 5413891.26474441, 448107.50428261654 5413891.119278993, 448107.5760545354 5413890.951854142, 448107.60228083713 5413890.61809609, 448107.5038572385 5413890.285497907, 448106.6172913337 5413888.954203755)))"
Data conversion error converting "MULTIPOLYGON (((448100.8441455475 5413891.714878206, 448101.9592703201 5413890.98188699, 448106.1205941128 5413888.208348199, 448106.6172913337 5413888.954203755, 448119.14407122834 5413845.653079207, 448092.6749742952 5413897.204952865, 448100.8441455475 5413891.714878206)), ((448106.6172913337 5413888.954203755, 448100.67237835645 5413909.503891656, 448106.7869587879 5413905.444822483, 448109.62918978377 5413903.550697134, 448120.64824890136 5413896.199807953, 448121.5933127337 5413897.680712297, 448123.2713462651 5413894.396665344, 448122.05952597706 5413892.618079591, 448124.83604189946 5413886.811342596, 448120.10543935397 5413878.839895083, 448113.88899419684 5413882.98883365, 448115.2517064707 5413885.221816312, 448114.7051928522 5413885.593766304, 448116.0211177631 5413887.527021834, 448116.59004200075 5413887.199332007, 448117.82427589374 5413889.022176619, 448109.03617948655 5413894.984904597, 448109.5364449597 5413895.9474404175, 448107.9979064148 5413896.884478368, 448105.6989061025 5413893.3261537785, 448105.99631370284 5413892.189438628, 448107.27946236933 5413891.3881821735, 448107.40297444514 5413891.26474441, 448107.50428261654 5413891.119278993, 448107.5760545354 5413890.951854142, 448107.60228083713 5413890.61809609, 448107.5038572385 5413890.285497907, 448106.6172913337 5413888.954203755)))"; SQL statement:
SELECT a."AEROWAY",a."AGRICULTURAL",a."AMENITY",a."BARRIER",a."BUILDING",a."BUILDING:HEIGHT",a."BUILDING:LEVELS",a."BUILDING:ROOF:HEIGHT",a."BUILDING:ROOF:LEVELS",a."GOVERNMENT",a."HEALTHCARE",a."HEIGHT",a."HISTORIC",a."ID",a."INDUSTRIAL",a."LAYER",a."LEISURE",a."MAN_MADE",a."MILITARY",a."MONUMENT",a."OFFICE",a."PUBLIC_TRANSPORT",a."RAILWAY",a."RESIDENTIAL",a."RESTAURANT",a."ROOF:HEIGHT",a."ROOF:LEVELS",a."RUINS",a."SHOP", null as "place_of_worship", null as "historic:building", null as "grandstand", null as "house", null as "apartments", null as "barn", null as "education", null as "sustenance" , case when st_isvalid(a.the_geom) then a.the_geom else st_makevalid(st_force2D(a.the_geom)) end  as the_geom FROM OSM_POLYGONS_91e8eb35_2007_4b24_a20e_110da225ac15 as a,  ZONE_ENVELOPE_aec4dd0b_f243_47e1_bec2_53cdfdc6c13b as b WHERE a.the_geom && b.the_geom and st_intersects(CASE WHEN ST_ISVALID(a.the_geom) THEN a.the_geom else st_makevalid(a.the_geom) end, b.the_geom) [22018-200]>

@ebocher, did you manage to run Paris using OSM before ? Could it come from a recent modification in the code ?

**Comment by ebocher** [comment]
What is the place name value ? Paris ?

**Comment by j3r3m1** [comment]
yes. Should it be Paris, France ?

**Comment by ebocher** [comment]
Paris processed in 1 hour ;-(
