### ISSUE TITLE
Error when executing BDTopo_V2 workflow

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#232]
I have put several BDTopo files in a folder in order to apply the BDTopo_V2 workflow.
I have all the needed files (IRIS_GE.shp, ZONE_VEGETATION.shp, etc.) for several commune. To distinguish each commune, I have constructed all files with a prefixname (e.g. IRIS_GE.shp is 44109_IRIS_GE.shp for Nantes, etc.).
I had a look into the code and according to my understanding it should not raise any problem. However, when I apply the workflow, the algorithm is not able to load the files. I got the following error:

> [ERROR] org.orbisgis.orbisdata.datamanager.jdbc.JdbcDataSource - Unsupported file characters>

It seems that the problem comes from the fact that there is no filename given in the 'load' function in the code (thus the tablename is automatically set according to the path that contains '/' ?). Here is the code I suggest could make the loading fails:
```groovy
                    //Looking for IRIS_GE shape file
                    if(shapeFiles.find{ it.toLowerCase().endsWith("iris_ge.shp")}) {
                        //Load the shapefiles
                        shapeFiles.each { shp ->
                            datasource.load(shp, true)
                        }
```

**Comment by ebocher** [comment]
Sure to understand but the load function is able to load a file with several signatures
https://github.com/orbisgis/orbisdata/blob/master/data-manager/jdbc/src/main/java/org/orbisgis/orbisdata/datamanager/jdbc/JdbcDataSource.java#L537

https://github.com/orbisgis/orbisdata/blob/master/data-manager/jdbc/src/main/java/org/orbisgis/orbisdata/datamanager/jdbc/JdbcDataSource.java#L547

**Comment by gpetit** [comment]
Do we allow the possibility of opening several files (cities) at the same time?
If yes, it means that we can have the following scenario

- 1 file in which we have 1 zone (city)
- 1 file in which we have many zones (cities)
- _n_ files, in which we have 1 zone (city) (1 per file)
- _n_ files in which we have many zones (cities)

**Comment by j3r3m1** [comment]
No, we should have only 1 file (that could contains one or several cities).
For several files, we need several folders and then iterate by ourself on them.

**Comment by gpetit** [comment]
So I don't understand your message in the issue

> To distinguish each commune, I have constructed all files with a prefixname (e.g. IRIS_GE.shp is 44109_IRIS_GE.shp for Nantes, etc.).

**Comment by j3r3m1** [comment]
Anyway I still have trouble using the load function. I have remove my .m2, the .groovy and the database previously created. When I re-run my groovy script, I got the same error (unsupported file characters) when executing this command:
`datasource.load("/home/decide/testpaendora/17300_IRIS_GE.shp")`

The problem actually comes from file names starting with number. I have try IRIS_GE or IRIS_GE_17300 it works well.

**Comment by j3r3m1** [comment]
> So I don't understand your message in the issue
> 
> > To distinguish each commune, I have constructed all files with a prefixname (e.g. IRIS_GE.shp is 44109_IRIS_GE.shp for Nantes, etc.).

Sorry it was not clear. @ebocher told me that the current workflow only works for 1 file per folder. Thus I just confirm that we should make it work only for this configuration.

**Comment by gpetit** [comment]
+1000
So one file per layer (IRIS_GE, ROUTE, ...) and not possible to change the names
