### ISSUE TITLE
Workflow BDTopo - 56184

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#244]
I still have trouble with this commune when calculating the water fraction:
Only dimension >=2 should be kept before intersection.

**Comment by gpetit** [comment]
Is it the same as #245 ?

**Comment by j3r3m1** [comment]
The error is on the same function (intersection) but the error message is different. I thought it was only related to intersection which are linestring but impossible to reproduce the error in IntelliJ yet.

>Exception lors de l'appel de la fonction définie par l'utilisateur: "intersection(POLYGON ((288017.1 6742492.7, 288019.7 6742491.8, 288020.9 6742490.4, 288021.5 6742489.4, 288021.3 6742486.8, 288020.4 6742483.8, 288018.9 6742482, 288016.5 6742479.4, 288014.3 6742478.4, 288012.2 6742478.6, 288010.4 6742480.8, 288010 6742481.4, 288007.9 6742482.3, 288006.2 6742482.6, 288004.5 6742485.8, 288005.4 6742488.7, 288006.7 6742490.2, 288009 6742491.2, 288011.5 6742491.7, 288017.1 6742492.7), (287972.5 6742542.9, 287968.9 6742543.2, 287966.5 6742541.9, 287965 6742540.4, 287963.9 6742537.9, 287963.3 6742534.9, 287963 6742531, 287963.8 6742528.9, 287966.6 6742526.1, 287976 6742518.5, 287982.8 6742509, 287988.5 6742502.6, 287990.4 6742499.3, 287992.6 6742493.7, 287993.2 6742490.6, 287994 6742488.2, 287996.1 6742483.9, 288000.3 6742482, 288005.1 6742480.1, 288007.2 6742478, 288011.7 6742473.2, 288015.4 6742467.1, 288018.5 6742463, 288024.9 6742459, 288028.6 6742455.9, 288032.8 6742452, 288034.7 6742449.4, 288038 6742448.2, 288041.5 6742448.2, 288044.3 6742449.6, 288046.8 6742452.4, 288047.7 6742454.4, 288048.1 6742456.4, 288047.8 6742459.4, 288047 6742461.5, 288045.7 6742463.9, 288042.8 6742468.6, 288039.9 6742473.2, 288037.4 6742478, 288036 6742482.5, 288034.2 6742487.9, 288033.6 6742489.1, 288032 6742491.7, 288030.5 6742492.4, 288029 6742492.6, 288027.3 6742493.5, 288026.6 6742495.2, 288027.5 6742496.8, 288028 6742498.5, 288027.5 6742501.9, 288026.5 6742504.1, 288025.6 6742505.5, 288021.6 6742508.1, 288019.7 6742509.1, 288015.2 6742510.4, 288010.9 6742512.6, 287990.8 6742532.8, 287984.5 6742538.2, 287979.4 6742540.8, 287975.6 6742542.1, 287972.5 6742542.9)), POLYGON ((288138.508 6742000.015, 288139.9 6742002.7, 288138.3 6742005.5, 288140.3 6742009.5, 288142.7 6742011.8, 288144.8 6742013.8, 288147.5 6742016.6, 288149.3 6742019.8, 288142.3 6742021.8, 288137.3 6742023.4, 288132.8 6742026.9, 288131.2 6742033.4, 288127.1 6742033.3, 288123.8 6742031.6, 288126.7 6742028.1, 288127.2 6742022.4, 288123.3 6742024.6, 288118.5 6742024.5, 288117.147 6742024.717, 288106.131 6742038.789, 288106.5 6742038.6, 288111 6742040.9, 288115.8 6742038.5, 288118.6 6742048.9, 288113.6 6742050.5, 288111.6 6742055.6, 288113.7 6742059.5, 288111.4 6742061.7, 288107.7 6742064.6, 288104.7 6742066.6, 288100.1 6742068.1, 288097.7 6742070.7, 288097.8 6742075.9, 288092.2 6742079.8, 288090.5 6742088.7, 288087.3 6742088.7, 288084.6 6742086.4, 288081.964 6742084.73, 288078.6 6742082.6, 288076.9 6742087.9, 288073.2 6742087.9, 288071 6742081.9, 288066.9 6742081.8, 288058 6742087.9, 288053.9 6742090, 288049.7 6742091.4, 288044.8 6742096.3, 288036.1 6742106.1, 288033.4 6742110.2, 288029.1 6742113.2, 288024.2 6742114.2, 288021 6742115.3, 288016.7 6742115.3, 288012.7 6742115.4, 288009.2 6742115.3, 288006.3 6742115.4, 288002.6 6742112, 287999.1 6742108.4, 287995.1 6742107.2, 287995.1 6742104.2, 287996.127 6742103.435, 287987.2 6742106.6, 287981.819 6742108.552, 287980.3 6742113.3, 287980.1 6742120.6, 287983.2 6742121.5, 287987.3 6742122.8, 287983.3 6742128.5, 287978.8 6742129.1, 287976.6 6742132.3, 287979.2 6742136.5, 287987.9 6742136.5, 287994.3 6742136.9, 288003.9 6742138.3, 288001.5 6742143.2, 288001.4 6742150.4, 288003 6742152.9, 288000.5 6742154.4, 287996.6 6742157, 287989.5 6742158.5, 287988.1 6742161.5, 287984.6 6742160.5, 287983 6742157.5, 287977.6 6742159.2, 287977.7 6742164.6, 287970.6 6742163.6, 287967.3 6742162.5, 287965.6 6742167.7, 287964.7 6742170.8, 287964.7 6742173.7, 287961.2 6742179.9, 287967.8 6742181.8, 287966.3 6742184.5, 287958.3 6742187.5, 287964.8 6742188.5, 287964.9 6742193.6, 287965 6742199.6, 287962.1 6742202.6, 287958.9 6742205.3, 287955.1 6742208.5, 287949 6742205.5, 287944.6 6742207.9, 287941 6742212.3, 287940 6742215.8, 287940.1 6742219.7, 287941.1 6742222.9, 287942 6742226.7, 287947 6742230.6, 287953.8 6742229.3, 287956.2 6742232.7, 287955.1 6742235.9, 287955.5 6742248, 287954.4 6742252.5, 287952 6742256.2, 287954.8 6742259.2, 287957.4 6742262.2, 287956.999 6742264.895, 287961.1 6742270.6, 287969.2 6742280.8, 287977.8 6742290.1, 287984.4 6742296.5, 287990.7 6742302.1, 287995.8 6742307.8, 287999.8 6742313, 288002.6 6742318.2, 288004.6 6742325.7, 288006.3 6742333.1, 288007.6 6742338.1, 288009 6742343.8, 288014.815 6742358.226, 288015.1 6742358.1, 288018.1 6742359.9, 288020.5 6742364.6, 288018.757 6742368.007, 288021.417 6742374.606, 288025.7 6742376.6, 288029.5 6742374, 288034 6742373.9, 288036.7 6742380.3, 288046 6742378.1, 288047.3 6742384.8, 288053.3 6742387.7, 288053.5 6742396.8, 288048.5 6742402.3, 288048.6 6742407.8, 288045.6 6742407.9, 288041.9 6742406.6, 288041.4 6742411, 288042.6 6742416.8, 288040.7 6742424.7, 288043 6742429.1, 288053.2 6742431.9, 288046.7 6742433.5, 288046 6742437.5, 288042.8 6742441.8, 288042.8 6742447.8, 288046.2 6742451, 288048.1 6742455.2, 288047.952 6742455.661, 288048.1 6742456.4, 288047.8 6742459.4, 288047 6742461.5, 288045.7 6742463.9, 288042.8 6742468.6, 288042.292 6742469.406, 288043.2 6742474.4, 288042.1 6742478, 288040 6742482, 288039.5 6742490.5, 288036.3 6742494.8, 288032.3 6742496.8, 288032.3 6742501.3, 288031.8 6742508.8, 288024.2 6742510.1, 288021.9 6742512.4, 288021.7 6742524.8, 288017.6 6742526, 288009.1 6742527.5, 288006.7 6742530, 288006.6 6742535.1, 288006.8 6742541, 288003.7 6742542.6, 287999.6 6742544.6, 287999.1 6742553.8, 287995.8 6742557, 287994.8 6742561.2, 287992.7 6742563.1, 287989 6742570.1, 287987.9 6742575.2, 287988.1 6742580.7, 287988 6742585.2, 287996.3 6742585.3, 288001.1 6742584.1, 288001 6742579.1, 288002 6742569.5, 288001.8 6742565, 288004.5 6742562.3, 288007.8 6742559, 288010.3 6742556.5, 288016 6742550.9, 288019.7 6742545.9, 288021.5 6742540.2, 288026.6 6742534.9, 288031.8 6742532.3, 288033.6 6742526.5, 288039.4 6742522.5, 288043.7 6742521.2, 288052.5 6742522.7, 288057.5 6742523.7, 288059.5 6742525.6, 288064.5 6742525.5, 288068 6742529.2, 288070.6 6742531.8, 288074.5 6742530.5, 288078 6742532.3, 288081.3 6742530.6, 288084.8 6742529.9, 288089.4 6742526.8, 288093 6742528.4, 288098.2 6742529.5, 288099.5 6742533.4, 288106.5 6742533.2, 288109.5 6742535.2, 288112.6 6742533.1, 288113.7 6742529.7, 288114.9 6742526.7, 288123.7 6742531.2, 288125.5 6742535.1, 288131.7 6742536, 288137.6 6742533.9, 288140.1 6742531.4, 288142.5 6742529, 288148.1 6742529.3, 288151.2 6742526.2, 288156.5 6742524.8, 288159.4 6742521.8, 288166.6 6742523.6, 288177.4 6742521.7, 288180.9 6742521.1, 288184.5 6742520.7, 288190.3 6742514.6, 288192.3 6742512.6, 288193.8 6742506.6, 288197.1 6742508.4, 288200.1 6742508.7, 288203.2 6742505.4, 288207.5 6742505.8, 288209.6 6742510.1, 288212.3 6742511.4, 288216.3 6742514.4, 288221.3 6742516.8, 288221.3 6742520.4, 288234.1 6742520.1, 288239.3 6742523.2, 288244.2 6742523, 288247.3 6742525.1, 288254.8 6742527.1, 288259.5 6742527, 288262.3 6742522.9, 288258.6 6742514.7, 288257.2 6742508, 288253.2 6742506.8, 288248.9 6742503.9, 288237.3 6742505.3, 288230.8 6742505.3, 288227.7 6742501.3, 288223.2 6742504.3, 288220.2 6742502.3, 288216.9 6742500.3, 288217.1 6742497, 288215.8 6742491.7, 288220 6742487.4, 288225.1 6742486.3, 288227.5 6742483.8, 288231 6742482.3, 288231 6742474.9, 288228.4 6742471.6, 288231.4 6742469.1, 288235.2 6742470.3, 288242.9 6742470.2, 288246.9 6742469.6, 288250.9 6742469.1, 288252.9 6742467, 288252.8 6742464.1, 288254.8 6742461.1, 288250.8 6742456.1, 288242.9 6742452.7, 288239.3 6742453.2, 288236.8 6742451.1, 288233.3 6742451.3, 288225.1 6742452, 288213.4 6742456, 288208.2 6742458.8, 288204.6 6742446.4, 288204.7 6742437.2, 288202.6 6742434.5, 288201.6 6742429.6, 288200.5 6742427.1, 288201.5 6742422.6, 288204.7 6742422.5, 288210.6 6742424.5, 288215.7 6742425.4, 288221.4 6742422.4, 288229.5 6742421.3, 288233.5 6742419.3, 288241.4 6742417.8, 288246.5 6742415.2, 288250.9 6742412.7, 288254.3 6742412.2, 288259.4 6742409.1, 288262.3 6742409.2, 288270.4 6742406.7, 288276.3 6742405, 288283 6742403.7, 288286.9 6742405.7, 288288.8 6742402.4, 288290.6 6742399.1, 288306.9 6742397.6, 288309.9 6742393.7, 288316.2 6742390.6, 288317.7 6742393.1, 288322.2 6742393.6, 288327 6742393.5, 288332.2 6742391.5, 288343.3 6742389.6, 288350.1 6742385.4, 288355.4 6742389.3, 288361.4 6742387.2, 288365.2 6742385.1, 288373.1 6742383.2, 288378.1 6742379.8, 288379 6742375, 288386.2 6742375.1, 288389.6 6742375.1, 288404.9 6742373.6, 288412.7 6742368.3, 288425.9 6742366.8, 288429.9 6742365.7, 288436.9 6742364.7, 288440 6742363.7, 288441.9 6742359.6, 288437 6742357.3, 288439.1 6742350.2, 288433.7 6742349.6, 288431.3 6742345.2, 288427.8 6742348.9, 288424 6742353.5, 288418.8 6742354.8, 288414.7 6742357.8, 288410.5 6742354.4, 288407.4 6742358, 288400.7 6742358, 288393.7 6742355.6, 288388.9 6742358.1, 288385.9 6742359.1, 288382.9 6742360.1, 288378.9 6742361.7, 288370.3 6742366, 288361 6742373.3, 288357.8 6742374.3, 288353.1 6742376.8, 288349.1 6742378.9, 288345.1 6742377.9, 288342.1 6742379.4, 288335.6 6742380, 288332.1 6742379, 288326.6 6742381.1, 288321.8 6742379.6, 288308.7 6742388.8, 288305.1 6742386.7, 288302.2 6742388.8, 288299.2 6742387.8, 288294.3 6742385.2, 288289.3 6742387.9, 288282.2 6742389.4, 288276.2 6742392, 288272.2 6742394.1, 288269.3 6742398.5, 288262.2 6742397.1, 288257.2 6742397.2, 288255.3 6742401.1, 288251.4 6742401.2, 288248.3 6742402.2, 288245.3 6742402.2, 288242.4 6742403.7, 288238.6 6742401.9, 288234.4 6742403.3, 288230.6 6742399.5, 288229.2 6742403.9, 288225.9 6742405.9, 288222.4 6742404.9, 288215.4 6742408.4, 288212.4 6742407.5, 288207.4 6742408.5, 288203.4 6742411.5, 288201.4 6742409.5, 288195.6 6742408.8, 288187.5 6742410.7, 288184.3 6742413.7, 288177.3 6742405.7, 288177.5 6742397.8, 288177.2 6742389.7, 288174.9 6742387.5, 288172.3 6742388.8, 288168.8 6742388.7, 288165.3 6742388.9, 288158.3 6742389.7, 288163.3 6742392.2, 288164 6742397.1, 288168.9 6742404.8, 288171 6742408.8, 288173 6742412.8, 288175.6 6742421.8, 288180.2 6742426.5, 288183.6 6742428.6, 288174.6 6742429.8, 288170.4 6742434.1, 288164.7 6742432.3, 288161.7 6742433.9, 288158.7 6742434.9, 288155.7 6742436.9, 288151.9 6742438.9, 288150.1 6742430.1, 288126.1 6742428.3, 288122.6 6742423.5, 288122.6 6742419.1, 288115.9 6742414.9, 288111.6 6742415.4, 288115.1 6742419.3, 288118.1 6742423, 288115.8 6742428.1, 288109.6 6742430.3, 288107.5 6742428.1, 288108.7 6742422.4, 288102.5 6742421.4, 288095.7 6742416.8, 288092.6 6742418.4, 288089.6 6742418.4, 288091.6 6742414.5, 288092.8 6742409, 288095.8 6742406.1, 288097.4 6742398.3, 288100.1 6742395.7, 288105.9 6742398.6, 288116.5 6742400.3, 288116.4 6742392.8, 288112.2 6742386.3, 288106.9 6742389, 288105.4 6742392.4, 288102.3 6742392.4, 288099.3 6742387.9, 288093.8 6742386.7, 288090.3 6742385.5, 288087.3 6742384.5, 288089.3 6742380.5, 288090.8 6742375.4, 288088.6 6742368.7, 288090.2 6742365.5, 288091.1 6742356.5, 288094.1 6742352.5, 288094.6 6742349.6, 288095.2 6742345.7, 288092.8 6742343.3, 288094.9 6742335.4, 288101.3 6742335.5, 288103.8 6742327.4, 288105.3 6742324.4, 288108.2 6742318.6, 288112.8 6742319.3, 288115.3 6742321.3, 288119.3 6742325.3, 288124.8 6742329.6, 288131.8 6742328.2, 288135.4 6742329.4, 288137.3 6742324.6, 288140.5 6742321.3, 288145.4 6742313, 288149 6742313.9, 288148.7 6742323.1, 288150.9 6742325, 288154.8 6742323, 288154.7 6742328.9, 288157.8 6742333, 288157.7 6742341.6, 288158.9 6742345, 288160 6742348.3, 288155 6742350, 288154 6742353, 288160 6742352.8, 288162.5 6742357.4, 288163.1 6742362.9, 288165.1 6742369.9, 288167.1 6742377.6, 288170.2 6742375.6, 288167.5 6742363.2, 288170.1 6742360.8, 288168 6742351.8, 288168.1 6742348, 288165.7 6742341.4, 288164.4 6742336.9, 288164.8 6742332.9, 288167.8 6742329.9, 288165.3 6742322.7, 288162.7 6742318.9, 288161.7 6742315, 288160.4 6742312.4, 288154.6 6742304, 288153.1 6742301, 288151.6 6742298, 288149.9 6742294.9, 288147.2 6742289.6, 288145.6 6742286.6, 288144.5 6742283.1, 288142.9 6742280.1, 288141.4 6742277.1, 288136.9 6742275.2, 288135.3 6742285.5, 288131 6742289.8, 288128.1 6742288.7, 288125.4 6742287.3, 288122.5 6742288.8, 288119 6742288.7, 288115.5 6742290.8, 288110.3 6742290.4, 288105.5 6742291.4, 288102.5 6742289.9, 288102 6742294, 288094.6 6742292.6, 288090.8 6742295, 288087.4 6742290.5, 288083.5 6742289.6, 288079.6 6742288.6, 288075.6 6742289.7, 288073.6 6742291.8, 288071.4 6742289.4, 288067.6 6742290.7, 288064.3 6742289.1, 288060.6 6742291.3, 288059.5 6742287.8, 288056.5 6742286.8, 288050.6 6742285, 288049.2 6742282.2, 288055.5 6742277.5, 288055.3 6742271.8, 288059.6 6742269.6, 288063.6 6742267, 288065.4 6742269.8, 288068.3 6742269.7, 288071.4 6742271.9, 288074.4 6742273.7, 288079.5 6742274.1, 288086.4 6742273.7, 288090.9 6742273.6, 288100.2 6742273.7, 288104.4 6742271.4, 288111 6742270.3, 288116.8 6742270.3, 288126.5 6742272.3, 288134.6 6742272, 288137.3 6742269.2, 288140.4 6742271.2, 288143.4 6742269, 288145.8 6742264, 288150.3 6742265.1, 288153.3 6742264.1, 288157.4 6742263, 288163.2 6742263.3, 288167.5 6742262, 288170.6 6742257.2, 288168.2 6742253.9, 288184.2 6742252.3, 288193.3 6742250.5, 288195.9 6742248, 288198.7 6742245.1, 288209.6 6742243.6, 288217.1 6742241.6, 288221.1 6742240.5, 288224.2 6742237.2, 288228.3 6742238.6, 288234.9 6742238.4, 288239 6742240.4, 288242.1 6742241.4, 288242 6742235.4, 288244.7 6742231.3, 288242 6742223.7, 288237.6 6742221.7, 288233.4 6742213.3, 288230.8 6742205.5, 288228.7 6742202.5, 288222.8 6742193.1, 288220 6742182.1, 288222.1 6742180.1, 288229.6 6742178.5, 288235 6742180.8, 288240.5 6742174.4, 288254.2 6742172.3, 288259.5 6742171.3, 288261.4 6742169.2, 288264.4 6742169.2, 288267.6 6742169.1, 288271.5 6742167.1, 288277.4 6742167.2, 288279.4 6742165, 288283 6742166.2, 288284.7 6742169.8, 288289.3 6742171.9, 288294.4 6742174, 288296.4 6742170.5, 288297.2 6742166.1, 288299.4 6742162.8, 288301.9 6742160.4, 288308.5 6742162.6, 288321.8 6742157.3, 288328.3 6742154.2, 288336.4 6742152.6, 288344.3 6742150.6, 288347.4 6742147.3, 288349.7 6742144, 288350.1 6742139.4, 288352.2 6742137.5, 288356.7 6742139.8, 288363.1 6742135.4, 288365.1 6742132.3, 288367.2 6742130.2, 288370.1 6742131.4, 288373.1 6742132.4, 288376.3 6742132.5, 288382.1 6742131.4, 288387 6742129.3, 288390.5 6742130.2, 288393.9 6742133.2, 288397.1 6742134.2, 288400.2 6742136.2, 288406 6742139, 288411.4 6742142, 288414.1 6742140, 288417.1 6742141, 288417 6742147, 288422 6742148.6, 288423.3 6742151.3, 288430.9 6742157.2, 288432.2 6742159.9, 288435.2 6742164.1, 288427.6 6742168.9, 288426.5 6742175.5, 288425.2 6742180.8, 288427.5 6742182.9, 288431.5 6742180.8, 288435.4 6742173.7, 288440.3 6742172.9, 288443.9 6742172.8, 288446.6 6742167.2, 288451.5 6742170.2, 288450.3 6742173.7, 288450.5 6742177.6, 288448.5 6742181.5, 288444.4 6742185.7, 288444.6 6742189.9, 288447.4 6742195.4, 288448.5 6742198.2, 288450.6 6742201.1, 288456.4 6742199.1, 288457.6 6742203.6, 288459.5 6742209.1, 288463.7 6742211.2, 288464.3 6742214.7, 288463.7 6742218.8, 288469.8 6742221.5, 288475 6742219.5, 288482.5 6742219.3, 288484.7 6742213.3, 288487.9 6742208.9, 288492.9 6742207.2, 288495.6 6742200.3, 288498.5 6742199.3, 288500.5 6742197.3, 288503 6742198.6, 288500.5 6742202.4, 288500.6 6742205.4, 288503 6742207.7, 288509.9 6742210.3, 288514.9 6742212.9, 288517.7 6742214.1, 288520.3 6742210.4, 288524.5 6742211, 288528.6 6742214, 288531.2 6742216, 288532.6 6742212.5, 288529.1 6742210.5, 288525.6 6742208.1, 288520.6 6742205.2, 288516.5 6742202.1, 288506.3 6742196, 288503 6742193.8, 288495.2 6742189.2, 288492.6 6742186.5, 288489.4 6742184.4, 288487.4 6742181.4, 288481.4 6742180.4, 288475.4 6742175.1, 288472.3 6742172.5, 288469.7 6742170.2, 288467.8 6742168.1, 288463.5 6742167, 288458.3 6742166.6, 288458.3 6742162.1, 288452.3 6742158.8, 288447.2 6742154.7, 288444.2 6742152.3, 288440.2 6742149.8, 288436.6 6742147.3, 288428.2 6742140.4, 288421.1 6742137, 288416 6742133, 288410.7 6742129.6, 288407 6742132.1, 288404.5 6742128.3, 288397.5 6742125.6, 288401.5 6742121.7, 288395.334 6742117.722, 288395.3 6742117.7, 288392.7 6742116.1, 288389.9 6742113.2, 288384.3 6742110.6, 288380.7 6742108.1, 288377.8 6742105.8, 288372.8 6742102.4, 288366.8 6742098.4, 288358.3 6742092.2, 288355.7 6742089.5, 288353.5 6742087.5, 288349.7 6742085.6, 288346.7 6742083.1, 288340.9 6742080.3, 288335.9 6742082, 288333.4 6742079.3, 288334 6742075.1, 288327.7 6742069.3, 288324.6 6742066.8, 288321.5 6742064.8, 288321.5 6742061.1, 288317 6742058.9, 288312.5 6742056.9, 288306.8 6742055.5, 288302.5 6742054, 288297.7 6742049.1, 288294.9 6742047.1, 288292.4 6742045.1, 288288.7 6742041.3, 288285.4 6742039.1, 288287.3 6742034.5, 288284.8 6742031.7, 288280.9 6742027.6, 288275.7 6742023.1, 288272.3 6742025.8, 288268.2 6742020.3, 288266.5 6742017, 288268.5 6742014.7, 288262.3 6742014.4, 288256.9 6742006.1, 288258.1 6742000.6, 288253 6741992.4, 288248.5 6741984.7, 288243.8 6741982.5, 288240.7 6741979.3, 288238.9 6741973.6, 288231.9 6741966.9, 288230.6 6741961.5, 288225.3 6741961.7, 288222.6 6741955, 288219.5 6741953.8, 288216.7 6741952.8, 288215.6 6741944.8, 288212.6 6741942.8, 288208.2 6741937.3, 288204.6 6741933.9, 288201.5 6741930.8, 288195 6741930.5, 288193.3 6741927.9, 288191.25 6741928.095, 288187 6741931.1, 288175.4 6741949.1, 288153.6 6741980.6, 288138.508 6742000.015), (287977.9 6742206, 287980.3 6742199.6, 287977.8 6742194.5, 287975.3 6742189.8, 287979.3 6742185.1, 287975.2 6742181.6, 287977.7 6742178.5, 287979.2 6742170.3, 287984.4 6742170.6, 287989.6 6742170, 287993.6 6742169.4, 287998.7 6742167.8, 287999.5 6742163.9, 288003.6 6742166.4, 288007.1 6742166.2, 288011.3 6742166.4, 288016.5 6742163.1, 288019.5 6742158.2, 288021.8 6742156.1, 288017.5 6742149.2, 288020.4 6742145.2, 288021.8 6742142.3, 288027.4 6742140.7, 288032.3 6742141.5, 288033.8 6742138.1, 288036.5 6742132, 288040.7 6742129.5, 288049 6742129.7, 288054.3 6742136.1, 288052.6 6742140.8, 288049.8 6742145.2, 288043.5 6742152.7, 288046.2 6742155.4, 288048.7 6742152.7, 288051 6742150.3, 288057.4 6742144.5, 288060.4 6742141.9, 288063.4 6742145.9, 288061.1 6742149.1, 288061.6 6742154.7, 288055.7 6742156.1, 288053.3 6742164.1, 288048.6 6742167.9, 288048.8 6742172.7, 288046.2 6742175.6, 288042.7 6742178.9, 288042.9 6742182, 288040.2 6742183.2, 288042.3 6742186.9, 288036.7 6742188.1, 288036.3 6742193, 288031.7 6742199.1, 288031.5 6742203.5, 288028.5 6742205.3, 288024.9 6742210.1, 288019.1 6742211.6, 288018.9 6742214.9, 288020.7 6742220, 288013.1 6742221.6, 288005.8 6742212.5, 287996.4 6742211.4, 287993.5 6742209.9, 287989.2 6742209.6, 287984.4 6742206.4, 287977.9 6742206))): no outgoing dirEdge found [ (288138.508, 6742000.015, NaN) ]"

**Comment by j3r3m1** [comment]
OK I did reproduce the error in IntelliJ using the geometries that cause the problem. I found that to avoid this problem, the only solution is to reduce the precision of the geometries. I have tried to apply this method to the waterFraction IProcess and it works well whatever the number of decimal I use for the function st_precisionReducer (I have try n = 40 it works...).
I do not understand why the first coordinates of my second geometry has three decimals instead of the usual one for the BDTopo (288138.508 6742000.015).
Anyway I think the solution is not to patch the waterFraction calculation but rather add a precisionReducer for the input data. What do you think ?

**Comment by gpetit** [comment]
Why not. 
The only concern I imagine would be that the input data may no longer be consistent with each other (between IRIS, road, rails). And so it might generate micro / weird RSU ?!

**Comment by j3r3m1** [comment]
I do not think it will generate trouble since the idea is to apply the same st_precisionReducer on each table, thus if points are identical at the beginning, they will remain identical at the end.

**Comment by gpetit** [comment]
Hum... cross finger ;-)
And what about ST_Force2D ? Have you tried ?

**Comment by j3r3m1** [comment]
it does not work, I have tried it in both cases

**Comment by gpetit** [comment]
Same bug with Auray (56007)

**Comment by j3r3m1** [comment]
time to modify the input data scripts ! Ha ha

**Comment by gpetit** [comment]
Ok. Just as a reminder concerning the geometries
- on `BUILDING` we have `ST_FORCE2D(ST_NORMALIZE(THE_GEOM))` (line 116)
- on `ROAD` we have `ST_FORCE2D(THE_GEOM) .... FROM EXPLODE` (line 269)
- on `RAIL` we have `ST_FORCE2D(THE_GEOM) .... FROM EXPLODE` (line 363)
- on `HYDRO` we have `ST_FORCE2D(THE_GEOM) .... FROM EXPLODE` (line 416)
- on `VEGET` we have `ST_FORCE2D(THE_GEOM) .... FROM EXPLODE` (line 483)
- on `IMPERVIOUS` we have `ST_FORCE2D(THE_GEOM) .... FROM EXPLODE` (line 558)

Remark : we should also add the `ST_FORCE2D` for `ZONE`

So you are suggesting to modify `HYDRO` and  `VEGET` (and maybe also  `IMPERVIOUS` ?) like this
`ST_PrecisionReducert(ST_FORCE2D(THE_GEOM), 40)` ?
I don't understand why `40` ?! Why not `3` or `2` ?

**Comment by j3r3m1** [comment]
I suggest that all input data should get a precision reducer in order to keep consistency. Concerning the n parameter, 1, 2 or 3 are OK for me, the 40 I gave was just an example of strange behavior since even using n = 40 removed the error...

**Comment by gpetit** [comment]
Ok. we have to talk about that with @ebocher

**Comment by gpetit** [comment]
Instead of using a `ST_PrecisionReducer() on RSU, @ebocher suggest to include the intersection inside a `ST_MakeValid()`

**Comment by gpetit** [comment]
See #247 -> it seems that adding ST_MakeValid on input layers is the solution
