### ISSUE TITLE
Workflow BDTopo - SRID

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#250]
I just computed Plougoumelen (see #245 ) and I finally got my 4 geojson files.

And surprise
- `zone_56167_block_indicators.geojson`, `zone_56167_rsu_indicators.geojson` and `zone_56167_RSU_LCZ.geojson` are in EPSG:4326
- `zone_56167_building_indicators.geojson` is in EPSG:2154

@ebocher @SPalominos @j3r3m1

**Comment by j3r3m1** [comment]
If all tables has the same (and a correct...) SRID in inputs, the table containing building and RSU indicators must also have the same SRID. Concerning the block, we should set the SRID at the end of the block creation using the future new function set_srid (see issue in orbisgis/orbisdata#194).

**Comment by ebocher** [comment]
Still valid ?

**Comment by gpetit** [comment]
Resolved. Thx
