### ISSUE TITLE
Workflow BDTopo - Filter output geoms

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#251]
In the `zone_xxx_block_indicators.geojson` and `zone_xxx_building_indicators.geojson` output files there is too much geometries. 
Indeed, we keep all the input object even those who are not in the study area.
So we have to remove:
- all the buildings where `ID_ZONE='outside'`
- all the blocks where `ID_RSU is null` (if it intersects the ZONE (in a majority or minority way), then the ID_RSU is affected. So only the blocks that do not intersects the ZONE have ID_RSU = null)

There will just be a concern about the blocks that are straddling the area: they will be duplicated from one area to another.
If we want to avoid this problem, we should only keep the blocks that are mostly in the area.

@ebocher @j3r3m1

**Comment by j3r3m1** [comment]
I have been convinced that it is more an opportunity to understand the indicator value of a given building (having the buildings that have been used for the calculation) than a problem but actually this is a bit more complicated than expected.
It is not only a problem of feeding a big database with results, it is also a problem when climatologists will model the climate of an area covering several cities. They will have duplicated buildings that they will have to filter. Thus we would have to filter each commune to avoid that. But then we will loose the buildings around the area they want to run (which is worse for visual and verification purpose).

**Comment by j3r3m1** [comment]
OK after a call to Robert, it should not be a problem to keep all of them.
If I am right, blocks have RSU ID and buildings have zone id. Then it will be easy for them to remove the non appropriate buildings and blocks.

**Comment by gpetit** [comment]
Ok, so to summarize the call with @j3r3m1 , we let the results as they are.
If the user want to remove duplicates objects, he has to :
- remove buildings that have `ID_ZONE` = `outside`
- remove blocks that have `ID_RSU` = `null`
- manage as he wants with blocks that overlaps _n_ zones (since they will be duplicated)

**Comment by gpetit** [comment]
This point has been documented here : https://github.com/orbisgis/geoclimate/blob/master/docs/for_users/execution_examples/run_bd_topo_v2.md#Warning
