### ISSUE TITLE
Workflow BD Topo - final log message

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#260]
When finishing to execute the workflow BD Topo, we have an error in the log message

```
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - 74010 has been processed
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Number of areas processed 0 on 1
```

We are writing that _0_ areas have been processed on _1_. It should be _1_ on _1_ (or _n_ on _n_)

@ebocher @j3r3m1

**Comment by ebocher** [comment]
my fault the index must start at  not 0
here the pb
https://github.com/orbisgis/geoclimate/blob/master/processingchain/src/main/groovy/org/orbisgis/orbisprocess/geoclimate/processingchain/Workflow.groovy#L141

**Comment by j3r3m1** [comment]
I am currently modifying the workflow bdtopo and its tests. I will include a specific commit for this change (add + 1 to the index...)

**Comment by gpetit** [comment]
In the same spirit, we have no information about the zone currently processed. We have it's zone id only when it's finished.
```
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - 67471 has been processed
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Number of areas processed 28 on 33
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Executing the parametersAndAbstractTables.sql script
```

It could be interesting to indicates the ZONE ID when starting a new zone (so that we know where we are, and what city may have problems ...). So something like this

```
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - 67471 has been processed
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Number of areas processed 28 on 33
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Starting to process 67358
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Executing the parametersAndAbstractTables.sql script
```

@j3r3m1 @ebocher

**Comment by j3r3m1** [comment]
You are right I do that too

**Comment by j3r3m1** [comment]
both done in #258
