### ISSUE TITLE
Workflow OSM: place name with spaces

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#263]
I got an error when applying the OSM workflow on city names with spaces.

Here is the error:
> [INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Create the units of analysis...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing the abstract model to build the RSU
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing vegetation...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing hydrographic...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing road...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing rail...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Grouping all tables...
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
Erreur de syntaxe dans l'instruction SQL "DROP TABLE IF EXISTS PARIS[*] 6E ARRONDISSEMENT_PREPARED_RSU_DATA;
                CREATE TABLE PARIS 6E ARRONDISSEMENT_PREPARED_RSU_DATA(THE_GEOM GEOMETRY) AS (SELECT ST_SETSRID(ST_TOMULTILINE(THE_GEOM),4326) 
                 FROM ZONE_B958AE42_E9CA_4B66_8143_12BBDC156269) UNION (SELECT ST_FORCE2D(THE_GEOM) AS THE_GEOM FROM VEGETATION_TMP42B1DCB8_92AE_4FC0_BECE_42C70D12632B) UNION (SELECT ST_FORCE2D(THE_GEOM) AS THE_GEOM FROM HYDROGRAPHIC_TMP804B6EBB_C22A_4602_8CEC_0A8C8424F009) UNION (SELECT ST_FORCE2D(THE_GEOM) AS THE_GEOM FROM INPUT_ROAD_A681D0B3_E407_4CC2_8CE2_3A64B2B77FEA WHERE ZINDEX=0 OR CROSSING = 'bridge') UNION (SELECT ST_FORCE2D(THE_GEOM) AS THE_GEOM FROM INPUT_RAILS_063826BA_E5D3_4A37_B61F_F7113760034A WHERE ZINDEX=0 OR CROSSING = 'bridge');

**Comment by j3r3m1** [comment]
Same with "-":
> [INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Grouping all tables...
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
Erreur de syntaxe dans l'instruction SQL "DROP TABLE IF EXISTS SAINT-[*]JORIOZ_PREPARED_RSU_DATA;
                CREATE TABLE SAINT-JORIOZ_PREPARED_RSU_DATA(THE_GEOM GEOMETRY) AS (SELECT ST_SETSRID(ST_TOMULTILINE(THE_GEOM),4326) 
                 FROM ZONE_7982740E_612E_43FD_8AA6_187A6A31A869) UNION (SELECT ST_FORCE2D(THE_GEOM) AS THE_GEOM FROM VEGETATION_TMP428DCC45_E83C_4369_9840_A6C32CA233FC) UNION (SELECT ST_FORCE2D(THE_GEOM) AS THE_GEOM FROM HYDROGRAPHIC_TMPEE480F88_F35B_49CF_B8AB_01A5923A255B) UNION (SELECT ST_FORCE2D(THE_GEOM) AS THE_GEOM FROM INPUT_ROAD_752C6A13_EB1E_4092_BA50_DC9B23E29013 WHERE ZINDEX=0 OR CROSSING = 'bridge') UNION (SELECT ST_FORCE2D(THE_GEOM) AS THE_GEOM FROM INPUT_RAILS_8CA8D2E7_EABF_40B3_BBCE_16D600777828 WHERE ZINDEX=0 OR CROSSING = 'bridge');

**Comment by ebocher** [comment]
Clisouet Vannes -> works for me

**Comment by j3r3m1** [comment]
OK the problem came from the prefixname, not the city name itself.
