### ISSUE TITLE
Workflow OSM - Orange

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#264]
Same problem than with the BDTopo when creating intersection. The problem is here related to the intersection between the road layer and the RSU layer.

I have investigated it, it only works when I apply a ST_MAKEVALID on the RSU geometry. Thus I think we need to make valid the RSU geometries.

> [INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Start computing RSU indicators...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Geometry properties
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing RSU free external facade density
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Unweighted statistical operations from lower scale
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing road fraction
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
Exception lors de l'appel de la fonction définie par l'utilisateur: "intersection(POLYGON ((-119.35488646561173 34.84934419662282, -119.35371858834263 34.8517902098944, -119.35251048834263 34.853794909894404, -119.35221903934152 34.85420229898398, -119.2876453471485 34.97180840117094, -119.18616508991695 35.08631346428902, -119.16968027255012 35.109356036791006, -119.16962127255012 35.10942613679101, -119.14041537156123 35.13793507553508, -118.99239108489945 35.3049580093511, -118.99166198489947 35.3056159093511, -118.90246676269021 35.37020533890147, -118.89000090592336 35.38237371361088, -118.84657725948833 35.41067691395058, -118.64448192765829 35.55702132427194, -118.64443452765828 35.55704842427195, -118.55506179016038 35.605178210381055, -118.55348699016038 35.60597541038105, -118.44395374607852 35.657323067791225, -118.44387904607852 35.657355367791226, -118.23789114565342 35.72618583944952, -118.20004904474416 35.741385892829896, -118.19997404474417 35.7414077928299, -118.19929509902097 35.73908263624377, -118.11939376635387 35.76578151711131, -118.11934446635387 35.76579341711131, -117.95313304622569 35.798532839223505, -117.95306194622569 35.798543739223504, -117.76196592708348 35.81850291654314, -117.76183752708349 35.81851011654314, -117.64635513342883 35.82164402213692, -117.64624113342883 35.82164382213692, -117.5357114150461 35.81839305911723, -117.5297547150461 35.81805285911723, -117.4047171701041 35.80696594869531, -117.4046274701041 35.80695514869531, -117.08269986175999 35.74100288750655, -116.77591754041586 35.62322473553947, -116.77392164041586 35.62226353553947, -116.52289222745674 35.478120018477895, -116.52193102745673 35.477471318477896, -116.27112802545874 35.277130855944456, -116.27106662545874 35.27707315594446, -116.03960446108955 35.01818622847997, -115.85641374410389 34.72316362602932, -115.72701754522883 34.400900071677974, -115.72700214522882 34.40084937167798, -115.65072454242555 34.019874049881246, -115.650627657702 33.98788758039421, -115.64641710143036 33.98823971681591, -115.64632370143036 33.987122916815906, -115.6503141428994 33.88438073948801, -115.6495476991712 33.63133951660589, -115.66279537394853 33.563025605308894, -115.66525576341121 33.49967778466499, -115.66526936341121 33.49959408466499, -115.71160882105768 33.31131067782423, -115.72351602966802 33.249909110645575, -115.72353162966802 33.24985661064558, -115.73089116115275 33.2329639541172, -115.74189320709115 33.18826117172161, -115.86728216202685 32.89317303898457, -115.86773746202685 32.89230283898457, -115.91673456749247 32.806389404110675, -115.91801461215456 32.80345126125979, -115.91955129401579 32.801450446014684, -115.93956675348869 32.76635455907291, -115.9396095534887 32.76628545907291, -116.11334024193134 32.527255789766386, -116.11344444193134 32.52713268976638, -116.15660611864823 32.47780466471015, -116.15701361864822 32.47735406471015, -116.19807054145573 32.438808333557226, -116.2146094822159 32.41727403576557, -116.21465068221592 32.41723213576557, -116.27369234534785 32.36781183594363, -116.39506409487699 32.25386362679888, -116.395111094877 32.253826226798886, -116.4734439743892 32.200611508691914, -116.51140277297186 32.16883843342058, -116.55781595198457 32.14329418508753, -116.64440212822521 32.08447266608684, -116.64446672822521 32.08443556608684, -116.72012978380214 32.04312448119038, -116.73036958380213 32.03781688119038, -116.73460794715251 32.045993833680235, -116.85043708892695 31.98224538066259, -117.08080131650259 31.908624477192728, -117.07879455525584 31.901752007170106, -117.07886955525584 31.901730107170106, -117.08087576395839 31.908600684918138, -117.21906008063762 31.864439078984983, -117.60347038950651 31.819830232687394, -117.98927557490859 31.850089010745204, -118.36203097161082 31.954082515167556, -118.70778050249736 32.12791719704783, -118.81865925129586 32.21391111664729, -118.82033222275903 32.1911009108765, -118.93326057015588 32.27871558172218, -118.93389357015589 32.27924398172218, -119.10734869863403 32.442515590924174, -119.10743629863403 32.44260849092417, -119.36804688727433 32.786942345907136, -119.54866891864057 33.17919145601959, -119.54926721864057 33.18097675601959, -119.57406350440698 33.260416509729076, -119.57409560440698 33.26052740972907, -119.63847315496793 33.57635733422466, -119.6512803384385 33.89842718111298, -119.6512573384385 33.898988881112984, -119.63636342779567 34.074066634282474, -119.63598842779567 34.07696183428247, -119.50191309694327 34.581558010523544, -119.50189489694327 34.58160221052354, -119.35488646561173 34.84934419662282), (-117.08573331025134 31.92551486674212, -116.8500790048413 32.26876882360423, -117.61930448795941 33.752813420413574, -117.08573331025134 31.92551486674212)), POLYGON ((-118.042 33.691, -118.041 33.689, -118.03999996026384 33.68799996026385, -118.043 33.691, -118.042 33.691))): found non-noded intersection between LINESTRING ( -118.042 33.691, -118.041 33.689 ) and LINESTRING ( -118.03999996026384 33.68799996026385, -118.043 33.691 ) [ (-118.041, 33.68900000000001, NaN) ]"

**Comment by gpetit** [comment]
> Thus I think we need to make valid the RSU geometries.

Ok for me. It make sense

**Comment by ebocher** [comment]
I will check the rsu  but seems relate to the intersection not the RSU geometry

**Comment by ebocher** [comment]
Since the last PR, Orange (FR) is processed without any pb in 6 minutes ;-)
