### ISSUE TITLE
Workflow OSM - Trouble with accents when getSpatialTable

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#265]
For several cities aving accents (Rezé, Couëron, etc.) I got the following error message when trying to execute the following line:

> def epsg = datasource.getSpatialTable(inputTableName).srid

The error message is the following and arrives much later than the one which concerns the whitespace or "-":
> [INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Create the units of analysis...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing the abstract model to build the RSU
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing vegetation...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing hydrographic...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing road...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing rail...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Grouping all tables...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - RSU created...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Creating the reference spatial units
[ERROR] org.orbisgis.orbisdata.datamanager.jdbc.h2gis.H2GIS - The table '"COUËRON_PREPARED_RSU_DATA"' is not a spatial table.
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
Cannot get property 'srid' on null object
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Cannot compute the RSU.

**Comment by ebocher** [comment]
oupps good catch

**Comment by ebocher** [comment]
OSM workflow tested with Rezé, Couëron without any problem. Could you point the test that does'nt work.

**Comment by j3r3m1** [comment]
OK my bad the problem comes from the prefixName which was set the same value as the city. I did not remove accents, whitespaces and "-".
@ebocher, @spalominos : any idea how to simply remove all of them in a string ?
