### ISSUE TITLE
GEOJSON read null value

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#266]
I have applied the BDTopo workflow and the OSM one on a full batch of cities. However, impossible to load the block indicators since the column id_rsu could be null (in case the block is located outside the city boundaries). Thus the following error is displayed by H2GIS:
> DROP TABLE IF EXISTS BUILDING_INDICATORS;
CALL GEOJSONREAD('path/zone_13010_block_indicators.geojson', 'BLOCK_INDICATORS');

The file is correctly opened by DBeaver up to the first line having id_rsu = null.
Note that the file is totally opened by QGIS.

@SPalominos I do not think it is the correct location for opening this issue. Please feel free to move it to a more appropriate place.

**Comment by ebocher** [comment]
Could you please shared the geojson file ?
Thanks

**Comment by j3r3m1** [comment]
I drop the avignon blocks on the server in the '/Temp/TroubleNullValue' folder.

**Comment by ebocher** [comment]
thanks a lot

**Comment by ebocher** [comment]
FIXED
