### ISSUE TITLE
Groovy Editor

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#269]
I have uploaded my dbeaver version (3.3) and the groovy editor plug-in following the geoclimate/readme instructions. I have restarted but when I want to open a new groovy editor, I got the following error:
'Plug-in "org.orbisgis.groovyeditor" was unable to instantiate class "org.orbisgis.ui.editors.groovy.GroovyEditor".'

Any idea where could this error come from ?

**Comment by SPalominos** [comment]
Did you tried with the very last version of the `GroovyEditor` ? It has been update recently to fix this problem.

**Comment by ebocher** [comment]
Yes I m using the last one

**Comment by ebocher** [comment]
Sorry, I was thinking about this one. https://github.com/orbisgis/orbisrcp/issues/25

**Comment by j3r3m1** [comment]
I will try that soon and let you know
