### ISSUE TITLE
LCZ classification results

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#271]
We computed the full Geoclimate chain on Séné, using BD Topo data.

The results for the LCZ are sometimes strange

#### Example 1, with a RSU made of water

- `id_rsu` = 1088
- `water_fraction` = 1

in `LCZ` table
- `id_rsu` = 1088
- `lcz1` = 105 (LCZ E : Bare rock or paved)
- `lcz2` = 107
- `min_distance` = 0
- `pss` = 0,702804694646678

#### Example 2, with a RSU made of water

- `id_rsu` = 942
- `water_fraction` = 0,999999999487372

in `LCZ` table
- `id_rsu` = 942
- `lcz1` = 104 (LCZ D : Low plants)
- `lcz2` = 105 
- `min_distance` = 0.40291904921245
- `pss` = 0.702191169349332

![lcz_bug](https://user-images.githubusercontent.com/1871248/73548115-81882380-4440-11ea-99ff-20510df22e3a.png)

@ebocher @j3r3m1

**Comment by j3r3m1** [comment]
The reason why these RSU are not associated with water fraction is simple: there is no indicator in the LCZ classification which take into account the water fraction.
The strange result is that they are classified in bare rock or paved. It seems that the water fraction has not been classified as pervious surface... What is the percentage of pervious and impervious for these RSU ?

Anyway, I still plan to improve the LCZ classification:
- One of the first improvement will be to better dissociated built areas to natural areas using the building fraction as a key parameter (below 10% ==> natural)
- Then for the natural lands we will have a specific algorithm to classify as water the RSU having water fraction above a certain threshold.

**Comment by gpetit** [comment]
Ok I see. We have some other examples like this (in Rouen and Rennes) --> the rivers are always in "bare rock or paved"

Below some other indicators

#### For `1088`
- `building_area_fraction` = 0
- `all_vegetation_fraction` = 0,000125326664418792
- `aspect_ratio` = 0 
- `ground_sky_view_factor` = 1 
- `pervious_fraction` = 1
- `impervious_fraction` = 0
- `effective_terrain_roughness_length` = 0 
- `effective_terrain_roughness_class` = 1 


#### For `942`
- `building_area_fraction` = 0,000128308408421041
- `all_vegetation_fraction` = 0,00801789234340921
- `aspect_ratio` = 0,000314629588815719
- `ground_sky_view_factor` = 0,985763972927971
- `pervious_fraction` = 0,999999999487372
- `impervious_fraction` = 0,000461996896658596
- `effective_terrain_roughness_length` = 0,000405095261147331 
- `effective_terrain_roughness_class` = 2 

When we have very high values like this (e.g more than 90% of water or vegetation), maybe we should "skip" the classification process and automatically assign the water / vegetation LCZ class ?

**Comment by j3r3m1** [comment]
I am on it

**Comment by j3r3m1** [comment]
should be solved with #325. @gpetit, could you investigate if it works better for natural LCZ ?

**Comment by gpetit** [comment]
I made some tests (on `56167` and `56243`) and there is still some improvements to be done

![pblm_lcz](https://user-images.githubusercontent.com/1871248/78664587-a1224900-78d4-11ea-84f0-a2b3c22fd026.png)

It seems that :
- `water` areas are OK.
- there is an overestimation of `dense trees`

I will continue to investigate

**Comment by gpetit** [comment]
Further investigations:
-  `dense trees` (101) and `compact high-rise` (1) are overestimated
- in Plougoumelen (56167), there is only 3 resulting classes (1, 101 and 107)
- in Séné (56243), there is only 4 resulting classes (1, 101, 104 and 107 - only 4 objects with 104)

**Comment by j3r3m1** [comment]
I think all these issues are solved. @gpetit ?
