### ISSUE TITLE
Update input paramaters names

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#273]
We should align the `expand` name in the workflow and conf files :
- `expand` (replace `distance` - default value = 1000)

In parallel, in the BD Topo workflow, we have to add the  `distBuffer` parameter (default value = 500)

**Comment by ebocher** [comment]
Planed with this https://github.com/orbisgis/geoclimate/issues/200

**Comment by j3r3m1** [comment]
Replace expand by distance in the BDTopo

**Comment by ebocher** [comment]
Fixed
