### ISSUE TITLE
zindex for water, vegetation and imprevious

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#275]
Keep a zindex for all input layers.
Useful to find a vegetalized roof in OSM

**Comment by j3r3m1** [comment]
First the objective is to filter the zindex = 0 to avoid underground water or swimming pools or vegetation on roofs

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
Done https://github.com/orbisgis/geoclimate/pull/654
