### ISSUE TITLE
Cast integer value to double  for all st_buffer call

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#276]
st_buffer(the_geom, WIDTH/2) must be replaced by st_buffer(the_geom, WIDTH::double precision/2)
otherwise it returns empty geometry

**Comment by j3r3m1** [comment]
You mean we should replace it each time we use it in geoclimate ?

**Comment by ebocher** [comment]
yep because
In this case
WIDTH/2 returns 0
if WIDTH = 1

**Comment by j3r3m1** [comment]
I see, I did not see the /2 I thought that it was for each use of st_buffer but actually it is each time it is used with an interger value divided by an other

**Comment by ebocher** [comment]
yep

**Comment by ebocher** [comment]
I'm on it
