### ISSUE TITLE
Nb_Building not described

### ISSUE THREAD

**Issue by ELSW56** [orbisgis/geoclimate#292]
Several indicators described in docs/chain_documentation/indicators/rsu.md are involving another indicator named NB_Building but this one is not defined.

**Comment by gpetit** [comment]
Thanks. I will have a look

**Comment by j3r3m1** [comment]
@ELSW56 do you have a test case for the problem you met with nb_density > 0 whereas the number of building in the RSU = 0 ? Then I could investigate this area specifically.

**Comment by ELSW56** [comment]
Indeed, the test case is the one for tomorrow's presentation, concerning Vannes. 
There are several RSU with building_number_density > 0 without buildings. 
You can locate them with DBeaver using this query :
```
SELECT ri.ID_RSU, ri.THE_GEOM
FROM RSU_INDICATORS ri LEFT join BUILDING_INDICATORS bi https://guides.github.com/features/mastering-markdown/
on ri.ID_RSU = bi.ID_RSU
WHERE ri.BUILDING_NUMBER_DENSITY > 0
GROUP BY ri.ID_RSU 
HAVING count(bi.ID_BUILD)=0
```

**Comment by j3r3m1** [comment]
OK I found the bug. I made the count on the buildings without specifying a column (then the count was 1 when there was no building...).
If I specify the ID_BUILD, it works. See the corresponding sql code.
```sql
DROP TABLE IF EXISTS test;
CREATE TABLE test 
AS SELECT COALESCE(COUNT(a.ID_BUILD),0) AS NB_DENS_NUMBER_DENSITY, b.id_rsu 
FROM buildings a 
	RIGHT JOIN rsu b
	ON a.id_rsu = b.id_rsu GROUP BY b.id_rsu;
```

**Comment by j3r3m1** [comment]
See #296
