### ISSUE TITLE
DBeaver : log message apparition order

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#294]
When I execute a groovy script in DBeaver, I never know which step is under process since log messages appear in alphabetical order. Is there a possibility to add a column datetime in order to know which message is the last one ? Could be cool for the session tomorow to have that for debugging.

**Comment by gpetit** [comment]
For me the logs are well ordered

![image](https://user-images.githubusercontent.com/1871248/75334374-03c10780-5888-11ea-8203-3009fbd6de5b.png)

Clikc on `Date` to change the order (I imagine you clicked on `Message`)

**Comment by j3r3m1** [comment]
Wow, I did not display the log full size, thus did not see the date column... My bad it is OK then, good to know
