### ISSUE TITLE
RSU_SMALLEST_UNITS height class

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#301]
I apply the rsu_smallest_unit process only with vegetation and RSU and I do not get any information in the output table.
I have debugged the function and I came out with the following problem: 
https://github.com/orbisgis/geoclimate/blob/24bc45a5d2dc0f5b1b6ef185da14da9bc88df82e/geoindicators/src/main/groovy/org/orbisgis/orbisprocess/geoclimate/geoindicators/RsuIndicators.groovy#L1481
Should be height_class instead of type I suppose ?

**Comment by ebocher** [comment]
Goodddddddddddddd catch.
I will fix it

**Comment by j3r3m1** [comment]
OK work
