### ISSUE TITLE
RSU_SMALLEST_UNITS duplicates

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#302]
When applying the RSU_SMALLEST_UNITS, it does not work as expected (at least concerning the vegetation layer). For several RSU, I get a "low_vegetation density" (but similarly for the high vegetation) higher than 1.
When I investigate the input layer, I found out that I may have several low_vegetation geometries covering each other. I understand that they may have a different type and then a different use. However when applying the rsu_smallest_units, for now we only want to know whether a place is covered by low or high (or both) vegetation. Then I suppose we would need to union low vegetation that intersect each other (and same for high vegetation).
I suppose that to work, the all "low vegetation" objects should be union when intersect

**Comment by j3r3m1** [comment]
I have tried a st_union(st_accum on vegetation geometries but not sufficient (sql ask me to put the a.the_geom in the group by list...
```sql
CREATE TABLE $high_vegetation_tmp AS SELECT st_intersection(ST_FORCE2d(a.the_geom), st_union(st_accum(b.the_geom))) AS the_geom, b.id_rsu FROM 
                            $vegetationTable AS a, $rsuTable AS b WHERE a.the_geom && b.the_geom 
                            AND ST_INTERSECTS(a.the_geom, b.the_geom) AND a.height_class='high' GROUP BY b.id_rsu
```

**Comment by ebocher** [comment]
I'm on it

**Comment by j3r3m1** [comment]
Ok work

**Comment by j3r3m1** [comment]
Thanks to  #305
