### ISSUE TITLE
Workflow BD Topo - multiple id_zones

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#310]
I'm trying to process many cities in the same time.
So, in my configuration file, I wrote 
```json
"input" : {
        "folder": {"path" :"/.../bdtopo/input/44/",
            "id_zones":["44162", "44172"]}
    },
```

And I get this errors
```
!ENTRY groovy.lang.GroovyShell 1 0 2020-03-09 10:19:55.986
!MESSAGE Reading file parameters from /.../bdtopo/config_id_zone.json

!ENTRY groovy.lang.GroovyShell 1 0 2020-03-09 10:19:55.987
!MESSAGE Process BD Topo v2 on the city of Nantes

!ENTRY groovy.lang.GroovyShell 4 0 2020-03-09 10:19:56.943
!MESSAGE Cannot find any commune from the list of zones  : 44162,44172

!ENTRY groovy.lang.GroovyShell 4 0 2020-03-09 10:19:56.945
!MESSAGE The iris_ge file doesn't contains any zone identifiers

!ENTRY groovy.lang.GroovyShell 4 0 2020-03-09 10:19:56.945
!MESSAGE Cannot load the files from the folder [path:/.../bdtopo/input/44/, id_zones:[44162, 44172]]

!ENTRY groovy.lang.GroovyShell 1 0 2020-03-09 10:19:56.947
!MESSAGE null

```

If I enter only one city (`"id_zones":["44162"]`) it works well

**Comment by j3r3m1** [comment]
wgat about if you do ("id_zones":["44172"]) ? Because no problem for me for all tests I have done using several insee_codes

**Comment by ebocher** [comment]
@j3r3m1  good catch

**Comment by ebocher** [comment]
but it must work without parenthesis. I will look asap

**Comment by j3r3m1** [comment]
no need of parenthesis, I just copied the message of @gpetit and replace the insee_code =)

**Comment by gpetit** [comment]
???
As I said:
- "id_zones":["44162"] works
- "id_zones":["44162", "44172"] does not work
- I also tried "id_zones":["44162"], ["44172"] but does not work too

**Comment by gpetit** [comment]
... and yes 44172 works well alone

**Comment by ebocher** [comment]
I'm on it

**Comment by gpetit** [comment]
Great. The PR #311 resolved the problem !
So the good syntax for various zone ids is : `"id_zones":["44109", "44114", "44162", "44172"]`
