### ISSUE TITLE
Error grabbing grapes

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#317]
I have tried to launch the snapshot version of geoclimate in a groovy dbeaver console and I got the following error:
> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [download failed: net.sourceforge.f2j#arpack_combined_all;0.1!arpack_combined_all.jar]

@SPalominos @gpetit it seems it is the same error as met at the IGN (proxy error). Do you confirm ?

**Comment by gpetit** [comment]
Yep, it seems to be the same.
You have to :
- close DBeaver
- remove your `.m2` and `.groovy` folders
- restart DBeaver
- check that the Groovy console is well updated

**Comment by j3r3m1** [comment]
What do you mean by your last step ? That the .groovy is well "re-created" and "re-fed" ? I have done this process twice without success, that's why I was thinking about the proxy (note that the same script in a IntelliJ test works).

**Comment by gpetit** [comment]
I was talking about the DBeaver plugins.

IntelliJ is getting dependencies directly from Maven while DBeaver is getting dependencies from Grab

**Comment by gpetit** [comment]
And (if I'm not wrong) there is no proxy where you are currently ;-)

**Comment by j3r3m1** [comment]
The current groovy plugin is the following:
> OrbisGIS 1.0.0.4--cUrh--7E7E77EEUAMQE

No option to upgrade, it seems I am updated

**Comment by SPalominos** [comment]
You can try to do the 2 first steps 
> - close DBeaver
> - remove your `.m2` and `.groovy` folders

and run your script in the GroovyConsole comming along with your Groovy installation.
If you still have the problem, the issue might be due to your internet connection.

**Comment by j3r3m1** [comment]
Same error. I think it comes from the proxy

**Comment by SPalominos** [comment]
Yes it seems, we should find how to solve this problem manually or automatically.

**Comment by j3r3m1** [comment]
I do not have the same problem anymore since I am in another place. For information, lines to add at the begining of the script to remove the proxy:

> System.getProperties().put("proxySet", true);
System.getProperties().put("proxyHost", "proxyUrl");
System.getProperties().put("proxyPort", "proxyPort");

Note that during our last training session the proxy port was 3128.

**Comment by ebocher** [comment]
Add proxy setting in doc

**Comment by ebocher** [comment]
Done ?

**Comment by j3r3m1** [comment]
Yes. Do we add these lines somewhere in the documentation or somewhere else or we get rid of that ?

**Comment by ebocher** [comment]
Is proxy info added to the doc ?
@gpetit

**Comment by ebocher** [comment]
Doc updated https://github.com/orbisgis/geoclimate/blob/master/docs/for_users/execution_environment.md
