### ISSUE TITLE
IProcess not found in DBeaver

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#318]
I have run a basic groovy script such as the one described in the doc (https://github.com/orbisgis/geoclimate/blob/master/docs/for_users/execution_examples/run_osm.md) and I got the following error:
> file:/home/decide/.local/share/DBeaverData/workspace6/General/Groovy/Script-6.groovy: 7: unable to resolve class IProcess
 @ line 7, column 10.
   IProcess workflowBdTopo = ProcessingChain.Workflow.BDTOPO_V2()

It is the same for the H2GIS class. Strange behavior since I have deleted the .groovy, .m2, reload dbeaver (with the last version of the Plug-in) and that in the new .groovy folder the geoclimate, orbisdata and orbisprocess libraries have been downloaded...

@SPalominos any idea ?

**Comment by SPalominos** [comment]
I your `.groovy\grapes` folder do you have a folder named `org.orbisgis.orbisdata.datamanager` ?
If yes, inside this `org.orbisgis.orbisdata.datamanager` folder, a folder named `api` ?
If yes, inside this `api` folder a folder named `bundles` ?
If yes, in this `bundles` folder, a file named `api-1.0.1-SNAPSHOT.jar` ?

**Comment by j3r3m1** [comment]
yes,
yes,
yes
My script is:
``` groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate
Geoclimate.logger = logger

IProcess workflowBdTopo = ProcessingChain.Workflow.BDTOPO_V2()
def confPath = '/Path/File.json'
workflowBdTopo.execute(configurationFile: confPath)

H2GIS datasource = H2GIS.open("/home/decide/Data/Modeval/database;AUTO_SERVER=TRUE")
```

**Comment by SPalominos** [comment]
Ok, I've got it.
When you do a Grab in groovy, it just downloads and adds a dependency (and its own dependencies) to you classpath (the list of the jar which java/groovy can access). But it doesn't mean that you can use the classes from this dependency in you script. To use them, you have to import, like in your script with the `Geoclimate` class.
So when you write `IProcess workflowBdTopo = ...`, the class `IProcess` is in the classpath but not declared in your script.
You have two solution :
 - Import the class : `import org.orbisgis.orbisdata.processmanager.api.IProcess`
 - Do not type your variable `workflowBdTopo` and write instead `def workflowBdTopo = ...` (better solution.

I hope I'm clear.

**Comment by j3r3m1** [comment]
Definitely you are. Then we will have to modify that in the groovy script. In a general point of view, I suppose the best is to always use def.

**Comment by SPalominos** [comment]
Yes, Groovy has a better support of `def` than explicit typing.
