### ISSUE TITLE
createIndex and createSpatialIndex

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#320]
I though that for index creation, the createIndex was the generic way and then create a spatial index if the field is a geometry one ? However, we still use the createSpatialIndex notation, both commands are valid ?

https://github.com/orbisgis/geoclimate/blob/f73bcf791e2a66d3d0c89ae4faa37fdfffc2a9f6/geoindicators/src/main/groovy/org/orbisgis/orbisprocess/geoclimate/geoindicators/RsuIndicators.groovy#L168

**Comment by SPalominos** [comment]
The `createIndex()` methods create a standard index whereas `createSpatialIndex()` creates a spatial index, so on a geometric column, the first method creates a String index and the second a geometric index.

**Comment by j3r3m1** [comment]
OK. I am not sure I have always created a spatial index for geometric fields. Is there a reason to create a string index on a geometric column ? If not would it be possible (and useful) to have only one method called createIndex that would create a spatial index if the field is geometric ?

**Comment by SPalominos** [comment]
Yes, we should discuss it with @ebocher and @gpetit about the need of having two kind of indexes on the geometric field and maybe we just need one `createIndex()` methods for all columns.

**Comment by gpetit** [comment]
Hum, IMO creating a "simple" index on geometry make no sens. It mean that in this case, the all string value (WKT) is used for the index ? The index will be huge !

So, yes, considering we are just talking about groovy (and not SQL), merging both indexes in the `createIndex()` may be a good option

**Comment by ebocher** [comment]
Would be nice to have only one syntax createIndex()
if createIndex() is done on a geometry column then OrbisData must perform a spatial index

**Comment by SPalominos** [comment]
Ok, so I create an issue on OrbisData and I link it.

**Comment by ebocher** [comment]
Fixed in OrbisData
