### ISSUE TITLE
Different overlapping land uses

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#326]
We may have a problem when two (or more) important objects are overlapping.
In the example below, two "opposite" land cover are overlapping : vegetation and impervious area. This is a military area (Camp de Meucon), mainly covered by vegetation. But in the `SURFACE_ACTIVITE` layer (which is supposed to be impervious), this area (ID = `SURFACTI0000000306710441`) is tagged as `Administratif`.

![meucon](https://user-images.githubusercontent.com/1871248/78875520-4e6c9c80-7a4e-11ea-8b49-4a47ae12c68b.png)

**Comment by j3r3m1** [comment]
and what is inside the impervious table ?

**Comment by gpetit** [comment]
I forgot to mention, but the orange area is made of only 1 polygon, while there is many vegetation areas (in green).

**Comment by ebocher** [comment]
So you want to split the polygon according the vegetation areas ?
What about the size of the vegetation areas  ? Are they greater than the threshold value we use ?

**Comment by gpetit** [comment]
For the moment I don't have specific idea. I'm just pointing a potential problem, especially when computing the LCZ

**Comment by j3r3m1** [comment]
Again is there a zone defined as impervious in this area ?
Let's say the whole zone is impervious and high vegetation, I do not think it could lead to trouble. How you would classify this zone if you would have to do it manually ? I suppose the result according to the automatic classification is impervious in the current version ?

**Comment by gpetit** [comment]
The orange area is present in the `SURFACE_ACTIVITE` layer. So by definition it will be inserted into the `IMPERVIOUS` table.
So in this specific case, we will have many RUS where 100% are impervious and in the same time 100% are vegetation. So full impervious and full pervious in the same time ?!
I did not processed this city yet. I will do to see what is the current LCZ result

**Comment by gpetit** [comment]
Ok I have one example

## ZONE_VEGETATION
- `ID`: ZONEVEGE0000000222214806
- `NATURE`: Forêt fermée de conifères
and
- `ID`: ZONEVEGE0000000222216876
- `NATURE`: Forêt fermée de feuillus

## RSU
- `id_rsu`: 145
- `high_vegetation_fraction`: 0,9999999929550702
- `high_vegetation_water_fraction`: 0
- `high_vegetation_building_fraction`: 0
- `high_vegetation_low_vegetation_fraction`: 0
- `high_vegetation_road_fraction`: 0
- `high_vegetation_impervious_fraction`: 0
- `water_fraction`: 0
- `building_fraction`: 0
- `low_vegetation_fraction`: 0
- `road_fraction`: 0
- `impervious_fraction`: 0
- `vegetation_fraction_urb`: 0,9999999929550702
- `low_vegetation_fraction_urb`: 0
- `high_vegetation_impervious_fraction_urb`: 0
- `high_vegetation_pervious_fraction_urb`: 0,9999999929550702
- `road_fraction_urb`: 0
- `impervious_fraction_urb`: 0
- `building_fraction_lcz`: 0
- `pervious_fraction_lcz`: 0,9999999929550702
- `high_vegetation_fraction_lcz`: 0,9999999929550702
- `low_vegetation_fraction_lcz`: 0
- `impervious_fraction_lcz`: 0
- `water_fraction_lcz`: 0
- `area`: 113556,99189995848
- `avg_height_roof_area_weighted`: 0
- `std_height_roof_area_weighted`: 0
- `road_direction_distribution_h0_d0_30`: 214,58892250046776
- `road_direction_distribution_h0_d30_60`: 275,63324802999915
- `road_direction_distribution_h0_d60_90`: 22,04767561420919
- `road_direction_distribution_h0_d90_120`: 422,78711599439924
- `road_direction_distribution_h0_d120_150`: 489,7376066892863
- `road_direction_distribution_h0_d150_180`: 47,84214666245239
- `ground_linear_road_density`: 0,01296826105422182
- `non_vert_roof_area_h0_10`: NULL
...
- `vert_roof_density`: NULL
- `non_vert_roof_density`: NULL
- `free_external_facade_density`: 0
- `geom_avg_height_roof`: 0
- `building_volume_density`: 0
- `avg_volume`: NULL
- `avg_number_building_neighbor`: NULL
- `building_floor_area_density`: 0
- `avg_minimum_building_spacing`: NULL
- `building_number_density`: 0
- `projected_facade_area_distribution_h0_10_d0_30`: 0
...
- `building_total_fraction`: 0
- `aspect_ratio`: 0
- `ground_sky_view_factor`: 1
- `effective_terrain_roughness_length`: 0
- `effective_terrain_roughness_class`: 1
- `main_building_direction`: NULL
- `building_direction_inequality`: NULL
- `building_direction_uniqueness`: NULL

## LCZ

- `ID_RSU`= 145
- `LCZ1`= 101
- `LCZ2`= NULL
- `MIN_DISTANCE`= NULL
- `PSS`= NULL

So it the resulting LCZ is good.
But the question is why `impervious_fraction` is equal to 0 ? Did we already included a workaround ?

**Comment by j3r3m1** [comment]
If the layers are superimposed, the indicator 'high_vegetation_impervious_fraction' should not be 0

**Comment by ebocher** [comment]
Fixed ?

**Comment by j3r3m1** [comment]
should be fixed with your last PR #367.
@gpetit or myself may verify that once we can run geoclimate using groovy

**Comment by ebocher** [comment]
Fixed ?
