### ISSUE TITLE
LCZ - same value for 1 and 2

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#329]
I found a case where LCZ1 and LCZ2 are the same. 
This RSU is classed as `bare rock or paved` but actually it's a forest (so it should be 101 or 102 - I will add this case in the LCZ test file)

Below are some information

Point (inside the RSU) : 258683,14 / 6745288,50

## LCZ table
- ID_ZONE : 56167 (Plougoumelen)
- id_rsu: 734
- lcz1: 105
- lcz2: 105
- min_distance: 0
- pss: 0,7027798996088424

## RSU indicators

- id_rsu: 734
- high_vegetation_fraction: 0,9998622190343457
- high_vegetation_water_fraction: 0,0001377770111214033917
- high_vegetation_building_fraction: 0
- high_vegetation_low_vegetation_fraction: 0
- high_vegetation_road_fraction: 0
- high_vegetation_impervious_fraction: 0
- water_fraction: 0
- building_fraction: 0
- low_vegetation_fraction: 0
- road_fraction: 0
- impervious_fraction: 0
- vegetation_fraction_urb: 0,9999999960454671
- low_vegetation_fraction_urb: 0
- high_vegetation_impervious_fraction_urb: 0
- high_vegetation_pervious_fraction_urb: 0,9999999960454671
- road_fraction_urb: 0
- impervious_fraction_urb: 0
- building_fraction_lcz: 0
- pervious_fraction_lcz: 0,9999999960454671
- high_vegetation_fraction_lcz: 0,9999999960454671
- low_vegetation_fraction_lcz: 0
- impervious_fraction_lcz: 0
- water_fraction_lcz: 0,0001377770111214033917
- area: 455174,0485000111
- avg_height_roof_area_weighted: 0
- std_height_roof_area_weighted: 0
- road_direction_distribution_h0_d0_30: 258,80924652702635
- road_direction_distribution_h0_d30_60: 474,5272353100638
- road_direction_distribution_h0_d60_90: 75,46982067547738
- road_direction_distribution_h0_d90_120: 3,7999999999883585
- road_direction_distribution_h0_d120_150: 0
- road_direction_distribution_h0_d150_180: 61,35827561081559
- ground_linear_road_density: 0,001920066798631095721
- non_vert_roof_area_h0_10: NULL
...
- vert_roof_area_h0_10: NULL
...
- vert_roof_density: NULL
- non_vert_roof_density: NULL
- free_external_facade_density: 0
- geom_avg_height_roof: 0
- building_volume_density: 0
- avg_volume: NULL
- avg_number_building_neighbor: NULL
- building_floor_area_density: 0
- avg_minimum_building_spacing: NULL
- building_number_density: 0
- projected_facade_area_distribution_h0_10_d0_30: 0
...
- building_total_fraction: 0
- aspect_ratio: 0
- ground_sky_view_factor: 0,9981790939112796
- effective_terrain_roughness_length: 0
- effective_terrain_roughness_class: 1
- main_building_direction: NULL
- building_direction_inequality: NULL
- building_direction_uniqueness: NULL

**Comment by j3r3m1** [comment]
@gpetit, do you still have this behavior with the new versions ?

**Comment by ebocher** [comment]
Fixed ?

**Comment by j3r3m1** [comment]
Let's say yes
