### ISSUE TITLE
Update doc

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#332]
Due the last modules refactoring https://github.com/orbisgis/geoclimate/pull/330, the doc must be updated

**Comment by gpetit** [comment]
Ok, so if I understand well, to launch the chain,  we used to have

```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-RC1')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate
Geoclimate.logger = logger

def process = Geoclimate.Workflow.BDTOPO_V2()
process.execute(configurationFile:'/home/geoclimate/bdtopo/config_all_zones.json')
```

and now, we have
```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-RC1')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate
Geoclimate.logger = logger

def process = Geoclimate.BDTOPO_V2.workflow()
process.execute(configurationFile:'/home/geoclimate/bdtopo/config_all_zones.json')
```

and same for OSM

Before

```groovy
...
def process = Geoclimate.Workflow.OSM()
...
```
After

```groovy
...
def process = Geoclimate.OSM.workflow()
...
```

Right ?

@j3r3m1

**Comment by ebocher** [comment]
Yes but without parenthesis 
```
def process = Geoclimate.OSM.workflow
```
so you can do

```
Geoclimate.OSM.workflow.execute(configurationFile:'/home/geoclimate/bdtopo/config_all_zones.json')
```

What about if we proposed this signature for the workflow ?
Even simpler for users, isn't it?

```
Geoclimate.OSM.workflow.execute('/home/geoclimate/bdtopo/config_all_zones.json')
```

By the way test the syntax in groovy or dbeaver console. It works for me but in case of ;-)

**Comment by gpetit** [comment]
Nice. Ok I will test and adapt the doc in order to have the simplest signature for users

**Comment by gpetit** [comment]
I'm on it

**Comment by gpetit** [comment]
The PR #335 partially answer this issue since only the new addresses of the configuration file have been updated.
The way the workflow are called (`Geoclimate.BDTOPO_V2.workflow` and `Geoclimate.OSM.workflow` instead of `Geoclimate.Workflow.BDTOPO_V2()` and `Geoclimate.Workflow.OSM()` ) will be updated once the RC2 will be released

**Comment by ebocher** [comment]
Fixed ?
