### ISSUE TITLE
LCZ classif : null values for indicators (BDTopo case)

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#334]
OK several problems of LCZ misclassification come from the fact that indicators may be null.
Several examples and propositions:
1. Aspect ratio (building height / building spacing) is null when no building, thus the LCZ algo classes it as urban since it does not have an aspect ratio < 0.1: 2 solutions:
- set its value to 0 (but it does not really make sense since there is no building...)
- modify the LCZ algo to consider null aspect ratio as rural type

2. For parking lot having no building, we do not have any surface fraction (all are set to null). In this case, how to set its LCZ class ? Should be set to impervious ? To low vegetation ? Or to impervious or low vegetation depending on the value of the surrounding LCZ (but then how to get this information...) ?

**Comment by gpetit** [comment]
1. I vote for "modify the LCZ algo"
2. It's a real problem since in the BD Topo there is many empty areas. I don't know if it's a good approach and if it's "allowed" but why not creating an additional class called `not_classed` (or `unclassifiable` or something else) in which all the objects we don't have enough information to classify are stored ? Maybe it's better to have no LCZ instead of a wrong / weird LCZ ?

**Comment by j3r3m1** [comment]
+1 for the "not_classed" LCZ type (code 999 ?). It could be a temporary solution waiting for a more accurate version of BDTopo and it makes it more generic since for other sources of data we may have some more informations.
Moreover people that wants to make their own rule for these LCZ according to their surrounding for example may make the modification easily

**Comment by ebocher** [comment]
1. modify the LCZ algo
2. I  I would prefer the term  "unknown"

**Comment by gpetit** [comment]
In the LCZ .sld style we have `undefined`

**Comment by ebocher** [comment]
undefined +1

**Comment by j3r3m1** [comment]
OK for modifying the LCZ algo and "undefined" (code "999"). @gpetit could you please update your expectedLcz file according to this ?

**Comment by gpetit** [comment]
Ok, I will update the .geojson. So when there is no input layer beneath an RSU, it means that there is not enough information to class --> expected : `999`

**Comment by j3r3m1** [comment]
yep !

**Comment by j3r3m1** [comment]
ok done
