### ISSUE TITLE
Add baresoil information

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#339]
Climatologists may be interested to have a more diversified soil typology (baresoil, sand, rock). Maybe we could add this information (as a new table ?) in the future versions of Geoclimate

**Comment by ebocher** [comment]
Yes sure

**Comment by ebocher** [comment]
We must investigate the natural tag in OSM
https://wiki.openstreetmap.org/wiki/Key:natural

**Comment by j3r3m1** [comment]
Keep only one issue opened, issues are now "linked"
