### ISSUE TITLE
Here is the problem. And strange thing, I display the ID of each building in order to know where happen the problem. It happens right after id 2231... which is the end of the file...

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#342]
Here is the problem. And strange thing, I display the ID of each building in order to know where happen the problem. It happens right after id 2231... which is the end of the file...

_Originally posted by @j3r3m1 in https://github.com/orbisgis/geoclimate/pull/336_

**Comment by j3r3m1** [comment]
Tu summarize, I get the following error:
> java.lang.NullPointerException: Cannot get property 'HEIGHT_WALL' on null object

When executing the following command:
>assertNotEquals('', row.HEIGHT_WALL)

And I also get the following error:
> java.lang.NullPointerException: Cannot get property 'WIDTH' on null object

When executing this command:
> assertEquals('DOUBLE', table.columnType('WIDTH'))

Maybe these are connected each other or/and connected to issue #341. We will see when the first issue will be fixed.

**Comment by j3r3m1** [comment]
it seems the last h2gis update did not solve the problem. I still have the same problem on my machine. And a similar problem appears on Jenkins (however less verbose)

**Comment by ebocher** [comment]
Fixed ?

**Comment by j3r3m1** [comment]
yes of course my bad
