### ISSUE TITLE
Update BDTopov2Tests

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#345]
We have modified the input data used for the BDTopo, thus the specific tests (on specific buildings or river, or etc.) should be updated with the object of the new territory.

**Comment by j3r3m1** [comment]
Most of these commented tests are in the input_data_formatting but one is also in the BDTopoGISLayer

**Comment by ebocher** [comment]
Remove all             System.properties.setProperty("data.bd.topo", "true") in bdtopo tests because we use now a resource folder, thanks to ign

**Comment by j3r3m1** [comment]
done in PR #348
