### ISSUE TITLE
Aspect ratio null value

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#348]
The aspect ratio should be null only if the building fraction = 1. Else if the building fraction is = 0, it should be 0. Currently, we have too many building_fractions that are null instead of zero, leading to aspect ratio = null...
We need to modify that, all surface fractions may have null value when no layer inside a RSU

**Comment by gpetit** [comment]
+1000

**Comment by j3r3m1** [comment]
Strange, it seems that the problem is dataset dependent. The unitTest of surface fraction has been fixed in the last PR. Then the result should be 0 by default. However, it seems that there is an unpredictible behavior using the smallestGeometry IProcess. I will investigate this point...

**Comment by j3r3m1** [comment]
OK solved in PR #349
