### ISSUE TITLE
OSM workflow failed at Montceaux-lès-Provins

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#351]
Intersection issue when creating the smallest geometries for surface fraction calculation (for Montceaux-lès-Provins - Île-De-France).
The error message is the following:
> [INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Generating minimum polygon areas
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
org.h2.jdbc.JdbcSQLNonTransientException: Exception lors de l'appel de la fonction définie par l'utilisateur: "union(MULTILINESTRING ((533398.787 5393281.492, 533398.82 5393275.978), (533398.82 5393275.978, 533368.444 5393275.197), (533368.444 5393275.197, 533295.018 5393260.421), (533295.018 5393260.421, 533253.872 5393260.177), (533253.872 5393260.177, 532899.629 5393305.09), (532899.629 5393305.09, 532882.754 5393394.221), (532882.754 5393394.221, 532879.759 5393405.465), (532879.759 5393405.465, 532879.758 5393405.467), (532879.758 5393405.467, 532884.984 5393390.51), (532884.984 5393390.51, 532892.596 5393368.722), (532892.596 5393368.722, 532965.401 5393351.508), (532965.401 5393351.508, 532994.707 5393470.202, 533245.207 5393417.188, 533232.797 5393429.598), (533232.797 5393429.598, 533232.798 5393429.597), (533232.798 5393429.597, 533378.126 5393303.023), (533378.126 5393303.023, 533398.787 5393281.492), (532879.759 5393405.465, 532884.984 5393390.51), (532884.984 5393390.51, 532885.38 5393389.376, 532892.596 5393368.722), (532892.596 5393368.722, 532939.577 5393357.614, 532965.401 5393351.508), (532965.401 5393351.508, 532975.059 5393390.623, 532994.707 5393470.202, 533245.207 5393417.188, 533243.073 5393419.322), (533243.073 5393419.322, 533232.798 5393429.597), (533232.798 5393429.597, 533378.126 5393303.023), (533378.126 5393303.023, 533398.787 5393281.492), (533398.787 5393281.492, 533398.82 5393275.978), (533398.82 5393275.978, 533368.444 5393275.197), (533368.444 5393275.197, 533295.018 5393260.421), (533295.018 5393260.421, 533253.872 5393260.177), (533253.872 5393260.177, 532899.629 5393305.09), (532899.629 5393305.09, 532882.754 5393394.221), (532882.754 5393394.221, 532879.759 5393405.465), (532884.984 5393390.51, 532900.415 5393309.001, 532900.473 5393308.986, 532900.652 5393308.957, 532900.851 5393308.883, 532901.055 5393308.827, 532901.217 5393308.746, 532901.387 5393308.683, 532901.567 5393308.571, 532901.757 5393308.477, 532901.9 5393308.366, 532902.054 5393308.271, 532902.209 5393308.127, 532902.377 5393307.997, 532902.495 5393307.86, 532902.628 5393307.737, 532902.752 5393307.565, 532902.891 5393307.405, 532902.981 5393307.248, 532903.087 5393307.101, 532903.175 5393306.908, 532903.28 5393306.724, 532903.558 5393306.103, 533253.962 5393261.678, 533294.864 5393261.92, 533368.149 5393276.668, 533368.406 5393276.697, 533397.811 5393277.453, 533397.79 5393281.087, 533377.436 5393302.299, 533243.073 5393419.322), (533243.073 5393419.322, 533232.797 5393429.598), (533232.797 5393429.598, 533232.798 5393429.597), (533232.798 5393429.597, 533378.126 5393303.023), (533378.126 5393303.023, 533398.787 5393281.492), (533398.787 5393281.492, 533398.82 5393275.978), (533398.82 5393275.978, 533368.444 5393275.197), (533368.444 5393275.197, 533295.018 5393260.421), (533295.018 5393260.421, 533253.872 5393260.177), (533253.872 5393260.177, 532899.629 5393305.09), (532899.629 5393305.09, 532882.754 5393394.221), (532882.754 5393394.221, 532879.759 5393405.465), (532879.759 5393405.465, 532879.758 5393405.467), (532879.758 5393405.467, 532884.984 5393390.51))): found non-noded intersection between LINESTRING ( 533243.0730000037 5393419.321999996, 533232.7980000017 5393429.596999998 ) and LINESTRING ( 533245.207 5393417.188, 533243.073 5393419.322 ) [ (533243.0730000003, 5393419.322, NaN) ]"
Exception calling user-defined function: "union(MULTILINESTRING ((533398.787 5393281.492, 533398.82 5393275.978), (533398.82 5393275.978, 533368.444 5393275.197), (533368.444 5393275.197, 533295.018 5393260.421), (533295.018 5393260.421, 533253.872 5393260.177), (533253.872 5393260.177, 532899.629 5393305.09), (532899.629 5393305.09, 532882.754 5393394.221), (532882.754 5393394.221, 532879.759 5393405.465), (532879.759 5393405.465, 532879.758 5393405.467), (532879.758 5393405.467, 532884.984 5393390.51), (532884.984 5393390.51, 532892.596 5393368.722), (532892.596 5393368.722, 532965.401 5393351.508), (532965.401 5393351.508, 532994.707 5393470.202, 533245.207 5393417.188, 533232.797 5393429.598), (533232.797 5393429.598, 533232.798 5393429.597), (533232.798 5393429.597, 533378.126 5393303.023), (533378.126 5393303.023, 533398.787 5393281.492), (532879.759 5393405.465, 532884.984 5393390.51), (532884.984 5393390.51, 532885.38 5393389.376, 532892.596 5393368.722), (532892.596 5393368.722, 532939.577 5393357.614, 532965.401 5393351.508), (532965.401 5393351.508, 532975.059 5393390.623, 532994.707 5393470.202, 533245.207 5393417.188, 533243.073 5393419.322), (533243.073 5393419.322, 533232.798 5393429.597), (533232.798 5393429.597, 533378.126 5393303.023), (533378.126 5393303.023, 533398.787 5393281.492), (533398.787 5393281.492, 533398.82 5393275.978), (533398.82 5393275.978, 533368.444 5393275.197), (533368.444 5393275.197, 533295.018 5393260.421), (533295.018 5393260.421, 533253.872 5393260.177), (533253.872 5393260.177, 532899.629 5393305.09), (532899.629 5393305.09, 532882.754 5393394.221), (532882.754 5393394.221, 532879.759 5393405.465), (532884.984 5393390.51, 532900.415 5393309.001, 532900.473 5393308.986, 532900.652 5393308.957, 532900.851 5393308.883, 532901.055 5393308.827, 532901.217 5393308.746, 532901.387 5393308.683, 532901.567 5393308.571, 532901.757 5393308.477, 532901.9 5393308.366, 532902.054 5393308.271, 532902.209 5393308.127, 532902.377 5393307.997, 532902.495 5393307.86, 532902.628 5393307.737, 532902.752 5393307.565, 532902.891 5393307.405, 532902.981 5393307.248, 532903.087 5393307.101, 532903.175 5393306.908, 532903.28 5393306.724, 532903.558 5393306.103, 533253.962 5393261.678, 533294.864 5393261.92, 533368.149 5393276.668, 533368.406 5393276.697, 533397.811 5393277.453, 533397.79 5393281.087, 533377.436 5393302.299, 533243.073 5393419.322), (533243.073 5393419.322, 533232.797 5393429.598), (533232.797 5393429.598, 533232.798 5393429.597), (533232.798 5393429.597, 533378.126 5393303.023), (533378.126 5393303.023, 533398.787 5393281.492), (533398.787 5393281.492, 533398.82 5393275.978), (533398.82 5393275.978, 533368.444 5393275.197), (533368.444 5393275.197, 533295.018 5393260.421), (533295.018 5393260.421, 533253.872 5393260.177), (533253.872 5393260.177, 532899.629 5393305.09), (532899.629 5393305.09, 532882.754 5393394.221), (532882.754 5393394.221, 532879.759 5393405.465), (532879.759 5393405.465, 532879.758 5393405.467), (532879.758 5393405.467, 532884.984 5393390.51))): found non-noded intersection between LINESTRING ( 533243.0730000037 5393419.321999996, 533232.7980000017 5393429.596999998 ) and LINESTRING ( 533245.207 5393417.188, 533243.073 5393419.322 ) [ (533243.0730000003, 5393419.322, NaN) ]"; SQL statement:
(select st_polygonize(st_union(
                    st_precisionreducer(st_node(st_accum(st_force2d(a.the_geom))), 3))) as the_geom, id_rsu from tmp_tables_zindex0_b154b0dd_daa8_41ef_bcfa_ef4e6e88464d as a group by id_rsu) [90105-200]

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
Fixed

**Comment by j3r3m1** [comment]
ok well done
