### ISSUE TITLE
documentation links not valid

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#360]
For information, it seems several links in the documentation are not valid anymore (maybe disapeared due to change in the organization of the folder).
@gpetit I have found this one:
https://github.com/orbisgis/geoclimate/blob/master/docs/chain_documentation/workflow/input_data/INPUT_DATA_MODEL.md#-building-use-and-type

@ebocher @SPalominos Is there a way to make tests to verify the validity of a link in the future (if the test is wrong our new PR does not work) ?

**Comment by SPalominos** [comment]
As the master branch contains the SNAPSHOT version of geoclimate, the files can change at any moment, so the best is tu add a git tag on the RC1 version and to use the this tag to link files.
I'm on it.

**Comment by ebocher** [comment]
Fixed ?

**Comment by j3r3m1** [comment]
Fixed by @SPalominos but for sure we will have to update the documentation soon
