### ISSUE TITLE
Workflow BD Topo - DB to DB - specify a schema

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#364]
Using the DB to DB configuration file, I want to point a specific output schema (by default it's the `public` one).
So instead of 
```groovy
"output" :{
        "database": {
            "user": "gwendall",
            "password": "portug@l",
            "url": "jdbc:postgresql://149.202.221.161:5432/paendora",
            "tables": {"building_indicators":"building_indicators_2154_test_gwen",
                "block_indicators":"block_indicators_2154_test_gwen",
                "rsu_indicators":"rsu_indicators_2154_test_gwen",
                "rsu_lcz":"rsu_lcz_2154_test_gwen",
                "zones":"zones_2154_test_gwen"}
        }
    },
``` 

I add the `labsticc` schema

```groovy
"output" :{
        "database": {
            "user": "gwendall",
            "password": "portug@l",
            "url": "jdbc:postgresql://149.202.221.161:5432/paendora",
            "tables": {"building_indicators":"labsticc.building_indicators_2154_test_gwen",
                "block_indicators":"labsticc.block_indicators_2154_test_gwen",
                "rsu_indicators":"labsticc.rsu_indicators_2154_test_gwen",
                "rsu_lcz":"labsticc.rsu_lcz_2154_test_gwen",
                "zones":"labsticc.zones_2154_test_gwen"}
        }
    },
``` 

But in this case, the process runs in 1s and I obtain this log message

```
!ENTRY groovy.lang.GroovyShell 1 0 2020-06-12 10:48:24.242
!MESSAGE null

!ENTRY org.orbisgis.ui.editors.groovy.GroovyJob 1 0 2020-06-12 10:48:24.245
!MESSAGE Groovy script successfully executed.
```

and of course, no results.

I should miss something in the `json` syntax ! How to point a specific output schema ?

**Comment by ebocher** [comment]
I'm on it. Seems due to OrbisDATA that is not able to parse catalog.schema.name

**Comment by gpetit** [comment]
When creating the index, we are using the table location for the name. But when a schema is specified, we have `schema.table` in the name so it returns an error since the . is not allowed

ex:
```sql
CREATE INDEX IF NOT EXISTS idx_labsticc.block_indicators_2154_id_zone
```
as to be change to something like this
```sql
CREATE INDEX IF NOT EXISTS idx_labsticc_block_indicators_2154_id_zone
```

**Comment by ebocher** [comment]
There is a fix under the pipe here https://github.com/ebocher/geoclimate-1/tree/geoclimate_postgis
but it's a bit more complicated

**Comment by ebocher** [comment]
In bdtopo script, must be
CREATE INDEX IF NOT EXISTS idx_${output_block_indicators.replaceAll(".","_")}_id_zone ON $output_block_indicators (ID_ZONE)
I'm on it

**Comment by ebocher** [comment]
Fixed please test

**Comment by gpetit** [comment]
Yep. I'm just waiting the validation of #363 to test in real conditions (but I already made a test on labsticc schema and I get one table (due to #363) so sounds good ;-)

**Comment by gpetit** [comment]
Works well. Thx
