### ISSUE TITLE
Road's width

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#379]
Interesting observation from colleagues: the road in OSM never overlay buildings or water surfaces. Any idea of the algorithm used ?
**In the future**, could be interesting to keep a default width depending on type (as we are currently doing) which could be decreased to the minimum distance to obstacles such as water or building.

**Comment by ebocher** [comment]
Doesn't understand the question.
There is no algorithm but humans that edit data with topological rules.
