### ISSUE TITLE
SRID BDTopo outputs

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#381]
It seems that all layers coming from the BDTopo worflow are saved without any SRID while they have one in the OSM workflow. Two potential reasons for that:
- there is no SRID when loading the raw data,
- the srid exists on the loaded raw data but it is lost after the first SQL queries.

**Comment by j3r3m1** [comment]
Second trouble with the SRID. When I launch the BDTopo Workflow, I now get the following error message:
> [INFO] org.orbisgis.orbisdata.processmanager.process.GroovyProcessFactory - Loading in the H2GIS database IRIS_GE
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
groovy.lang.MissingPropertyException: No such property: srid for class: org.locationtech.jts.geom.Polygon
Possible solutions: SRID, valid, area

@gpetit do you get the same error if you try it with the last geoclimate version ?

**Comment by ebocher** [comment]
I have some units tests in OSM workflow to test if the output SRID are correct.
This kind of test must be added to BDTopo Workflow.

About 

```java
https://github.com/orbisgis/geoclimate/pull/376/files#diff-53aa9a26a59cb5007e7239e3452a7fa8R617
```
Seems there is a fix here : 
https://github.com/orbisgis/geoclimate/pull/376/files#diff-53aa9a26a59cb5007e7239e3452a7fa8R617

Don't known if this change has been tested ?

**Comment by gpetit** [comment]
I just made a test with local shapefiles (having the following .prj - 2154)

```
PROJCS["RGF93_Lambert_93",GEOGCS["GCS_RGF_1993",DATUM["D_RGF_1993",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",700000.0],PARAMETER["False_Northing",6600000.0],PARAMETER["Central_Meridian",3.0],PARAMETER["Standard_Parallel_1",44.0],PARAMETER["Standard_Parallel_2",49.0],PARAMETER["Latitude_Of_Origin",46.5],UNIT["Meter",1.0]]
```
and it works. But the resulting .geojson files are in 4326

It seems to me it used to work before. Is there anything we've done lately that might explain this regression?

**Comment by j3r3m1** [comment]
> Seems there is a fix here :
> https://github.com/orbisgis/geoclimate/pull/376/files#diff-53aa9a26a59cb5007e7239e3452a7fa8R617
> 
> Don't known if this change has been tested ?

@SPalominos any idea ?

**Comment by gpetit** [comment]
>and it works. But the resulting .geojson files are in 4326

In fact there is no srid in the geojson. So by default, QGIS open it as 4326

**Comment by ebocher** [comment]
There is no SRID in the header of geojson ?

**Comment by gpetit** [comment]
>There is no SRID in the header of geojson ?
No

After a call with @j3r3m1 we have the point (i guess).
I made the test with local shapefiles from IGN ... and we not that their PRJ is wrong. So all the input shapefiles have a "null" PRJ. That's why there is no srid in the output geojson.

Our chain is good. If no (or not recognized) srid in the input, then no srid in the output.

The problem of @j3r3m1 is something else

**Comment by ebocher** [comment]
Good catch

**Comment by j3r3m1** [comment]
OK no trouble anymore with the 'SRID', my geoclimate version was not updated...

**Comment by ebocher** [comment]
Note that  the bdtopo test data must be updated to set  valid OGC prj files.
See https://github.com/orbisgis/geoclimate/tree/master/bdtopo_v2/src/test/resources/org/orbisgis/orbisprocess/geoclimate/bdtopo_v2/sample_12174

**Comment by j3r3m1** [comment]
And we may add a test at the end of PrepareData (if not exists...) to verify that the correct SRID is set to the input of geoindicators ?

**Comment by ebocher** [comment]
Fixed ?

**Comment by ebocher** [comment]
Fixed ?

**Comment by ebocher** [comment]
Fixed and unit test added
