### ISSUE TITLE
Abstract model level from type

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#384]
When the height values are missing we use a map that set a level value for a specific type.
e.g :    "building": 1,        "house": 1,        "detached": 1,        "residential": 1,
        "apartments": 1,        "bungalow": 0,        "historic": 0,        "monument": 0

If I'm not wrong when the level is equal to zero the height will be set to 3 and when the level is 1 the height will be 1*3+3

Imagine now if we have a building under construction or a ruin what about the height ?

Would it be interesting to set 0 for 0 and 1 level for a height = 3 ?

@gpetit @j3r3m1 @ELSW56

**Comment by gpetit** [comment]
Hum ...
- if it's a ruin do we have to keep it ?
- if under construction, we have better to consider it as finished or not existing. This mid-situation make no sense for me (in a db point of view)

>Would it be interesting to set 0 for 0 and 1 level for a height = 3 ?

Not clear for me. You mean in every case or only for ruin and under construction ?
If we have a building, we consider that the height is at least 3m high. If no height ... it's not a building

**Comment by ebocher** [comment]
> Hum ...
> 
>     * if it's a ruin do we have to keep it ?
> 
>     * if under construction, we have better to consider it as finished or not existing. This mid-situation make no sense for me (in a db point of view)

@j3r3m1 
> 
> 
> > Would it be interesting to set 0 for 0 and 1 level for a height = 3 ?
> 
> Not clear for me. You mean in every case or only for ruin and under construction ?
> If we have a building, we consider that the height is at least 3m high. If no height ... it's not a building

I mean for all cases. Do we need to put the building without height in the impervious areas ?
