### ISSUE TITLE
BD Topo input data

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#389]
I have found the "piste_aerodrome" table in the BDTOPO data. It is in the "building" folder but I wonder if it could be interesting for feeding the impervious layer. @gpetit you know better than me these data, could it be interesting to add it or useless ?

**Comment by ebocher** [comment]
@j3r3m1 it'd be nice to add it to the impervious layer.

**Comment by j3r3m1** [comment]
@gpetit I did not check this point but did you change anything ?
