### ISSUE TITLE
Workflow BD Topo - Missing db references in conf file

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#395]
I may be wrong, but I think we are missing the db references here : 
https://github.com/orbisgis/geoclimate/blob/ae86f1b674d56dce4406ef477d9e68e546e3250d/bdtopo_v2/src/test/resources/org/orbisgis/orbisprocess/geoclimate/bdtopo_v2/config/bdtopo_workflow_folderinput_folderoutput.json#L3

We should have 

```json
    "geoclimatedb" : {
        "path" : "/tmp/.../geoclimate_db;AUTO_SERVER=TRUE",
        "delete" :true
    },
```
No ?

**Comment by ebocher** [comment]
The geoclimatedb parameters is optional. If the user doesn't set any parameters, a database will created in its tmpdir folder. The database will be called bdtopo_v2
