### ISSUE TITLE
BD Topo Workflow - Wrong results when adding a new zone

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#398]
I'm facing a really strange problem. I realized that when you add new zones to be processed, some indicators have null values when they should be filled in.

Here is an example:

- I'm working in db to db mode, from and to our server.
- I'm exectuting the following script in the groovyConsole
```
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT', classifier='jar-with-dependencies', transitive=false)

import org.orbisgis.orbisprocess.geoclimate.Geoclimate

def process = Geoclimate.BDTOPO_V2.workflow
process.execute(configurationFile:'/home/gpetit/geoclimate/bdtopo/config_bd_to_bd.json')
```

I'm playing with two cities : Le Bono (56262) and Plougoumelen (56167).

I have no existing tables in the output table.
I'm starting the process with 56262. Everything is ok.
Then, I disconnect the db and quit the groovyConsole. The local working db has been removed.
No I'm starting again, but with 56167. So the new data are inserted into the existing tables in the output db.

Now, I'm counting the number of RSU per zones and also when the column `building_fraction` (`bf` is the following table) is = 0 or null. And I get this

|       | RSU nb | where `bf` is null | where `bf` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56262 |   575  |         0        |      445     |
| 56167 |   747  |        641       |       0      |

Hummm a bit strange for 56167 ... but why not.

Now, I remove all my resulting tables in the output db and I replay the same scenario but in the other order. So first 56167 and then 56262. And I count again ... and I get 

|       | RSU nb | where `bf` is null | where `bf` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56262 |   575  |         445        |      0     |
| 56167 |   747  |        0       |       641      |

Now the problem is on 56262.

I made the same approach with 4 cities and in all cases, only the first city has coherent results.
I focused on `building_fraction` but many other indicators are concerned (especially those regarding fractions)

Any idea @ebocher @SPalominos @j3r3m1

**Comment by gpetit** [comment]
Still investigating ...

I have the same kind of problem on the `block_indicators` table.
I made a count on the `net_compactness` column (`nc` in the table below)


#### Run 1 : 56262 and then 56167

|       | Block nb | where `nc` is null | where `nc` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56262 | 1457 | 0 | 1294 |
| 56167 | 1324 | 1189 | 0 |

#### Run 2 : 56167 and then 56262

|       | Block nb | where `nc` is null | where `nc` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56262 | 1457 | 1294 | 0 |
| 56167 | 1324 | 0 | 1189 |

Once again, the first zone to be computed seems ok. But the second one has weird (null) results

In parallel, I also checked the results between the two same zone computed two times and they seems the same. Ouf !

**Comment by gpetit** [comment]
Some updates.
I made a new test on two new cities: Allaire (56001) and Ambon (56002).
Instead of processing cities one by one, I executed them in the same process. 
Here are the results:

#### Run 1 : "56001", "56002"

|       | Block nb | where `nc` is null | where `nc` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56001 | 2590 | 0 | 2225 |
| 56002 | 1487 | 1199 | 0 |

|       | RSU nb | where `bf` is null | where `bf` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56001 | 1311 | 0 | 1061 |
| 56002 | 475 | 330 | 0 |


#### Run 2 : "56002", "56001"

|       | Block nb | where `nc` is null | where `nc` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56001 | 2590 | 2225 | 0 |
| 56002 | 1487 | 0 | 1199 |

|       | RSU nb | where `bf` is null | where `bf` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56001 | 1311 | 1061 | 0 |
| 56002 | 475 | 0 | 330 |

So again, it seems the order of treatment is important. Whether the treatments are done at one time or in several times, in both cases, it is the first city processed that has good results. Subsequent ones have errors.

**Comment by gpetit** [comment]
I made new tests to try to figure out what the problem is.
So instead of playing in `db to db` mode, I switched to `folder to folder` mode.
I executed `56167` and `56262` in the same run and I get these results

|       | RSU nb | where `bf` is null | where `bf` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56167 |   747  |        0       |       641      |
| 56262 |   575  |         0        |      445     |

|       | Block nb | where `nc` is null | where `nc` = 0 |
|:-----:|:------:|:----------------:|:------------:|
| 56167 |   1324  |        0       |       1189      |
| 56262 |   1457  |         0        |      1294     |

So we clearly see that results are good and that the problem come from the `db to db` mode, probably when inserting the second zone into the output table.

**Comment by gpetit** [comment]
I don't know where it's placed in the code (I will try to find), but my idea is that in the "insertion" part of the code, **when we have a value = 0 the script is feeding the existing table with null value**.

**Comment by j3r3m1** [comment]
What an investigation Sherdall Holtit ! Nice job.

**Comment by ebocher** [comment]
Insert doesn't convert the value from 0 to null.
I will check

**Comment by gpetit** [comment]
> Insert doesn't convert the value from 0 to null.

Yes. I don't know if "insert" is the good term ... but since it works when we consider the zones independently, I deduced that the problem came when we want to add a new zone on a table where there is already a first zone. And the problem seems to exist only when "correct" values are = 0.

> I will check

Grazie mille.

**Comment by ebocher** [comment]
Tested with the last version works well.
I'm using this command
```java
java -jar Geoclimate.jar -w bdtopo_v2.2 -f ~/applications/geoclimate/bdtopo_workflow_dbinput_dboutput_erwan.json
```
