### ISSUE TITLE
Error message wrong when configFile does not exist

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#402]
When the workflow does not find the configuration file, the following error message is displayed:
> [ERROR] org.orbisgis.orbisdata.processmanager.process.GroovyProcessFactory - Invalid file parameters

All my parameters were valid but the path of my configuration file was wrong. Then it could be much more consistent to display an error message such as:
"Configuration file not found"

**Comment by ELSW56** [comment]
See PR #403
