### ISSUE TITLE
SRID parameter

### ISSUE THREAD

**Issue by ernlt** [orbisgis/geoclimate#412]
When editing **srid** parameter in the configuration file to run the OSM workflow (WorkflowOSM.groovy), I get an other string value of srid (epsg) into the geojson files in output. 
In my case: srid 32662 to epsg 32630

Configuration file:
![Capture d’écran du 2020-09-15 09-59-38](https://user-images.githubusercontent.com/68550685/93182871-8339f980-f73a-11ea-8e7a-74eb8b2c88e4.png)

Geojson output file:
![Capture d’écran du 2020-09-15 10-00-28](https://user-images.githubusercontent.com/68550685/93182875-83d29000-f73a-11ea-9c20-8393777d2bb7.png)

**Comment by ebocher** [comment]
Thanks a lot. We are on it.

**Comment by ebocher** [comment]
You must put the srid parameter inside the output array

```json
"output" :[
                        "folder" : "/tmp/ouputs/",
                        "srid":"4326"]
```
