### ISSUE TITLE
BD Topo failed for insee code 31160 (Daux)

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#414]
This commune fails when executing the identification of the minimum geometry for the surface fraction calculation. Here is the error message:
> [INFO] org.orbisgis.orbisdata.processmanager.process.GroovyProcessFactory - Generating minimum polygon areas
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
org.h2.jdbc.JdbcSQLNonTransientException: Exception lors de l'appel de la fonction définie par l'utilisateur: "union(MULTILINESTRING ((559472.194 6291021.554, 559472.194 6291021.555), (559472.194 6291021.555, 559469.1 6291031.1), (559469.1 6291031.1, 559466.631 6291037.739), (559466.631 6291037.739, 559469.5 6291038.6), (559469.5 6291038.6, 559470.5 6291039.6), (559470.5 6291039.6, 559471.6 6291046.6), (559471.6 6291046.6, 559.....................
 558873.936 6292657.327, 558867.537 6292593.066), (558867.537 6292593.066, 558864.775 6292593.087), (558864.775 6292593.087, 558871.2 6292657.6), (558871.2 6292657.6, 558871.525 6292662.192), (558871.525 6292662.192, 558874.301 6292662.47))): found non-noded intersection between LINESTRING ( 558852.2752000159 6292093.324799984, 558851.9990000001 6292093.601 ) and LINESTRING ( 558852.369 6292093.231, 558851.999 6292093.601 ) [ (558852.219340668, 6292093.380659332, NaN) ]"; SQL statement:
(select st_polygonize(st_union(
                st_precisionreducer(st_node(st_accum(st_force2d(a.the_geom))), 3))) as the_geom, id_rsu from tmp_tables_zindex0_593e5db7_bdf5_4352_b2e9_63ac3a51be78 as a group by id_rsu) [90105-200]

**Comment by ebocher** [comment]
Fixed. See the beautiful LCZ map
![daux_lcz](https://user-images.githubusercontent.com/1820572/98704916-7a9e2200-237d-11eb-83e9-61508b6306c6.png)

**Comment by ebocher** [comment]
Fixed
