### ISSUE TITLE
Trouble with BDTOPO nb_lev

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#441]
I have several buildings in BDTOPO_V2 Vannes that have a building height roof = 2 m. Then the algorithm to set the building heights and nb_lev gives nb_lev=0 m... Which then leads to a floor_area = 0.
Should we set the building height roof to 3 and then it will correct the nb_lev to 1 or should we keep building height roof to 2 m and thus set nb_lev to 1 ?

**Comment by ebocher** [comment]
I vote to keep building height roof to 2 m and thus set nb_lev to 1

**Comment by j3r3m1** [comment]
BATIMENT0000000290121365 for example

**Comment by ebocher** [comment]
Is it in the BDTOPO test file ?

**Comment by j3r3m1** [comment]
OK the problem then is that we set a minimum building height  (hLevMin=3 m by default).
Then should I add a fix to all buildings having height_roof < 3 m to 3 m ?

**Comment by ebocher** [comment]
we will have the same behaviour with OSM

**Comment by j3r3m1** [comment]
OK solved in #442

**Comment by ebocher** [comment]
Thanks
