### ISSUE TITLE
Geoclimate chain re-processing

### ISSUE THREAD

**Issue by ernlt** [orbisgis/geoclimate#451]
I have the following error in the Geoclimate execution:
https://github.com/orbisgis/geoclimate/blob/master/geoindicators/src/main/groovy/org/orbisgis/orbisprocess/geoclimate/geoindicators/SpatialUnits.groovy
![Capture d’écran du 2020-10-21 10-49-12](https://user-images.githubusercontent.com/68550685/96696484-1cd47680-138b-11eb-92b2-adb87bcfd6c7.png)

**Comment by j3r3m1** [comment]
It seems to be the same error that we have previously faced in H2. I know that deleting the database solved the problem but it is probably not a solution in your case.

**Comment by ernlt** [comment]
On localhost, I have cleaned my workspace by deleting all output directories or .db files generated when running the chain.

**Comment by SPalominos** [comment]
@ernlt Can you give the groovy script you are using to run the SpatialUnit processes ? Also the configuration file if you have one.

**Comment by ebocher** [comment]
Fixed https://github.com/orbisgis/geoclimate/pull/490
