### ISSUE TITLE
Command builder to run processing chain

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#46]
This is a proposal to offer a simple way to run a processing chain.
The idea is to declare each chain as command line builder.

see https://picocli.info/#_groovy

**Comment by j3r3m1** [comment]
I am not sure I really get it. Could you give an example ?

**Comment by ebocher** [comment]
Something like

geoclimate -building = '/tmp/mybuilding.shp' -preparedata - usr

**Comment by j3r3m1** [comment]
The syntax would be something like:
`geoclimate --inputs --processingChainName --outputs`

So, for example, if we use the first processing chain I have push to you it would be something like:
`geoclimate --datasource="H2GIS", --distBuffer = 1000, etc. --PrepareBDTopo --outputBuilding = "BUILDINGS", etc.`

Is is easy to identify the name of the processing chain if we have several inputs and outputs and we do not identify it specifically ?

**Comment by ebocher** [comment]
We have to imagine a simple solution (out of an IDE or a groovy console) to execute the global processing chain. For example, if I want to process the BD Topo  data and calculate indicators, I need an access point to start the processing. 
Currently I have no idea about the best syntax to do that ;-) .
In  mind, I have the SAGA commands.

**Comment by SPalominos** [comment]
You can find a list of the reserved characters [here](https://docstore.mik.ua/orelly/unix2.1/upt/ch08_19.htm).
Maybe we can use a syntax like : `geoclimate [INPUTS]... CHAIN/PROCESS` (which is used for most of the unix command like `cp`, `mv`, `ls` ...) which become in your examples :
 ``` bash
$ geoclimate --building='/tmp/mybuilding.shp' preparedata/usr
$ geoclimate --datasource="H2GIS" --distBuffer=1000 PrepareBDTopo
```
With a realistic case :
``` bash
$ geoclimate --datasource="path/to/database" --osmTablesPrefix="EXT" zoneCode="35236" --extendedZoneSize=1000 --bufferZoneSize=500 PrepareData/OSMGISLayers/loadInitialData
```

I start a simple implementation and you both will comment it to improve and fix the syntax.

**Comment by j3r3m1** [comment]
OK no need to reinvent the powder (sorry for this one...) I think that the usual UNIX command is a good practice, we can not promote standard if we create our own syntax for something already existing and close to what we want.

**Comment by ebocher** [comment]
My issue is just to start a discussion. I think we must take time before coding something.

**Comment by ebocher** [comment]
So, in reference to the group of mappers, I propose to write a groovy script that offers a way to run each mappers. The script is parametrized from a CLI syntax.

Proposed syntax : 

groovy /tmp/geoclimate_chain.groovy -data -process -folder

where
-data [osm -code  -distance(optional)  -out(optional) ], [bdtopo -folder -format shp (optional default shp) -code -distance(optional) -out(optional)] //Mutually Exclusive Options with picoli
-process [gi -code -out(optional)],[lcz -code -out(optional)], //Mutually Exclusive Options with picoli
-dbfolder is the output directory to store the H2GIS database and result files
-log [false, true] to log messages

Examples

//Extract and prepare the OSM data to the abstract model
 groovy /tmp/geoclimate_chain.groovy -data osm -code 56260 -dbfolder /tmp/myOutputFolder

Note : all tables of the abstract model must prefixed or suffixed with the code name of the area

//Import and prepare the BDTOPO data to the abstract model
 groovy /tmp/geoclimate_chain.groovy -data bdtopo -folder /tmp/ -format shp -code 56260 -dbfolder /tmp/myOutputFolder

Note : all tables of the abstract model must prefixed or suffixed with the code name of the area

//Compute geoindicators 
 groovy /tmp/geoclimate_chain.groovy -process gi code 56260 -out -dbfolder /tmp/myOutputFolder

Note: the -code value is used to check the abstract table in the database, specified by -dbfolder
If -out is set the output tables are saved in geojson gzip in the -dbfolder. 

same for approach for tissues classification, lcz...

**Comment by j3r3m1** [comment]
Once we have achieve a first version of the processing chains, may be it will be easier to use real examples because I am still not sure to get why there is so few inputs in your -process gi

**Comment by ebocher** [comment]
yes sure

**Comment by ebocher** [comment]
I closed this issue because since Geoclimate dependencies package you are able to run a script that do all the job.
groovy geoclimate.groovy
I think it's enough yet
