### ISSUE TITLE
Connect mappers

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#48]
We have finished the coding of the first mapper (to prepare the BDTopo data). 
The objective is to create a mapper that integrate the full chain of processes (from BDTopo importing to indicator calculation).
We have decided to separate the main tasks into submappers as follow:
- data preparation: the prepareBDTopoData is coded
- create the spatial units: we should code the corresponding mapper
- calculate some of the indicators : we should code the corresponding mapper

In order to make this job, I have two questions:
- should we store each mapper in a separate file as it is done for the prepareBDTopo one or is it possible to code several mappers in a same file (for example all those that concerns the data preparation - OSM and BDTopo - all those that regards spatial unit preparation and all those that concerns the indicator calculation) ?
- is it already possible to connect several mappers ?

**Edit:** I also have a third question: is the mapper appropriate to compute parrallel chains ? For examplei in the case of the spatial unit creation:
-->P1-->P2-->
----->P3------>

**Comment by SPalominos** [comment]
- Several mappers can be written in the same file (like for the processes).
- Now you can't connect the mapper, but this feature is coming.
- The mapper doesn't execute processes or chain in parallel. This feature is also coming.

**Comment by ebocher** [comment]
To connect mapper with another mapper a good way will be to integrate a mapper in a process so you can connect this process with another process in a mapper.

**Comment by j3r3m1** [comment]
I did not test it but it seems relevant. What do you think @SPalominos ? Is it correct or you would prefer a different solution ?

**Comment by SPalominos** [comment]
I think it would be great to be able to link mappers like if they were processes.

**Comment by j3r3m1** [comment]
So you would modify the mappers in order to make them have inputs and outputs ? It could be a good opportunity to better define which input goes where. I have in mind the problem of lack of differentiation of two inputs belonging to the same mapper that would have the same name but would be used in two different IProcess.
For example, the datasource that could be different (not the case yet but we should be able to deal with this issue).
I think that if we can map different mappers the same way as we can map processes, it would be interesting. And it would be nice to be able to "map" the mapper inputs also the same way we map IProcesses even if they do not come from an other mapper...
