### ISSUE TITLE
Trouble to characterize LCZ outside city center

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#482]
In some residential areas, it may be quite complicated to distinguish heterogeneous tissues since roads do not boucle. Thus we may have large vegetation areas and some dense buildings that would become a sparsely built area while it should be two disctinct zones. In order to solve this problem, we may decrease the vegetation_surface value (currently to more 10000 or more - I propose to set 5000 m²).

**Comment by ebocher** [comment]
Good idea

**Comment by ebocher** [comment]
Currently we have as default value surface_vegetation: 100000 m2

**Comment by j3r3m1** [comment]
OK definitely too much, 5000 would be definitely better (if too much, we may go up to 10000 but I think 5000 is good)

**Comment by ebocher** [comment]
10 000 for 1 ha ?

**Comment by j3r3m1** [comment]
Yes but I would rather prefer 5000

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
Fixed
