### ISSUE TITLE
SQL error with several placenames

### ISSUE THREAD

**Issue by ernlt** [orbisgis/geoclimate#483]
On localhost, in the groovy configuration file, when specifying 2 litteral placenames (for ex. def osmFilters=["vannes","lorient"], the compilation works normally until it must generate the grid with createGrid process. 

```
> [ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
> org.h2.jdbc.JdbcSQLSyntaxErrorException: La table "COPERNICUS_GRID" existe déjà
> Table "COPERNICUS_GRID" already exists; SQL statement:
> CREATE TABLE copernicus_grid AS SELECT * FROM ...
```

Actually, it seems logical to get this error, as we do not delete the grid table if it already exists.
So, I suggest to add the following lines in the SpatialUnits.createGrid process, before the 1rst 'if' statement:

```
def BASENAME = "grid"
def outputTableName = prefix prefixName, BASENAME
datasource "DROP TABLE IF EXISTS $outputTableName;"
```

A simillar error would appear in the GenericIndicators.upperScaleAreaStatistics process.
Before the line  [outputTableName: outputTableName], we have to add the following lines (the ';' caracter was missing) 

```
 // Drop intermediate tables created during process
 datasource "DROP TABLE IF EXISTS $spatialJoinTable, $pivotTable;"
 info "The table '$outputTableName' has been created"
```

Actually I have already made the updates for the processes, but my PR seems not to build normally...

**Comment by ebocher** [comment]
Good catch. Feel free to send a PR

**Comment by ebocher** [comment]
In fact, this issue is related to the Corpenicus script.

**Comment by ernlt** [comment]
Yes, this issue uses processes related to the groovy configuration file for Copernicus configuration.

**Comment by ernlt** [comment]
Fixed

**Comment by ebocher** [comment]
Fixed ?

**Comment by ernlt** [comment]
> Fixed ?

Yes Fixed.
