### ISSUE TITLE
Relationships between spatial units

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#49]
For the calculation of some of the geospatial variables, we need the correlation Table between spatial units as input (for example building and block, building and RSU and block and RSU).
In order to create those Tables, I see two solutions: we create a new file which could be called "units_relations" or we add an IProcess in the spatial_unit file which could be called "unitRelationCalculation".
What is your opinion concerning this point ?

**Comment by ebocher** [comment]
Because we have an abstract model that constrains the input data, I think the good method will be to assume that with have the following indexes
building table : id_rsu, id_block
block table : id_rsu
rsu table :  id_rsu

Consequently, the process that build the relationships must update the input tables with the corresponding indexes.

**Comment by j3r3m1** [comment]
OK for updating the input Tables. Two questions then:
- isn't it "too costly" to use the "update" query (compare to a create table) ?
- where should be made this update ? In the prepare data, in the spatialUnits of the geoindicators class or in a new class within the geoindicators ?

**Comment by gpetit** [comment]
It can be done only after the creation of RSU and blocks. So if I understand well, not in the prepare data process.

Concerning the cost, we can test both options and choose the better one :
* update the existing table
* create a  new one by merging the input one and the relation one (for MAPUCE I think we choose this one)

**Comment by ebocher** [comment]
Note : the update command has a bug with H2 1.4.198. It's very very slow.
The second option proposed by @gpetit  sounds a good way.

**Comment by j3r3m1** [comment]
OK for the create table. I propose to code a single IProcess that would add an ID field of the upper scale in the table of the lower scale (would work for each of the combination building/block, building/rsu, block/rsu).

But then what about the location of the IProcess ? Do I add it to the SpatialUnit.groovy or in a new groovy script (for example called ScalesRelations.groovy) ?

**Comment by ebocher** [comment]
Put it in SpatialUnit.groovy
