### ISSUE TITLE
Use a grid as RSU to directly calculate climate model parameters

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#496]
We currently use roads, hydro, etc. to split the territory and then calculate the indicators for each of the reference spatial unit (RSU). Then climate simulations using those indicators have to aggregate values from those units to climate grid cell. For some indicators, the aggregation may have no sense. Thus a work could be made in two steps:
1. Identify indicators which has no physical meaning when aggregated (if there are some).
2. If there is no indicators concerned by this lack of meaning, then add an option in the workflow to aggregate directly to a grid of square cells. Else use directly the grid cells as the RSU for the indicator calculation.

**Comment by ebocher** [comment]
I propose to add this kind of parameters into the workflow config file to manage the grid size and the parameters that will be aggregated.
```
{"distance" : 500,
        "indicatorUse": ["LCZ", "URBAN_TYPOLOGY"],
        "svfSimplified": true
 "grid_aggregation": {
            "x_size": 1000,
            "y_size": 1000,
            "indicators": ["BUILDING_MEAN_HEIGHT","BUILDING_MEAN_AREA","WATER_MEAN_AREA"]
	}
}
```

indicators is a list of fixed indicator names.
The extent of the grid corresponds to the extent of the input zone
The result is stored in one table named grid_indicators

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
done https://github.com/orbisgis/geoclimate/pull/507
