### ISSUE TITLE
OSM license copyleft

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#50]
Add in all osm processes a link to https://www.openstreetmap.org/copyright

**Comment by ELSW56** [comment]
What do you mean by "all osm processes" ?
The ones that use the overpass API ?
The ones that use the node, way, ... tables ?
Only the processes or any method/function/procedure ?

**Comment by ebocher** [comment]
It seems that a reference to OSM  must be added when any code uses OSM data.
What do you think if we set a ref on top of the OSMGISLayers, here https://github.com/orbisgis/geoclimate/blob/master/prepare_data/src/main/groovy/org/orbisgis/osm/OSMGISLayers.groovy#L8

**Comment by ELSW56** [comment]
OK, it will be included in the coming PR.
