### ISSUE TITLE
Use OSM trees to improve vegetation fraction evaluation

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#500]
Extract OSM trees and use the new layer to better characterize the fraction of vegetation.
It'd be interesting for urban areas
@j3r3m1

**Comment by j3r3m1** [comment]
For this issue, we can pick up the tag [diameter_crown](https://wiki.openstreetmap.org/wiki/Key:diameter_crown) (even though it is only 1.34% of all trees).
However, we need a default value for other trees.
@wurtzj @ebocher what do you think about 4 m ?

**Comment by ebocher** [comment]
Not sure to understand. Do you want to add the tree information to the fraction of vegetation ? Or do you want to have a tree layers to improve the SVF indicator ?

**Comment by j3r3m1** [comment]
The idea is mainly to add some more vegetation fraction (which might superimpose with roads)

**Comment by wurtzj** [comment]
Hi Jeremy,

The approximation seems roughly correct to me.
Emilie Bernard who worked on the vegetation database in TEB used a linear relationship between tree height and tree crown based on observations : TREE_CROWN = 0, 4847 ∗ TREE_HEIGHT
Based on a tree height of **10 meters** (which is the mean of tree height computed by Emilie) it gives a crown of **~4.8m.**

Maybe you can also collect some information on the type of vegetation (leaf cycle and leaf type) and on it's height. Maybe doing a majoritarian mean for the type of vegetation ?
Maybe if you can get the tree height you can compute the crown using this linear relationship ?

**Comment by j3r3m1** [comment]
> Emilie Bernard who worked on the vegetation database in TEB used a linear relationship between tree height and tree crown based on observations : TREE_CROWN = 0, 4847 ∗ TREE_HEIGHT

Sousa and Gorlé (2019) found a slightly different relation (TREE_HEIGHT = 5 + 0,5 ∗TREE_CROWN) but it was based on very small sample of trees (35)

> Based on a tree height of **10 meters** (which is the mean of tree height computed by Emilie) it gives a crown of **~4.8m.**

Excellent ! We can round to 5.

> Maybe you can also collect some information on the type of vegetation (leaf cycle and leaf type) and on it's height. Maybe doing a majoritarian mean for the type of vegetation ?

Do you mean use a default value being the majoritarian mean when the type is missing ?

> Maybe if you can get the tree height you can compute the crown using this linear relationship ?

Yes this is definitely an option if we have the tree height but not the tree crown width but both tree height and tree crown width are quite rare anyway.


Sousa, Jorge, et Catherine Gorlé. « Computational Urban Flow Predictions with Bayesian Inference: Validation with Field Data ». Building and Environment 154 (1 mai 2019): 13‑22. https://doi.org/10.1016/j.buildenv.2019.02.028.

**Comment by wurtzj** [comment]
> Do you mean use a default value being the majoritarian mean when the type is missing ?

Yes.

**Comment by ebocher** [comment]
In order to integrate the trees to improve the vegetation fraction, we need to : 

- [ ] create a new tree layer with the folowing schema : POINT, id, diameter_crown, height

The diameter_crown will be used to compute the fraction.

- [ ] update the fraction of vegetation using a buffer arround each tree

**Comment by j3r3m1** [comment]
Duplicated with #686
