### ISSUE TITLE
Let's try to be a little less wordy

### ISSUE THREAD

**Issue by ELSW56** [orbisgis/geoclimate#508]
Now that things work well, we should think of limiting the "Info" given to the users.
We could separate real users informations from debugging informations

**Comment by ebocher** [comment]
We need to use debug method more often instead of info.
In addition, the name of the package must be removed in the logs

**Comment by ebocher** [comment]
@SPalominos  @j3r3m1

**Comment by j3r3m1** [comment]
> We need to use debug method more often instead of info.
> In addition, the name of the package must be removed in the logs

I agree both assertions

**Comment by j3r3m1** [comment]
> We need to use debug method more often instead of info.
> In addition, the name of the package must be removed in the logs
The best would be to keep a debug log with the package name (easier to debug for us) and simple informations for user mode

**Comment by ebocher** [comment]
@SPalominos 
Can you point us an example to custom the log ?

**Comment by ebocher** [comment]
Done thanks @SPalominos
