### ISSUE TITLE
Only building height estimation

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#509]
In the new version of the configuration file, we need to set at least one "indicatorUse" type (LCZ, TEB, URBAN_TYPO). However, for OSM, a user could only want to get OSM data with estimated building height.
Thus it would be nice if the workflow could work with "indicatorUse" = [], ie calculate indicators for building height estimation and then nothing else.

**Comment by ebocher** [comment]
Good idea

**Comment by ebocher** [comment]
Done
