### ISSUE TITLE
prefixName issue

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#51]
In the SpatialUnits IProcesses, the outputTableName has been replaced by the prefixName but the outputTableName is still in the Javadoc as param. It should be removed.

The prefixName is used to build the outputTableName as follow:
```groovy
String outputTableName = prefixName+"_"+UUID.randomUUID().toString().replaceAll("-","_")
```
I thought that the prefixName was useful to distinguish two calculations proposed by one user when he needs the same IProcess but not the same input data. Then I thought that a base name was automatically defined in the script (for example script name) and that the user would have the opportunity to add the prefixName to this base name. My proposition would be:
```groovy
String outputTableName = prefixName+"_baseNameOfIprocess"
```

Using the current code, the output would be pretty ugly (due to the UUID) and hard for the user to simply identify.

**Comment by ebocher** [comment]
Sure UUI output value is a bit ugly, but  UUID is important to avoid table conflict name.

An idea could be   :
String outputTableName = "baseNameOfIprocess"+"_"+UUID.randomUUID().toString().replaceAll("-","_") 

So the user understand that the ugly table name has been produced from the baseNameOfIprocess

As a consequence we must have one identifier for each IProcess a WPS script requires.

**Comment by j3r3m1** [comment]
I thought that the prefix was proposed by the user to avoid conflict.
The problem with the UUID is that for a mapper, the resulting tables will not have the same UUID. Then it will be complicated to distinguish two Tables if the user want to reuse the same mapper on a different dataset.

**Comment by j3r3m1** [comment]
My proposition is retained

**Comment by ebocher** [comment]
Should we have a prefix or a suffix for the table name?
Imagine, I want to keep the code of my zone in the table name.
56260_rsu will cause a pb with the sql syntax.

**Comment by j3r3m1** [comment]
Then may be a suffix is more adapted although I thought that th prefix was useful to gather all the tables of a dataset more easily

**Comment by j3r3m1** [comment]
done in #71
