### ISSUE TITLE
OSM estimated building height tag

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#514]
When building height is estimated, the final building table contains the estimated height in the "height_roof" value but we can not make the difference between buildings having estimated height and those having user filled height. Any chance to add this field in the abstract model ? Could be useful both for OSM and BDTopo since building height could also be null or 0 for some buildings.

**Comment by ELSW56** [comment]
You mean, adding a flag ? Like 0 when user filled height and 1 when it's estimated ?

**Comment by j3r3m1** [comment]
yep, I think that this information already exists since only some buildings have their height estimated

**Comment by ELSW56** [comment]
For OSM, during the formatBuildingLayer process, a table is created with the building table name prefixed with "est_". The columns are id_build, id_source and a boolean flag called "estimated" and it contains as many rows as the building table.
Is this what you were searching for ?

**Comment by j3r3m1** [comment]
Yes, definitely. What about adding this column in the building table ?

**Comment by ELSW56** [comment]
@ebocher : do you use this special table for the statistical estimation ?

**Comment by ebocher** [comment]
We can easily back up the table the estimated buildings. It is necessary to think about to add a parameter to the osm workflow.

**Comment by j3r3m1** [comment]
what do you mean by parameter ? A parameter to say whether or not we want to save the table ? Ideally I would have had this field directly in the building table. 
I think that the process of height estimation is generic, thus parameters adding should be valid for osm and bdtopo.

**Comment by ebocher** [comment]
When the estimatedHeight parameter is set to true we can save the ids of the building with their height that must be estimated in a json file.
So you are welcome to join it with the output building indicators.

**Comment by j3r3m1** [comment]
sounds good. Does it work right now ?

**Comment by ebocher** [comment]
Fixed you can now set in the table name building_height_missing to store the id_build and the id_source of the buildings that have no height values. The table is saved in a csv or a database table.
Have fun with it ;-)
