### ISSUE TITLE
Bad sea land mask extraction for area [52.08484801362273, -10.75003575696209, 52.001518013622736, -10.66670575696209]

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#519]
As the figure shows the whole area is tagged as land.

![sea_land_mask_pb](https://user-images.githubusercontent.com/1820572/105825890-6652e400-5fc0-11eb-97b0-7042a8a3bbb2.png)

@ELSW56  @ernlt 

I'm on it

**Comment by ernlt** [comment]
It seems that there is a very small islet in this area

**Comment by ebocher** [comment]
Done fixed
![sea_land_islet](https://user-images.githubusercontent.com/1820572/105833239-33611e00-5fc9-11eb-98d4-2ec5f08b6ce9.png)
