### ISSUE TITLE
Hydro transformation very slow

### ISSUE THREAD

**Issue by ELSW56** [orbisgis/geoclimate#529]
While executing the workflow on bbox [69.24666, 28.3359, 69.32999, 28.41923], a "problem" occurred.
It took approximately 1 hour for the process to finish and 95% of the time was spent on the process called formatHydroLayer in the file FormattingForAbstractModel.groovy.
The same "problem" happened in quite some different areas with similar characteristics.

![image](https://user-images.githubusercontent.com/31065426/106263540-ce096900-6224-11eb-85ab-b584600355f7.png)

**Comment by ebocher** [comment]
This is a quite complex issue because we need to find a better algorithm to extract faster the sea/land mask.

**Comment by ebocher** [comment]
Fixed.
