### ISSUE TITLE
osm files cleanup incomplete

### ISSUE THREAD

**Issue by ELSW56** [orbisgis/geoclimate#530]
When downloading OSM data is impossible due to the Overpass API restriction, an OSM file is created anyway and the new possibility to delete the files, once they are read into H2GIS, is not applied.

**Comment by ebocher** [comment]
Good catch we must delete the temporary file when OSM fails

**Comment by ebocher** [comment]
Fixed on OSM tool side https://github.com/orbisgis/orbisanalysis/pull/83

**Comment by ebocher** [comment]
Fixed
