### ISSUE TITLE
OSM Worflow temporary tables cleaning

### ISSUE THREAD

**Issue by ELSW56** [orbisgis/geoclimate#534]
I've already been working on the removal of temporary tables that are generated by several processes.
Before going further, I'd like to know whether or not there are some left in the following list :

- BUILDING_INDICATORS
- DISTRIBUTION_REPARTITION
- EST_INPUT_BUILDING_9B2712D8_94DE_464A_91AC_A9E217669C9C
- GRID_INDICATORS
- INPUT_BUILDING_9B2712D8_94DE_464A_91AC_A9E217669C9C
- INPUT_BUILDING_9B2712D8_94DE_464A_91AC_A9E217669C9C_GRID_EF1A2BA9_70DE_4CB4_9476_86C8760322CD_JOIN
- INPUT_BUILDING_9B2712D8_94DE_464A_91AC_A9E217669C9C_RSU_JOIN
- INPUT_HYDRO_5854BE08_5F56_4CF8_B8EB_B9F7891574BF
- INPUT_IMPERVIOUS_171470DB_A819_4D4A_A30D_2FA9B4AC9ADC
- INPUT_RAILS_8E2D636D_1AFE_4422_8567_E296DFC8E554
- INPUT_ROAD_188C0D3A_10DE_4998_B1E2_EEAF2B150BBE
- INPUT_SEA_LAND_MASK__1C29C84F_6743_43A1_AE08_FCD027396CC3
- INPUT_URBAN_AREAS_9C23B5C1_BAF1_4801_B86F_75FF4E1428AC
- INPUT_VEGET_7157732C_13D6_47F1_8388_E0539E2BB4D6
- INPUT_WATER_SEA__9C35AFEB_40D0_4D48_936C_002A7AAE89C9
- LOG_ZONES_B0E050CA_ACF0_49E7_B78D_415F4996DA96
- PREPARED_RSU_DATA
- RSU
- RSU_INDICATORS
- RSU_INDICATOR_RSU_EXTENDED_FREE_FACADE_FRACTION
- RSU_INDICATOR_RSU_SMALLEST_COMMUN_GEOMETRY
- RSU_LCZ
- RSU_SMALLEST_COMMUN_GEOMETRY
- ZONE_6EEC33B9_CB9A_45B3_9AC2_5F7E0AD34232
- ZONE_ENVELOPE_DD95C5E2_C1ED_4921_B742_9C73FF818849

FYI, these tables are the result of the OSMWorkflow with the following configuration : 
```
def osm_parameters = [
                "description" :"Example of configuration file to run the grid indicators",
                "geoclimatedb" : [
                        "folder" : "${dirFile.absolutePath}",
                        "name" : "test_db;AUTO_SERVER=TRUE",
                        "delete" :false
                ],
                "input" : [
                        "osm" : [[
                                         68.83001,
                                         20.41955,
                                         68.91334,
                                         20.50288
                                 ]],
                        "delete":true],
                "output" :[
                        "folder" : ["path": "$directory",
                                    "tables": ["zones",
                                               "rsu_indicators",
                                               "rsu_lcz",
                                               "grid_indicators"]],
                        "srid":4326],
                "parameters":
                        ["distance" : 0,
                         "rsu_indicators": [
                             "indicatorUse": ["LCZ"],
                             "svfSimplified": true,
                             "estimateHeight": true
                         ],
                         "grid_indicators": [
                             "x_size": 10,
                             "y_size": 10,
                             "rowCol": true,
                             "indicators": ["BUILDING_FRACTION",
                                            "BUILDING_HEIGHT",
                                            "WATER_FRACTION",
                                            "VEGETATION_FRACTION",
                                            "ROAD_FRACTION",
                                            "IMPERVIOUS_FRACTION",
                                            "LCZ_FRACTION"],
                             "output":"asc"
                         ]
                        ]
        ]
```

**Comment by j3r3m1** [comment]
> Before going further, I'd like to know whether or not there are some left in the following list

You mean which one of these should be kept ?

**Comment by ELSW56** [comment]
I mean, from the given list, which are those that are temporary tables left.
But you can as well tell me which are the ones that need to be kept ;)

**Comment by j3r3m1** [comment]
I would say that as you have specified as output tables : "zones",
                                               "rsu_indicators",
                                               "rsu_lcz",
                                               "grid_indicators"
Only those should be conserved ? =)
Strange that some of the temporary tables do not have suffix:

- DISTRIBUTION_REPARTITION
- PREPARED_RSU_DATA
- RSU_INDICATOR_RSU_EXTENDED_FREE_FACADE_FRACTION
- RSU_INDICATOR_RSU_SMALLEST_COMMUN_GEOMETRY
- RSU_SMALLEST_COMMUN_GEOMETRY

**Comment by ELSW56** [comment]
Thanks @j3r3m1. I'll have a look and add postfix when necessary.
@ebocher : ok for you ?

**Comment by ebocher** [comment]
Some table names are defined with a unique name using the postfix method so they will be delete inside the process.
But be careful some table names are cached to b reused by other processes, so if you drop it you will break the chain.
I don't know which ones. You have an example here https://github.com/orbisgis/geoclimate/blob/master/geoindicators/src/main/groovy/org/orbisgis/orbisprocess/geoclimate/geoindicators/RsuIndicators.groovy#L1553

**Comment by ebocher** [comment]
BUILDING_INDICATORS
kept

    DISTRIBUTION_REPARTITION
delete

    EST_INPUT_BUILDING_9B2712D8_94DE_464A_91AC_A9E217669C9C
delete
    GRID_INDICATORS
kept
    INPUT_BUILDING_9B2712D8_94DE_464A_91AC_A9E217669C9C
kept
    INPUT_BUILDING_9B2712D8_94DE_464A_91AC_A9E217669C9C_GRID_EF1A2BA9_70DE_4CB4_9476_86C8760322CD_JOIN
delete

    INPUT_BUILDING_9B2712D8_94DE_464A_91AC_A9E217669C9C_RSU_JOIN
to check

    INPUT_HYDRO_5854BE08_5F56_4CF8_B8EB_B9F7891574BF
kept
    INPUT_IMPERVIOUS_171470DB_A819_4D4A_A30D_2FA9B4AC9ADC
kept
    INPUT_RAILS_8E2D636D_1AFE_4422_8567_E296DFC8E554
kept
    INPUT_ROAD_188C0D3A_10DE_4998_B1E2_EEAF2B150BBE
kept
    INPUT_SEA_LAND_MASK__1C29C84F_6743_43A1_AE08_FCD027396CC3
kept
    INPUT_URBAN_AREAS_9C23B5C1_BAF1_4801_B86F_75FF4E1428AC
kept
    INPUT_VEGET_7157732C_13D6_47F1_8388_E0539E2BB4D6
kept
    INPUT_WATER_SEA__9C35AFEB_40D0_4D48_936C_002A7AAE89C9
kept
    LOG_ZONES_B0E050CA_ACF0_49E7_B78D_415F4996DA96
kept
    PREPARED_RSU_DATA
delete
    RSU
delete
    RSU_INDICATORS
kept
    RSU_INDICATOR_RSU_EXTENDED_FREE_FACADE_FRACTION
delete
    RSU_INDICATOR_RSU_SMALLEST_COMMUN_GEOMETRY
delete but at the end of the workflow
    RSU_LCZ
kept
    RSU_SMALLEST_COMMUN_GEOMETRY
delete but at the end of the workflow
    ZONE_6EEC33B9_CB9A_45B3_9AC2_5F7E0AD34232
kept
    ZONE_ENVELOPE_DD95C5E2_C1ED_4921_B742_9C73FF818849
kept

**Comment by ELSW56** [comment]
> 
> 
> Some table names are defined with a unique name using the postfix method so they will be delete inside the process.
> But be careful some table names are cached to b reused by other processes, so if you drop it you will break the chain.
> I don't know which ones. You have an example here https://github.com/orbisgis/geoclimate/blob/master/geoindicators/src/main/groovy/org/orbisgis/orbisprocess/geoclimate/geoindicators/RsuIndicators.groovy#L1553

OK. Up to now, I've been looping on :
- remove one table
- start the process again in the same conditions

to be sure the chain was not broken. I'll do the same with the remaining temp tables.

By the way, do you think it could be a good idea :

- to give a special prefix (like tmp_) to all the tables that shouldn't be kept
- to give the same postfix to all the tables that have to be kept and concern the same zone ?
