### ISSUE TITLE
Geoclimate Licence

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#544]
Hi,
It seems there is a difference between the [licence (GPL v3)](https://github.com/orbisgis/geoclimate/blob/master/LICENSE) and the tag displayed by Github (LGPL v3)

![image](https://user-images.githubusercontent.com/1871248/108688073-ca04fa00-74f7-11eb-9d9b-3f0f2182d561.png)

@ebocher @j3r3m1

**Comment by ebocher** [comment]
You are right. Geoclimate Licence file must be LGPL 3.
