### ISSUE TITLE
Error grab dependencies

### ISSUE THREAD

**Issue by juldd** [orbisgis/geoclimate#545]
Pendant notre installation :
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate',version='1.0.0-RC1')

on reçoit un message d'erreur :
Error grabbing Grapes -- [unresolved dependency: org.orbisgis.orbisprocess#geoclimate;1.0.0-RC1: not found].

Est-ce qu'il faut pas changer la version?
Merci pour votre aide :D

**Comment by j3r3m1** [comment]
I have tried and got the same error in the Groovy Console. We are currently updating some of the libraries (#515), which maybe could explain why we get this error.

We also have the opportunity to download directly the .jar of the last version with all dependencies:
```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')

// Declaration of our Nexus repository, where the geoclimate project is stored
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT', classifier='jar-with-dependencies', transitive=false)
```
But I got a different error:
>java.lang.RuntimeException: Error grabbing Grapes -- [download failed: org.orbisgis.orbisprocess#geoclimate;1.0.0-SNAPSHOT!geoclimate.jar]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

@SPalominos @ebocher do you confirm the reason of the first error and do you have any idea for the second one ?

@juldd I think the best solution for now is to use the entire workflow using the command line. Have you tried it ?

PS: If you can write in English it is even better =)

**Comment by j3r3m1** [comment]
You may try to replace your grab line by the SNAPSHOT one, I have tried it seems to work:
```groovy
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')
```

**Comment by juldd** [comment]
Hello, unfortunately, we have the other errors this time.
We used : 
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT', classifier='jar-with-dependencies', transitive=false)
import org.orbisgis.orbisprocess.geoclimate.Geoclimate
Geoclimate.logger = logger
def process = Geoclimate.Workflow.BDTOPO_V2()
process.execute(configurationFile:'/home/geoclimate/bdtopo/config_all_zones.json')                  
logger.info process.results.outputMessage 

but we obtained the message error : groovy.lang.MissingPropertyException: **No such property: logger for class: scrip_groovy at scrip_groovy.run(scrip_groovy:6)** 
Thanks for your help.

**Comment by j3r3m1** [comment]
Yes you can remove the logger line not useful here, you will probably have the messages logged in the console anyway.

**Comment by juldd** [comment]
At this time:
2 compilation errors:

unable to resolve class org.orbisgis.orbisprocess.geoclimate.Geoclimate
 at line: 1, column: 1

unable to resolve class grab
 at line: 2, column: 1

**Comment by j3r3m1** [comment]
> Hello, unfortunately, we have the other errors this time.
> We used :
> @GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
> @grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT', classifier='jar-with-dependencies', transitive=false)
The problem may come from the grab command. Should be Grab instead of grab.

**Comment by juldd** [comment]
Thank you !
Now, I think that I have a problem with the configuration file. In my bdtopo I configurated my 2 files: config_all_zones.json and config_id_zone.json, but I got a message : 
java.lang.NullPointerException: Cannot invoke method BDTOPO_V2() on null object
Did we have to change our path in the other configuration files?
Best regards

**Comment by j3r3m1** [comment]
I have changed the title of the issue (in order to be more specific concerning the problem met) and marked it as solved. Could you open an new issue and clarify where is your configuration file and what is inside ?
