### ISSUE TITLE
problem with BDTOPO method

### ISSUE THREAD

**Issue by juldd** [orbisgis/geoclimate#546]
For my test, I used your BD_TOPO in "sample_12174".
 
[config_all_zones.txt](https://github.com/orbisgis/geoclimate/files/6061878/config_all_zones.txt)

Thanks for your help

**Comment by j3r3m1** [comment]
You should keep a .json format for your text file. When you save to .txt it seems that special characters are inserted into you file and would definitely create troubles when reading the file.

**Comment by juldd** [comment]
Ok, json is in zip file.

[config_all_zones.json.zip](https://github.com/orbisgis/geoclimate/files/6062015/config_all_zones.json.zip)

**Comment by j3r3m1** [comment]
Here is what I see when I load your file (my editor shows troubles with the json). 
![image](https://user-images.githubusercontent.com/13120405/109506346-d102ae00-7a9d-11eb-974b-05f0ebca50bc.png)

Quite difficult (or boring) to see it with human eyes but using gedit (simple editor in Unix) it is more simple to identify that there is one } which should not be there row 8 (I have selected it with my cursor). If you delete this one your json should be OK.

Then tell me where is located this configuration file and remind me the code command you use to call the configuration file (path and file name should be similar).

**Comment by juldd** [comment]
Ok, I got it. 
**groovy script:**
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT', classifier='jar-with-dependencies', transitive=false)
import org.orbisgis.orbisprocess.geoclimate.Geoclimate
def process = Geoclimate.Workflow.BDTOPO_V2()
process.execute(configurationFile:'/Users/julitadiallodudek/GEOCLIMATE/geoclimate/bdtopo/config_all_zones.json')

**Comment by ebocher** [comment]
If @juldd  runs the last compiled GeoClimate version (from Master), the json file must be updated with the new parameters group : 

```
"parameters":
                        ["distance" : 0,
                         "hLevMin": 3,
                         "hLevMax": 15,
                         "hThresholdLev2": 10,
                          rsu_indicators: [
                         "indicatorUse": ["LCZ", "TEB", "URBAN_TYPOLOGY"],
                         "svfSimplified": true]
                        ]
```
Sorry but the doc is not up to date.

**Comment by juldd** [comment]
It doesn't change anything. We have always the same error:
java.lang.NullPointerException: Cannot invoke method BDTOPO_V2() on null object
I have the impression that this error occurred before a configuration file was taken into account.

**Comment by j3r3m1** [comment]
@ebocher means:
```
"parameters":
                        {"distance" : 0,
                         "hLevMin": 3,
                         "hLevMax": 15,
                         "hThresholdLev2": 10,
                          rsu_indicators: {
                                 "indicatorUse": ["LCZ", "TEB", "URBAN_TYPOLOGY"],
                                 "svfSimplified": true}
                        }
```
Is your config file located at: '/Users/julitadiallodudek/GEOCLIMATE/geoclimate/bdtopo/config_all_zones.json' ?

**Comment by juldd** [comment]
indeed

**Comment by j3r3m1** [comment]
> It doesn't change anything. We have always the same error:
> java.lang.NullPointerException: Cannot invoke method BDTOPO_V2() on null object
> I have the impression that this error occurred before a configuration file was taken into account.

No the error happens when the method is called and the method can not find the file actually.

Is '/Users/julitadiallodudek/GEOCLIMATE/geoclimate/bdtopo/config_all_zones.json' an absolute path in macOS ? 

It seems not (see https://stackoverflow.com/questions/26634800/osx-absolute-desktop-file-path-including-volumes for example). Thus may be change your path in absolute path (even those in the configuration file) would make the job.

**Comment by julienpergaud** [comment]
Hello,

As julita explained, the problem should not come from json file. We have modified it and obtained always the same error with absolute path (on MacOs and linux). Moreover, there is a problem when using dbeaver with the version of groovy, but now we use only groovy console to solve this problem.
Anyway, the error comes from the definition of process in script_groovy file which is "def process = Geoclimate.Workflow.BDTOPO_V2() "
For Java, the method workflow seems not exist :
java.lang.NullPointerException: Cannot invoke method BDTOPO_V2() on null object
	at scrip_groovy.run(scrip_groovy:7)
Could you send us either a script groovy with the new snapshot version 1.0.0 or the geoclimate.jar file? I cannot download the jar file on nexus server.
Thx in advance

Julien

**Comment by j3r3m1** [comment]
Well, you are right, I do not know about the absolute path but for sure the "def process" row is not updated...
I think you should instead use:
def process = Geoclimate.BDTOPO_V2.workflow

However, it seems that there is no log related to the workflow if you remove the row
Geoclimate.logger = logger

Let me know first if you do not have the same error... =)

**Comment by juldd** [comment]
Hi,
This time : 
The process has been stopped since the table BATI_INDIFFERENCIE has a no SRID
Cannot import preprocess.

I run geoclimate with java -jar only.
Thank you for your help ;D

**Comment by ebocher** [comment]
Hi,
I'm on it. I'm fixing some issues due to IO import-export file in H2GIS.
Our server is currently down so we are not able to publish a new version of GeoClimate.
See : https://twitter.com/OrbisGIS/status/1369334030211162122

**Comment by j3r3m1** [comment]
@ebocher updated the version and relaunched the server, I have made a test with the same sample as you, it works on my computer. Could you please make a test and let us know ?
Here is the script used:
```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate

def process = Geoclimate.BDTOPO_V2.workflow
process.execute(configurationFile:.../config_all_zones.json')
```

And the JSON:
```json
{
  "description" :"Process many cities using BD Topo v2",
  "geoclimatedb" : {
    "path" : "/tmp/geoclimate_db;AUTO_SERVER=TRUE",
        "delete" :true
    },
    "input" : {
        "folder": "/home/decide/Code/Intel/geoclimate/bdtopo_v2/src/test/resources/org/orbisgis/orbisprocess/geoclimate/bdtopo_v2/sample_12174/"
    },
    "output" :{
        "folder" : "/home/decide/testJulia/"},
    "parameters":
        {"distance" : 0,
         "hLevMin": 3,
         "hLevMax": 15,
         "hThresholdLev2": 10,
         "rsu_indicators": {
                 "indicatorUse": ["LCZ", "TEB", "URBAN_TYPOLOGY"],
                 "svfSimplified": true}
        }
}
```

Note that you should obtain an error since some tables are missing in the test folder (reservoir and aerodrome layers). However, everything goes up to the end and works fine.

**Comment by j3r3m1** [comment]
You should delete your .groovy to download the new archive

**Comment by juldd** [comment]
Hello with my BDtopo, 
I have the same error : 
The process has been stopped since the table BATI_INDIFFERENCIE has no SRID
 Cannot import preprocess.
I directly run a groovy script in my groovy console. Am I doing something wrong?
Best regards

**Comment by ebocher** [comment]
Seems that the BATI_INDIFFERENCIE.shp file has no prj file or perhaps the prj file is not valid and doesn't contain an EPSG code to detect the SRID.

**Comment by j3r3m1** [comment]
Do you still use the test file ?
I have checked, none of the file in the test folder have changed these last few months, thus it should work on your machine if you have the same Geoclimate version and the same data. How did you download the data ? Perhaps you missed the prj file when downloading or saving the data ?

**Comment by j3r3m1** [comment]
By the way @gpetit @ebocher, one of you has the BDTOPO for the test commune ? It could be nice if you could upload the "RESERVOIR" and "PISTE_AERODROME" layers (I suppose as empty tables ?) or change the ERROR as warning ?

**Comment by juldd** [comment]
I'm using my bdtopo for dijon region, I have also .prj file.

**Comment by juldd** [comment]
Is it possible to have errors if the names of our columns in bdtopo are in uppercase? Do I need to preprocess my data before running the groovy script?

**Comment by juldd** [comment]
I have the differences between prj file of sample_12174 and my prj file.

**Comment by j3r3m1** [comment]
> I'm using my bdtopo for dijon region, I have also .prj file.

Did you check that it works for 12174 sample ? We first need to know if it works for you with verified data

**Comment by juldd** [comment]
Yes it works

**Comment by juldd** [comment]
Do you want me to replace the prj for all shapefile?

**Comment by j3r3m1** [comment]
yes

**Comment by juldd** [comment]
IT WORKS !!! 👯

**Comment by j3r3m1** [comment]
Perfect ! May we close the is issue then ?
