### ISSUE TITLE
Simplify the access to each IProcess

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#548]
Currently, most of the geoindicators need inputs coming from other geoindicators outputs.
Let's see with an example:
>I want to calculate **O_a** which is the ouput of IProcess **IP_a**. For this I need the input value **I_a**, which is also the ouput **O_b** of IProcess **IP_b** (then **I_a** = **O_b**). Thus to get **O_a** I will need to first use **IP_b**, get its output and feed **IP_a** with it.

This is nice when we use the entire Worflow since calculations are not made twice. However it could be very complicated for a user to chain processes (identify which process should be called). As a future enhancement we may allow several signatures for IProcesses. If one specific input is not calculated, we may calculate it.

**Comment by ebocher** [comment]
This is a good idea but a hard job because we must think about all possibilities.
