### ISSUE TITLE
Delete database if error in the workflow

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#552]
Currently, if an error occur during the workflow and the error does not stop the workflow, it goes up to the end and delete the base if we have "delete: true" such as below in our configuration file.
```json
{
  "description" :"Any worfklow goal",
  "geoclimatedb" : {
    "path" : "/tmp/geoclimate_db;AUTO_SERVER=TRUE",
        "delete" :true
    },
}
```

It could then be complicated to analyse the problem, except restarting the process (which sometimes could be long). Several options:
- an error should stop the workflow (otherwise it is a warning ?) and thus not deleting the base
- an error should set the "delete: true" to "delete: false"

**Comment by ebocher** [comment]
Exceptions are badly managed by the process. I think we must remove the process api and go to single functions and throw the correct exception for each functions.

**Comment by j3r3m1** [comment]
OK then we will get rid of this problem when we will deal with function implementation if I understand well.

**Comment by ebocher** [comment]
Right

**Comment by ebocher** [comment]
I propose to add a new class DataException that will be used to throw an exception when the process doesn't work as it does.
