### ISSUE TITLE
Warnings when running Geoclimate with CLI

### ISSUE THREAD

**Issue by franetibe** [orbisgis/geoclimate#556]
I use the archive Geoclimate.jar to run Geoclimate with CLI.

The configuration file is below : 

{ "description" :		"Processing OSM data",
  "geoclimatedb" : 	{	"folder"		: "/tmp/osm",
				"name" 			:"geoclimate_db_test;AUTO_SERVER=TRUE",
				"delete" 		:true},
"input" : 		{	"osm"			: ["Pont-de-Veyle"]},
"output" :		{	"folder"		: "/tmp"},
"parameters": 		{	"rsu_indicators"	: {	"indicatorUse": ["LCZ", "TEB", "URBAN_TYPOLOGY"],
								"svfSimplified": true,
								"estimateHeight" : true},
				"grid_indicators"	: {	"x_size": 100,
								"y_size": 100,
								"rowCol": false,
								"output" : "geojson",
								"indicators" :["BUILDING_FRACTION", "BUILDING_HEIGHT", "WATER_FRACTION",
"VEGETATION_FRACTION", "ROAD_FRACTION", "IMPERVIOUS_FRACTION", "LCZ_FRACTION"]}}}

Each time I run Geoclimate.jar, I obtain several warnings at the beginning of the execution : 

fr@0:~/Documents/Geoclimate$ java -jar Geoclimate.jar -f ma_config.json
**WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.**
1 osm areas will be processed
https://nominatim.openstreetmap.org/search?q=Pont-de-Veyle&limit=5&format=geojson&polygon_geojson=1
Executing query... Pont-de-Veyle
Downloading the Nominatim data.
**WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/home/francois/Documents/Espace_geek/Geoclimate/Geoclimate.jar) to field java.util.ArrayList.size
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release**

Then :

Start polygons transformation
Build way polygons
Build outer polygons
Build inner polygons
The way and relation POLYGONS have been built.
Start polygons transformation
Build way polygons
**No keys or values found in the relations. An empty table will be returned.**
The way and relation POLYGONS have been built.
Start lines transformation
**No keys or values found in the relations. An empty table will be returned.**
The way and relation LINES have been built.

And another issue regarding XStream, two times :

All geoindicators have been computed
Extracting the building having no height information and estimate it
Collect building indicators to estimate the height
Start estimating the building height
**Security framework of XStream not initialized, XStream is probably vulnerable.**

Processing urban typology surface fraction calculation
Processing LCZ surface fraction indicators calculation
Geoindicators calculation time: 1.866 s
All geoindicators have been computed
 The LCZ classification is performed 
 The URBAN TYPOLOGY classification is performed 
**Security framework of XStream not initialized, XStream is probably vulnerable.**

The workflow is working and I can open the output files.

**Comment by j3r3m1** [comment]
Good to hear that the workflow is working well. Concerning the warning, I think I also get most of them, it should not be related to your installation. @ebocher @SPalominos is there any way to solve the warnings for now or should we wait the third-party suppliers to solve them in their side ? If so should we let them know about these warnings ?

**Comment by ebocher** [comment]
XStream warning message seems to be easy to fix. See : https://stackoverflow.com/questions/44698296/security-framework-of-xstream-not-initialized-xstream-is-probably-vulnerable
I put this in my todo list.

" No keys or values found in the relations. An empty table will be returned."is a valid message but we can display it only in a debug mode. @j3r3m1  ?

WARNING: An illegal reflective access operation has occurred and other messages  is another issue ;-)

**Comment by j3r3m1** [comment]
> " No keys or values found in the relations. An empty table will be returned."is a valid message but we can display it only in a debug mode. @j3r3m1 ?

OK to show it only in a debug mode

**Comment by ebocher** [comment]
XStream warning message fixed on master

**Comment by ebocher** [comment]
> " No keys or values found in the relations. An empty table will be returned."is a valid message but we can display it only in a debug mode. @j3r3m1 ?
Need some changes on  module https://github.com/orbisgis/orbisanalysis/tree/master/osm

**Comment by ebocher** [comment]
Ok here we are https://github.com/orbisgis/orbisanalysis/pull/86

**Comment by ebocher** [comment]
Fixed
