### ISSUE TITLE
Change Urban Typology name in the code

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#557]
We renamed Urban typology by UTRF (Urban Typology by Random Forest) in the documentation but it is now not consistent anymore with the code (for example in the config file indicatorUse is URBAN_TYPOLOGY. We should update this term.

Note that it will also impact the indicator names (those ending by URB --> UTRF). For now they are still URB in the wiki, need to be updated when done in the code

**Comment by ebocher** [comment]
So you want to rename the indicatorUse variable to  UTRF or the full name Urban_Typology_by_Random_Forest
Note that the output tables must renamed too

**Comment by j3r3m1** [comment]
Yes. I can do that if you want

**Comment by ebocher** [comment]
Do it ;-)
Note you must change it also in the BDTopo worflow

**Comment by j3r3m1** [comment]
When #590 merged, remains the doc to update

**Comment by ebocher** [comment]
Done
