### ISSUE TITLE
Change in wudapt.org structure

### ISSUE THREAD

**Issue by matthiasdemuzere** [orbisgis/geoclimate#563]
Hi, 

Just a quick note. We have been revising the wudapt.org website structure a bit.
Perhaps you could upload the link on the README for LCZ to: https://www.wudapt.org/lcz/lcz-framework/

If you want, we can also include this package on the [tools overview](https://www.wudapt.org/tools-overview/) section. If interested, please feel free to send me info that could be included.

**Comment by j3r3m1** [comment]
Thank you for the information and the proposition.
I have updated the link in #564. 
We are clearly interested to appear in the tool overview section but first we need a bit more time to publish a first version of this work. We will let you know once it is done (hopefully soon).

**Comment by matthiasdemuzere** [comment]
Sure, no worries. Keep us posted and keep up the good work!

**Comment by ebocher** [comment]
Thanks @matthiasdemuzere .
Readme fixed by @j3r3m1
