### ISSUE TITLE
Ground absorption table name usefull to build noise map

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#570]
The ground absorption table  is an input data to build noise map.
The ground absorption table contains an areal geometry and a g column that stored  the acoustic absorption of a ground.
In order to marry geoclimate with other environmental issues like noise or air quality I think we could calculate this layer
@j3r3m1

**Comment by j3r3m1** [comment]
What do you mean by calculate ? The table you tell about only makes link between generic types of ground defined in Geoclimate and physical properties that have to be set to each of these types. It is something a bit different than an input table. It is a parameter table

**Comment by ebocher** [comment]
You are rigth it's a parameter table used to produce a new output table

**Comment by ebocher** [comment]
Maybe it's not relevant to add it in GeoClimate

**Comment by j3r3m1** [comment]
I think that the noise will not affect the climate. Thus I would not add these informations in the input. But the output of noisemodelling could be then related to climate output (anyway outside Geoclimate)
