### ISSUE TITLE
Primary and secondary LCZ type - column name

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#574]
We currently use "LCZ1" and "LCZ2" as column names in the rsu_indicators table.
https://github.com/orbisgis/geoclimate/blob/a1d06d424553bbb21e455dee2a85684ca2705086/geoindicators/src/main/groovy/org/orbisgis/orbisprocess/geoclimate/geoindicators/TypologyClassification.groovy#L367

 This is quite confusing with the LCZ type 1 and LCZ type 2. I propose to rename to "LCZ_PRIMARY" and "LCZ_SECONDARY" what do you think ? Any other ideas for the names ?

@ebocher @franetibe @ELSW56 @gpetit

**Comment by ebocher** [comment]
I'm in favour of "LCZ_PRIMARY" and "LCZ_SECONDARY" .
Ready for all ?

**Comment by ebocher** [comment]
Fixed
