### ISSUE TITLE
Error running Geoclimate with BDTOPO V2.2 and Groovy Console [Linux]

### ISSUE THREAD

**Issue by franetibe** [orbisgis/geoclimate#583]
I have downloaded the last version of Geoclimate.jar today.

I run Geoclimate with BDTOPO V2.2 on Ubuntu 18.04 using this configuration file :

```json
{
    "description": "Processing BD Topo v2 data",
    "geoclimatedb": {
        "folder": "/tmp/bd_topo_v2",
        "name": "geoclimate_db_test;AUTO_SERVER=TRUE",
        "delete": true
    },
    "input": {"bdtopo_v2":	{
        "folder": {"path": "/home/mydirectory/Geoclimate/BD_TOPO_v2/"}
				}
    },
    "output": {
        "folder": "/tmp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "URBAN_TYPOLOGY"
            ],
            "svfSimplified": true
        }
    }
}
```

I use the Groovy Console using this script : 

```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate

def process = Geoclimate.BDTOPO_V2.workflow
process.execute(configurationFile:'/home/mydirectory/Geoclimate/my_first_config_file_bdtopov2.json')
```

I obtain the following error :

[Thread-3] ERROR org.orbisgis.orbisprocess.geoclimate.bdtopo_v2.BDTopo_V2_Utils - The input folder must contains a file named iris_ge
[Thread-3] ERROR org.orbisgis.orbisprocess.geoclimate.bdtopo_v2.BDTopo_V2_Utils - Cannot load the files from the folder [path:/home/mydirectory/Geoclimate/BD_TOPO_v2/]
Result: false

However, everything goes well when I run Geoclimate x BDTOPO v2.2 with the CLI method.

Does anyone has an idea ?

Thanks !

**Comment by j3r3m1** [comment]
Is there the iris_ge file in your data directory (/home/mydirectory/Geoclimate/BD_TOPO_v2/) ? It seems the problem comes from that.

**Comment by ebocher** [comment]
Since https://github.com/orbisgis/geoclimate/issues/572 the IRIS_GE file is not used anymore. You must used the commune file available with the BDTopo db .My apologies, I should have highlighted this change

**Comment by franetibe** [comment]
Before this test, I have deleted the iris_ge files from my directory, since @ebocher has mentioned that iris_ge are not used anymore.

I have replaced iris_ge files by commune files.

It works with the CLI method, and I obtain an error with the Groovy Console method.

**Comment by ebocher** [comment]
ok.
Try to remove the .groovy folder in your home to update the dependencies

**Comment by j3r3m1** [comment]
> Before this test, I have deleted the iris_ge files from my directory, since @ebocher has mentioned that iris_ge are not used anymore.
> 
> I have replaced iris_ge files by commune files.
> 
> It works with the CLI method, and I obtain an error with the Groovy Console method.

Ideally, instead of removing / replacing files, to be sure you have all the right files in the folder, I recommend you to get the last version of the entire Geoclimate repo using git pull.

**Comment by franetibe** [comment]
I have deleted the .groovy folder in /home.

This action solve the problem, thanks ! I close the issue.
