### ISSUE TITLE
Frequently Asked Questions section

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#597]
We may set a F.A.Q. in the wiki to answer the main problems encountered by users. For now:
- proxy: see #317 for Groovy and #595 for command line
- memory: see #595 for command line

**Comment by 4estone** [comment]
Could you please add information about processing OSM data with a bounding box?

**Comment by j3r3m1** [comment]
> Could you please add information about processing OSM data with a bounding box?

I have created a new issue to solve that, I do not think it should be in the FAQ.

**Comment by franetibe** [comment]
I agree, I propose to create a FAQ section below the Tutorial sections

What do you think ?

**Comment by ebocher** [comment]
Done https://github.com/orbisgis/geoclimate/wiki/Frequently-Asked-Questions
and a tutorial ins under the pipe for the bbox setting by @franetibe
