### ISSUE TITLE
Problems with LCZ classification

### ISSUE THREAD

**Issue by juldd** [orbisgis/geoclimate#606]
Hi,
I have a problem with the buildings in the vegetation LCZ. Another problem concerns the class E of the LCZ. In this case we can get class E for the road but not for the stone quarry.
![Buidings_in_vegetation](https://user-images.githubusercontent.com/79527022/125296683-d4992200-e326-11eb-9aa4-cf969a59de67.png)
Can we fix it?
Thank you for your help :)

**Comment by ebocher** [comment]
Thanks to report an issue.

> I have a problem with the buildings in the vegetation LCZ

Can you specify the type of problem you have?

> Another problem concerns the class E of the LCZ. In this case we can get class E for the road but not for the stone quarry.

What type of data source do you use? OSM, BDTopo ?
Note that in both input the quality of classification depends on the landcover types. Can you check if the " stone quarry" is well identified in your input data ?

**Comment by juldd** [comment]
1. The class B of vegetation (normally no buildings) can contain the buildings with geoclimate classification. It is especially true for the case of the last ranges of buildings in an urban zone.

**Comment by j3r3m1** [comment]
>     1. The class B of vegetation (normally no buildings) can contain the buildings with geoclimate classification. It is especially true for the case of the last ranges of buildings in an urban zone.

This is actually an expected behavior. This is our interpretation of the Stewart and Oke definition: below 10% of building fraction, the land is a rural type (see enclosed):
![image](https://user-images.githubusercontent.com/13120405/125318481-2b5c2700-e33a-11eb-9cb7-98f1709a3f6a.png)

**Comment by ebocher** [comment]
Close it ?

**Comment by juldd** [comment]
Thanks for your help, it's ok for me.
Another problem it's lcz E but I try fix it with Pleiades. 
best regards

**Comment by j3r3m1** [comment]
> Thanks for your help, it's ok for me.
> Another problem it's lcz E but I try fix it with Pleiades.
> best regards

Not sure I got what was the problem you faced.
Class E is set for Reference Spatial Units having the sum of impervious and road fractions > 0.1 AND > water AND > VEGETATION.
For now we do not consider natural impervious lands such as stones (should be done in the future - cf #339). 

Note that it could be helpful for us if you check that the expected stones area are identified as stones in OSM (using the 'query features' icon in https://www.openstreetmap.org/)
![image](https://user-images.githubusercontent.com/13120405/125452544-e943aefe-19ba-43ab-abc1-71fde63dfa2e.png)
