### ISSUE TITLE
Change in version 1.0.0 SNAPSHOT + using geoclimate for TEB

### ISSUE THREAD

**Issue by julienpergaud** [orbisgis/geoclimate#607]
Hello,

From today, the version snapshot 1.0.0 has changed and i have had to change the config file and add communes to BDTOPO directory.
So, why you don't change number version to keep process working on specific version?
Second poitn concerns the use of geoclimate for TEB inputs.
Do you have any config fille for this?
We are working with grid_indicators but we don't have any aspect_ratio in grid output which is needed for TEB-MESONH simulation.
Thanks in advance for your answer.

Julien

**Comment by julienpergaud** [comment]
Thk you so much Erwan for your answer.
Ok for geoclimate modifications.
Concerning TEB, whe you explain that the TEB indicators are computed at the RSU scale, does it imply that is not possible to have this on a grid?

**Comment by ebocher** [comment]
> Concerning TEB, whe you explain that the TEB indicators are computed at the RSU scale, does it imply that is not possible to have this on a grid?

Only few indicators are aggregated at grid scale ( here you have the list https://github.com/orbisgis/geoclimate/wiki/Processing-steps).
It is possible to aggregate other indicators but it needs some coding tasks in GeoClimate. Can you list the indicators you want and we can add it in a todo list for the future

**Comment by j3r3m1** [comment]
> Concerning TEB, whe you explain that the TEB indicators are computed at the RSU scale, does it imply that is not possible to have this on a grid?

Actually, we will have all needed TEB indicators at the grid scale in the future since the Topographical Spatial Units (TSU) are just a type of Reference Spatial Unit (RSU) - cf #555. Soon we will have the choice to directly calculate all indicators using as RSU a grid of squares.

**Comment by ebocher** [comment]
Done
