### ISSUE TITLE
Processing BD Topo V2 on windows error

### ISSUE THREAD

**Issue by 4estone** [orbisgis/geoclimate#612]
I'm trying processing BD Topo V2 on windows and I get this error:
`A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:bdtopo_v2_2". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-200]
Cannot load the local H2GIS database to run Geoclimate
Cannot execute the BDTOPO_V2.2 workflow`

My json file looks like this:

> {
    "description": "Processing BD Topo v2 data",
    "input": {"bdtopo_v2":	{
        "folder": {"path": "C:/temp/LCZ/orbisgis/BDTopoV2/"}
				}
    },
    "output": {
        "folder": "C:/temp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "URBAN_TYPOLOGY"
            ],
            "svfSimplified": true,
            "estimateHeight": true
        }
    }
}

May-be need more option on conf file for running on windows?

**Comment by simogeo** [comment]
I got the same error on Ubuntu. It works well with OSM workflow

**Comment by ebocher** [comment]
@simogeo 
Can you please share your config file ?

**Comment by simogeo** [comment]
Just a copy-paste and adaptation of the given sample config file : 

```json
{
    "description": "Processing BD Topo v2 data",
    "input": {
		"bdtopo_v2":	{
			"folder": {
				"path": "/home/simon/Bureau/geoclimate/BDTOPOv2/"			
			}
		}
    },
    "output": {
        "folder": "/tmp/BDTOPOresult/"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "UTRF"
            ],
            "svfSimplified": true
        },
        "grid_indicators": {
            "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :[
                 "BUILDING_FRACTION", 
                 "BUILDING_HEIGHT", 
                 "WATER_FRACTION",
                 "VEGETATION_FRACTION", 
                 "ROAD_FRACTION", 
                 "IMPERVIOUS_FRACTION", 
                 "LCZ_FRACTION"
             ]
         }
    }
}
```

**Comment by ebocher** [comment]
Thanks I will check this config file.

**Comment by ebocher** [comment]
I have added a unit test on GeoClimate to test your config file : https://github.com/orbisgis/geoclimate/pull/613
It runs the following config file : 

```json
{
    "description": "Example of configuration file to run the grid indicators",
    "geoclimatedb": {
        "folder": "/home/geoclimate2/geoclimate/bdtopo_v2/./target/bdtopo_withoutzone",
        "name": "geoclimate_chain_db;AUTO_SERVER=TRUE",
        "delete": false
    },
    "input": {
        "bdtopo_v2": {
            "folder": {
                "path": "/home/geoclimate2/geoclimate/bdtopo_v2/target/test-classes/org/orbisgis/geoclimate/bdtopo_v2/sample_12174"
            }
        }
    },
    "output": {
        "folder": {
            "path": "./target/bdtopo_withoutzone",
            "tables": [
                "grid_indicators"
            ]
        }
    },
    "parameters": {
        "distance": 0,
        "grid_indicators": {
            "x_size": 1000,
            "y_size": 1000,
            "indicators": [
                "WATER_FRACTION"
            ]
        },
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "UTRF",
                "TEB"
            ],
            "svfSimplified": true
        }
    }
}
```

where sample_12174 contains the data : https://github.com/orbisgis/geoclimate/tree/master/bdtopo_v2/src/test/resources/org/orbisgis/geoclimate/bdtopo_v2/sample_12174

I'm not able to reproduce the bug you mention.

Can you please explain how you are running GeoClimate  ; Terminal, Command Line Interface, Groovy Console.

**Comment by simogeo** [comment]
I run geoclimate from a terminal 

`java -jar geoclimate-1.0.0.jar -f my_first_config_file_bdtopov2.json -w BDTOPO_V2.2`


And I get the following result : 

> Unable to create the DataSource.
> Un chemin de fichier implicitement relatif au répertoire de travail actuel n'est pas autorisé dans l'URL de la base de données "jdbc:h2:bdtopo_v2_2". Utilisez un chemin absolu, ~ /nom, ./nom ou le paramètre baseDir à la place.
A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:bdtopo_v2_2". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-200]
Cannot load the local H2GIS database to run Geoclimate


runing an elder version of geoclimate, I get the following error : 

`java -jar Geoclimate.jar -f my_first_config_file_bdtopov2.json -w BDTOPO_V2.2`

> Please set a valid input data provider
> The BDTOPO_V2.2 workflow has been successfully executed


All shapefiles, copied from [given source](https://github.com/orbisgis/geoclimate/tree/master/bdtopo_v2/src/test/resources/org/orbisgis/geoclimate/bdtopo_v2/sample_12174), are of course located into /home/simon/Bureau/geoclimate/BDTOPOv2/

My OS : Ubuntu 20.04 

java -version returns : 

> openjdk version "1.8.0_292"
> OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
> OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by bbrangeo** [comment]
Bonjour,

J'ai la même erreur.

**Comment by ebocher** [comment]
You can not set in the path of the database but only a folder name here bdtopo_v2_2. You must set something like that : jdbc:h2:/tmp/bdtopo_v2_2
where bdtopo_v2_2 contains the whole shapefiles.
This is that the message saids "Use an absolute path, ~/name, ./name, or the baseDir setting instead."
This limitation is due to the H2 database used by H2GIS and GeoClimate to store and process data

**Comment by bbrangeo** [comment]
I use my conf :

`       "input": {"bdtopo_v2":  {
           "folder": {"path": "jdbc:h2:~/27_GEOCLIMATE/bdtopo_v2_2"}
                   }
},`

With my directory bdtopo_v2_2 : 

`ls bdtopo_v2_2` ==>

`AIRE_TRIAGE.CPG              GARE.SHP                         PAI_RELIGIEUX.DBF             ROUTE_PRIMAIRE.PRJ
AIRE_TRIAGE.DBF              GARE.SHX                         PAI_RELIGIEUX.PRJ             ROUTE_PRIMAIRE.SHP
AIRE_TRIAGE.PRJ              HYDRONYME.CPG                    PAI_RELIGIEUX.SHP             ROUTE_PRIMAIRE.SHX
AIRE_TRIAGE.SHP              HYDRONYME.DBF                    PAI_RELIGIEUX.SHX             ROUTE.PRJ
AIRE_TRIAGE.SHX              HYDRONYME.PRJ                    PAI_SANTE.CPG                 ROUTE_SECONDAIRE.CPG
BATI_INDIFFERENCIE.CPG       HYDRONYME.SHP                    PAI_SANTE.DBF                 ROUTE_SECONDAIRE.DBF
BATI_INDIFFERENCIE.DBF       HYDRONYME.SHX                    PAI_SANTE.PRJ                 ROUTE_SECONDAIRE.PRJ
BATI_INDIFFERENCIE.PRJ       LIEU_DIT_HABITE.CPG              PAI_SANTE.SHP                 ROUTE_SECONDAIRE.SHP
BATI_INDIFFERENCIE.SHP       ....`


I run :
`java -jar Geoclimate.jar -w BDTOPO_V2.2 -f my_first_config_file_bdtopov2.json`

Same error :
`Unable to create the DataSource.
A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:bdtopo_v2_2". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-200]
Cannot load the local H2GIS database to run Geoclimate`

**Comment by ebocher** [comment]
Thanks for this feedback I will test it when I will be back.  I will be OoO until end of August.

**Comment by ebocher** [comment]
We need a Windows OS to run a test about this issue. @ELSW56  is it ready for you ?

**Comment by ebocher** [comment]
Ok I found it. Thanks to @j3r3m1 that give me the way ;-)

**Comment by ebocher** [comment]
Fixed
