### ISSUE TITLE
OSM

### ISSUE THREAD

**Issue by bbrangeo** [orbisgis/geoclimate#614]
Bonjour,

Je souhaite tester votre outil. J'ai suivi le WIKI pour OSM, cependant j'ai un message d'erreur :

`Cannot execute the query.
Connected as: 1603108662
Current time: 2021-07-20T16:08:38Z
Rate limit: 2
2 slots available now.
Currently running queries (pid, space limit, time limit, start time):

Cannot extract the OSM data for the query [maxsize:1073741824][bbox:46.182835200716,-1.1481302976608,46.185598425454,-1.1438870429993];
((
	node["building"];
	node["railway"];
	node["amenity"];
	node["leisure"];
	node["highway"];
	node["natural"];
	node["landuse"];
	node["landcover"];
	node["vegetation"];
	node["waterway"];
	way["building"];
	way["railway"];
	way["amenity"];
	way["leisure"];
	way["highway"];
	way["natural"];
	way["landuse"];
	way["landcover"];
	way["vegetation"];
	way["waterway"];
	relation["building"];
	relation["railway"];
	relation["amenity"];
	relation["leisure"];
	relation["highway"];
	relation["natural"];
	relation["landuse"];
	relation["landcover"];
	relation["vegetation"];
	relation["waterway"];
);
>;);
out;`

Pouvez-vous m'éclairer ?

Merci d'avance.
Boris

**Comment by bbrangeo** [comment]
C'est bon cela refonctionne.

**Comment by j3r3m1** [comment]
The problem probably comes from the OSM API having a time out, that's why it worked when you tried again.
