### ISSUE TITLE
Error running Geoclimate with BDTOPO V2.2

### ISSUE THREAD

**Issue by bbrangeo** [orbisgis/geoclimate#617]
Bonjour,

J'ai une erreur avec BDTOPO V2.2 :

`The process has been stopped since the table BATI_INDIFFERENCIE has a no SRID
Cannot import preprocess.
Number of areas processed 1 on 1
The BDTOPO_V2.2 workflow has been successfully executed`

Quelqu'un peu m'aider ?

J'utilise BDTOPO_2-2_TOUSTHEMES_SHP_LAMB93_D017_2018-09-25.7z.001

<img width="438" alt="Capture d’écran 2021-08-25 à 09 58 11" src="https://user-images.githubusercontent.com/769760/130750915-1eb37e6e-9e9c-4799-8ee0-7851d4b7ce00.png">

**Comment by ebocher** [comment]
Please test the first release version here https://github.com/orbisgis/geoclimate/releases/tag/0.0.1.
It should fix your issue.

**Comment by bbrangeo** [comment]
I tested. 

Release ok for bdtopV2 and OSM. 👍 

Thank you.
