### ISSUE TITLE
JOSS review: broken links in docs

### ISSUE THREAD

**Issue by arbennett** [orbisgis/geoclimate#623]
All of the links on the [example workflow ](https://github.com/orbisgis/geoclimate/blob/v1.0.0-RC1/docs/for_users/execution_examples/run_osm.md) are giving me 404 errors. For example : https://github.com/orbisgis/geoclimate/blob/master/processingchain/src/test/resources/org/orbisgis/orbisprocess/geoclimate/processingchain/config/osm_workflow_envelope_folderoutput.json

**Comment by ebocher** [comment]
Thanks for the comment but this link is related to an old version. You must used now the wiki doc and the last release 0.0.1
