### ISSUE TITLE
Error with the OSM API

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#630]
Sometimes when we run the OSM workflow, we get the following error:
'ERROR org.orbisgis.geoclimate.osm.OSM - Cannot execute the overpass query [maxsize:1073741824][bbox:46.25733,4.870033,46.26997,4.905224];'

It is quite complicated to understand where does the error comes from.

- The informations displayed are respectively the maxsize allowed and the current bbox queried but not the actual size of the data corresponding to this bbox.
- Quite often it seems we are temporarily "blacklisted" from the OSM (or a timeout since too many persons asking for data?) but we do not get informed about that.

If possible it would be nice to log at least if the error comes from the 1st or the 2nd problem.

**Comment by ebocher** [comment]
To solve this issue , we must

- [ ] Improve OSMTools module to check the overpass log error
- [ ] Throw a better exception when OSM data cannot be extracted

**Comment by simogeo** [comment]
I also faced this issue.

Some tracks to investigate : 
* timeout : https://wiki.openstreetmap.org/wiki/Overpass_API#Resource_management_options_.28osm-script.29
* Overpass API status page : http://overpass-api.de/api/status - [source](https://github.com/tyrasd/overpass-turbo/issues/340)

See also : 
* https://github.com/drolbr/Overpass-API/issues/351
* https://github.com/mvexel/overpass-api-python-wrapper/issues/88
* https://wiki.openstreetmap.org/wiki/Overpass_API/status

**Comment by ebocher** [comment]
Hi @simogeo ,
Thanks for the comments and resources.
GeoClimate doesn't used any timeout when the Overpass query is send.
So I suggest to set a defautlt timeout and offer a way to set it from the input parameters. Something like that

```
"input" : [
                        "osm" : ["Pont-de-Veyle"],
                        "timeout" : 900,
                        "maxsize":1073741824
]

```

moreover, it seems that the name osm is not appropriate to define the values of the table which are names or bboxes

what about rename it to filters 

```
"input" : [
                        "filters" : ["Pont-de-Veyle"],
                        "timeout" : 900,
                        "maxsize":1073741824
]
```

@j3r3m1 @ELSW56

**Comment by j3r3m1** [comment]
is filter may be replaced by something like "location" ?

**Comment by ebocher** [comment]
location  = vendu ;-)

**Comment by ebocher** [comment]
It seems fixed.
