### ISSUE TITLE
Error with accessing jarfile- Windows

### ISSUE THREAD

**Issue by lheidger** [orbisgis/geoclimate#636]
Hello,

I am having trouble accessing the jar file. The error message is as follows:

C:\Users\lily\OneDrive\Documents\Geoclimate>java -jar Geoclimate.jar -h
Error: Unable to access jarfile Geoclimate.jar

I have tried updating java and downloading the jar file multiple times. Any suggestions are appreciated.

**Comment by j3r3m1** [comment]
Hi,
I get this error only when I do not have any file named "Geoclimate.jar". It may come from the fact that on Windows (I do not know if it is the case for all versions) the extension ".jar" is automatically added to uour file name. Try to get rid of the ".jar" at the end of the file and test it again with the same command (with the ".jar")

**Comment by j3r3m1** [comment]
@lheidger did it solve your problem ?
