### ISSUE TITLE
Deploy geoclimate on maven with github actions

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#640]
Deploy GeoClimate on Maven Central using  github actions.

**Comment by j3r3m1** [comment]
Would be nice to have the snapshot version for testing.

**Comment by j3r3m1** [comment]
@ebocher @SPalominos

**Comment by SPalominos** [comment]
Geoclimate is available on Sonatype Nuexus (see [here](https://oss.sonatype.org/#nexus-search;quick~geoclimate))

**Comment by j3r3m1** [comment]
My question was not clear but I think we need to have the snapshot version as a jar with all dependencies as the [0.0.1 version](https://github.com/orbisgis/geoclimate/releases/download/0.0.1/geoclimate-0.0.1.jar). It should then be usable as described here:
https://github.com/orbisgis/geoclimate/wiki/Default-case-with-OSM-for-linux#command-line-interface

**Comment by ebocher** [comment]
A new deployment is done after each PR, available here https://nightly.link/orbisgis/geoclimate/workflows/CI_snapshot/master/geoclimate-0.0.2-SNAPSHOT.zip
Thanks to @SPalominos 
We will change it asap to return a jar and not a zip file
