### ISSUE TITLE
Unsupported file format

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#641]
When starting calculations using the BDTopo V2, I obtain an error due to the file extension of my shapefile.
> Unsupported file format.
Supported formats are : [csv,dbf,dbf.gz,geojson,geojson.gz,gpx,gpx.gz,osm,osm.gz,osm.bz2,shp,tsv,tsv.gz,asc,asc.gz].
Cannot import the file : /tmp/myCity/COMMUNE.SHP
Unable to find table COMMUNE_TMP

If I modify the extension to lower case it solves the problem but I wonder if this behavior expected ?

**Comment by ebocher** [comment]
Fixed here https://github.com/orbisgis/geoclimate/pull/647
