### ISSUE TITLE
Using my own building height vector data in the Geoclimate model.

### ISSUE THREAD

**Issue by Fengqi-CC** [orbisgis/geoclimate#642]
Hello,
Recently I am focusing on local climate zone classification in Beijing,  and I found although I can get LCZ results, there is no specific building height in the default data source from Openstreet. Therefore, I would like to use my own building height vector data in the Geoclimate model.

Unfortunately, I did not find any instructions about this issue. And I wonder if I can get any detailed instructions to connect my vector-based dataset.  Thank you in advance!

**Comment by ebocher** [comment]
This ticket has been inactive since several months so we are closing it.
