### ISSUE TITLE
SQL error when processing bd-topo

### ISSUE THREAD

**Issue by 4estone** [orbisgis/geoclimate#643]
Hello,
I got this error when processing bd-topo data:
```
Formating the BDTOPO data
Unable to execute the Sql command '
CREATE TABLE BUILD_ZONE_MATRIX__45164a96_4e51_47c9_968a_c4ca5fe3f294 (ID_BUILD integer primary key, ID_ZONE varchar) AS SELECT * FROM BUILD_WITHIN_ZONE__eb2c4619_0837_49d1_b152_19d34430c8f9 UNION SELECT * FROM BUILD_OUTER_ZONE_MATRIX__8e14db8e_4a6f_40bd_824a_4ecba881fc6b'.
Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.BUILD_ZONE_MATRIX__45164A96_4E51_47C9_968A_C4CA5FE3F294(ID_BUILD) ( /* key:1 */ 1, '67212')"; SQL statement:

CREATE TABLE BUILD_ZONE_MATRIX__45164a96_4e51_47c9_968a_c4ca5fe3f294 (ID_BUILD integer primary key, ID_ZONE varchar) AS SELECT * FROM BUILD_WITHIN_ZONE__eb2c4619_0837_49d1_b152_19d34430c8f9 UNION SELECT * FROM BUILD_OUTER_ZONE_MATRIX__8e14db8e_4a6f_40bd_824a_4ecba881fc6b [23505-200]
Cannot format the BD Topo data
Cannot format data and compute statistics.
The BDTOPO_V2.2 workflow has been successfully executed
```
I'm processing a full french département (Bas-Rhin), and I suppose that error occure on commune INSEE = 67212. I look at this commune data and I dont see anything special ...

**Comment by ebocher** [comment]
Thanks I will check

**Comment by ebocher** [comment]
The current GeoClimate version 0.0.2-SNAPSHOTt is able  to process the commune (CODE_INSEE = 67212).
Here the LCZ on this area.
![67212](https://user-images.githubusercontent.com/1820572/143255296-cf472cae-0099-4f90-9ec9-4aa3a74d62a8.png)

Input data from : https://www.opendatarchives.fr/

**Comment by 4estone** [comment]
Thanks. 
But where is Geoclimate 0.0.2 release? There's only 0.0.1 on releases page...

**Comment by ebocher** [comment]
Hi,
The 0.0.2 is not released it. There is snapshot version compiled after each changes here  : 
https://nightly.link/orbisgis/geoclimate/workflows/CI_snapshot/master/geoclimate-0.0.2-SNAPSHOT.zip
We are working on it...
