### ISSUE TITLE
Sea-land mask failed

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#646]
I have tried to apply GeoClimate 0.0.1 for a bounding box in Sweden which contains some water (in blue) and some land (in red) and it failed to identify the land in the entire east region. 
![image](https://user-images.githubusercontent.com/13120405/141256746-1b6285ec-04e2-4f40-9957-97d54de21a22.png)

The coordinates of the bounding box are [57.634008, 11.774940, 57.761517, 12.099724] (a quite large area for a test...)

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
It seems. It rocks now !

![geoclimate_sea](https://user-images.githubusercontent.com/1820572/144073644-32d2ffc3-8996-4392-850a-26be48c53678.png)
