### ISSUE TITLE
Error with buidling height value

### ISSUE THREAD

**Issue by Gwen22200** [orbisgis/geoclimate#649]
Hello,

I see a difference between osm building height and thz result in qgis for the layer buidling computed by geoclimate jar.

osm : 
![image](https://user-images.githubusercontent.com/20315388/143567271-ca26dbdb-9bb8-4172-a1b6-7ee24501a43b.png)
Level : 3

Qgis result : 
![image](https://user-images.githubusercontent.com/20315388/143567330-87b615ca-9261-4649-9d70-aff2d394deaf.png)
NB_LEV : 7 

Is it a normal behavior ?

Thanks,
Gwendal

**Comment by ebocher** [comment]
OSM URL for this data
https://www.openstreetmap.org/way/266225046

**Comment by j3r3m1** [comment]
Got the same values, and this is a building identified as having no missing building height (it means its height is not estimated using the RF model). I investigate where does the issue come from.

**Comment by ebocher** [comment]
We must update the height estimation to integrate the building:levels and roof:levels values

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
Fixed
