### ISSUE TITLE
BDTOPO V3

### ISSUE THREAD

**Issue by ML426** [orbisgis/geoclimate#672]
Is BDTOPO v3 compatible with Geoclimate?
Do I need to make any changes before using it?
Best

**Comment by j3r3m1** [comment]
Hi, not now right but probably in the next months we should have a workflow dedicated to bdtopo v3.

**Comment by ML426** [comment]
Thx, but how can i do to have BDTOPO V2 ?
I tried last time but only V3 is available.

**Comment by ML426** [comment]
Thank you, 
but how can i do to have BDTOPO V2 ?
I tried last time but only V3 is available.
