### ISSUE TITLE
[feature] delete temporary files by default after processing

### ISSUE THREAD

**Issue by simogeo** [orbisgis/geoclimate#678]
Would be nice to delete temporary files by default after processing.

At least having the ability to delete them or not based on a new configuration var from json file.

**Comment by ebocher** [comment]
What are the temporary files you want to delete ? Do you have a list in mind ?

**Comment by simogeo** [comment]
I'm taking about all *.db files in /tmp folder, such as :

```
bdtopo_v2_2dbe5a603_d784_49e4_a566_301c0ecf9fd2.mv.db
osm_bd97a215_0f80_4206_804d_11a86389195a.mv.db
...
```

This is not a priority of course, but could be nice because they can get huge

**Comment by ebocher** [comment]
This is the H2GIS database used by GeoClimate. The files must be deleted by default, unless the user sets the following parameters

```
"description" :"Example of configuration file to run the OSM workflow and store the result in a folder",
                "geoclimatedb" : [
                        "folder" : "/tmp",
                        "name" : "geoclimate_test_db",
                        "delete" :false
                ],
                "input" : [
                        "osm" : ["Pont-de-Veyle"]],
```

**Comment by simogeo** [comment]
I do not set any "geoclimatedb" parameter but they are not deleted
