### ISSUE TITLE
Coastline bug

### ISSUE THREAD

**Issue by wurtzj** [orbisgis/geoclimate#685]
Hello everybody,

Looking to Geoclimate outputs from OSM (not v0.0.2 as I cannot run new version though) I found odd estimation of sea shores.
In particular, there is no island in the boxes with such error. You will find attached an example of such bug. Purple is for 0% Water fraction and yellow is 100%
![WATER_FRACTION_BUG_NORMANDIE](https://user-images.githubusercontent.com/99657196/155978830-0fd8f853-83b2-4c17-abee-2fef6c2c19cf.png)

Thank you and best regards,

**Comment by ebocher** [comment]
Please share the config file, so we will be able to test it with the current version 0.0.2.
Note : The 0.0.2 introduces several changes so  it will be better to find a way to run it on your config system. We can't put backwards fixed on releases

**Comment by ebocher** [comment]
@wurtzj 
Can you share the config file for this area ?

**Comment by ebocher** [comment]
This issue has been fixed with the PR #731
See this example on Le Havre city

![fix_water_normandie](https://user-images.githubusercontent.com/1820572/166957328-38110340-5e72-44c4-aa28-a1381b3a4132.png)
