### ISSUE TITLE
processing chain when inputs having same name are not the same

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#69]
A same IProcess (scalesRelations) is used several times in the mapper called "CreateScalesOfAnalysis" but this process does not used the same input names each time for the input called columnIdUp (sometimes it refers to id_block, sometimes id_rsu). @SPalominos @ebocher How could we manage this problem (use a same input twice but without the same value...) ?

**Comment by ebocher** [comment]
fixed ?

**Comment by j3r3m1** [comment]
This problem was only encountered with the processing chain MAPPER, not processing chain with the IProcess format. So yes fixed
