### ISSUE TITLE
undefined_fraction

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#693]
As discussed in #692, it might be very useful for users to have the "undefined_fraction" since most of RSU do not have the sum of "all layers" fractions equal to 1 and that the superimposition method leads to a great number of fractions that could be quite easily forgotten by the user and thus lead to mistake when trying to calculate the "undefined fraction" by himself.

**Comment by j3r3m1** [comment]
As adviced by @simogeo: 
> I really think this should be clearer in the doc ! I mean, for each classification (URB/LCZ or no classification) explicitly say user that : 
```
A_FRACTION + B_FRACTION + C_FRACTION + [XXX]_FRACTION + UNDEFINED_FRACTION = 1
```

**Comment by ebocher** [comment]
Fixed thanks @j3r3m1
