### ISSUE TITLE
Problem solved but not identified

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#70]
The compilation of the netCompacity branch was tough. It did not work directly. Finally, regarding the modifications I have made for making it work, two assumptions, both a bit strange:
- either the problem came from the order of the test regarding the process order in the process file. The order was not conserved which would make the tests failed...
- the string that defined the IProcess (at the beginning of each IProcess) was the same for holeAreaDensity and netCompacity, that could affect the good working of the code...

**Comment by ebocher** [comment]
Fixed ?

**Comment by j3r3m1** [comment]
Yes but I still do not know how it was fixed.
