### ISSUE TITLE
Urban Weather Generator indicators

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#706]
Compute the indicators requiered by the Urban Weather Generator model
See : https://github.com/ladybug-tools/uwg

The following indicators are aggregated onto a regular grid.

- [x] bldheight – Urban building height in meters.
- > Refer to the column  AVG_HEIGHT_ROOF or AVG_HEIGHT_ROOF_AREA_WEIGHTED. It might be better to use the area weighted version if we refer to https://urbanmicroclimate.scripts.mit.edu/uwg_parameters.php#urbanArea

- [x] blddensity – Building footprint density as fraction of urban area.
- > Refer to the column BUILDING_FRACTION

- [x] vertohor – Vertical-to-horizontal urban area ratio.
- > Refer to the column FREE_EXTERNAL_FACADE_DENSITY

- [x] grasscover – Fraction of urban ground covered in grass only.
- >  Refer to the column LOW_VEGETATION_FRACTION

- [x] treecover – Fraction of urban ground covered in trees.
- > Refer to the column HIGH_VEGETATION_FRACTION

Pseudo workflow configuration 
```
 "parameters": [
                "rsu_indicators":[
                        "indicatorUse": ["LCZ"]
                ],
                "grid_indicators": [
                        "x_size": 100,
                        "y_size": 100,
                        "indicators": ["BUILDING_FRACTION","BUILDING_HEIGHT","BUILDING_HEIGHT_WEIGHTED", "BUILDING_POP",
                                       "BUILDING_TYPE_FRACTION","WATER_FRACTION","VEGETATION_FRACTION",
                                       "ROAD_FRACTION", "IMPERVIOUS_FRACTION", "LCZ_FRACTION", "LCZ_PRIMARY",
                        "FREE_EXTERNAL_FACADE_DENSITY"]
                ]
```

**Comment by j3r3m1** [comment]
It weems that the sum of all these indicators should be equal to 1, thus it means:
- if trees are above grass, we should make a choice between tree and grass -> it seems tree more appripriate
- the UWG user will have to fill the 1-all_fractions using its own hands. We simplify the task since the undefined_fraction is now calculated.

**Comment by j3r3m1** [comment]
> * if trees are above grass, we should make a choice between tree and grass -> it seems tree more appripriate

It is actually the case for any superimposition. For now the choice is to use the default priority order:
https://github.com/orbisgis/geoclimate/blob/5ce6e0f8cefe270c17ca961ff3bf1998b7302635/geoindicators/src/main/groovy/org/orbisgis/geoclimate/geoindicators/WorkflowGeoIndicators.groovy#L1960

**Comment by ebocher** [comment]
Here some results for Orange, Vaucluse, town

![visualization](https://user-images.githubusercontent.com/1820572/159570700-b9064043-8280-4730-8323-0f26e54c8892.png)

**Comment by j3r3m1** [comment]
Solved but skeptical about UWG results
