### ISSUE TITLE
WorldPop OGC WCS endpoint

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#718]
It seems that the WorldPop WCS service is not available anymore.

See : https://ogc.worldpop.org/geoserver/ows?

This is a good solution to retrieve raster data based on an envelope which is not possible with the rest api of worldpop.

https://wopr.worldpop.org/api/v1.0/data

We need to talk to the WorldPop community to know if the service is definitely removed.

WorldPop is a very nice input for GeoClimate to estimate population exposure.

@bondarenkom @edarin

**Comment by bondarenkom** [comment]
Hi @ebocher 
Our server was restarted during updates and OGC service did not start properly. Thank you for highlighting this, I have just re-started the services and it is working as expected.
Please let me know if you get any issues.

**Comment by ebocher** [comment]
Hi @bondarenkom 
Thanks a lot.
We will send to you some results in few days about counting people by Local Climate Zones.

**Comment by bondarenkom** [comment]
Hi @ebocher 
Just to let you know that if you are interested in WorldPop global population 2000-2020 data and you would like to get tile service for this, I would recoment to check ArcGIS livingatlas https://livingatlas.arcgis.com/en/browse/?q=worldpop#d=3&q=worldpop 
Our data was published there and openlly avalible as Imagery Layer service.  It was published 1km but very soon we are going to publish 100m as well.  Also, you can read a blog about WorldPop data on ArcGIS livingatlas
https://www.esri.com/arcgis-blog/products/arcgis-pro/announcements/a-first-glimpse-into-the-future-of-population-data/
These Imagery Layer services on ArcGIS  is a good source for WorldPop data.

**Comment by ebocher** [comment]
By the way, I have another question. 
If I'm not wrong the ppp layers from the OGC service provides the unconstrained grid population. As a result, it is possible to find inhabitants in areas without any habitation such as parks.
Is the "top-dow constrained" grid available somewhere ?

**Comment by ebocher** [comment]
Hi @bondarenkom  and @edarin  any inputs ?
Thanks

**Comment by bondarenkom** [comment]
Please check this page https://www.worldpop.org/project/categories?id=3

You should find:
- Constrained Individual countries 2020 ( 100m resolution )
- Constrained Individual countries 2020 UN adjusted  (100m resolution)

**Comment by ebocher** [comment]
Thanks @bondarenkom 
Is there an OGC endpoint  to extract on demand some part of the grid (as WCS ) ? If no,  is this part of your roadmap  ?
