### ISSUE TITLE
Retrieving more buildings

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#721]
It seems some of the OSM buildings are not taken into account in GeoClimate. It is for example the case of buildings dedicated to parking:
https://www.openstreetmap.org/relation/13128398

Any chance to add these buildings to the chain ?

**Comment by ebocher** [comment]
Without any  level or height tags, it will be hard to define the best information to model it as a building.
Do you have any suggestion ?

**Comment by j3r3m1** [comment]
We do not have any level either for most buildings. The problem would be if we have a lot of parkings which are created as building but are underground. But are they created as building then ?
Otherwise we could create a new building type "parking" (https://github.com/orbisgis/geoclimate/wiki/Building-layer#type-and-main_use-column-values) and then estimate its height with the algo ?

**Comment by ebocher** [comment]
Building=parking has been integrated and qualified in transportation for the main use.
See : https://github.com/orbisgis/geoclimate/blob/master/osm/src/main/resources/org/orbisgis/geoclimate/osm/buildingParams.json#L76
When the building doen't have any height information we set 1 level by default.
