### ISSUE TITLE
New land/sea mask trouble

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#727]
Previously I got troubles with a bbox in Göteborg (see #646). It has been solved but I now have the same kind of issue with a new (larger) bounding box.
http://bboxfinder.com/#57.596495,11.706619,57.805262,12.208557

I have tried to isolate the bug trying the following bboxes:
- http://bboxfinder.com/#57.770000,11.706619,57.805262,11.870000 -> unfortunately works...
- http://bboxfinder.com/#57.683262,11.706619,57.805262,11.750000 -> same
- http://bboxfinder.com/#57.672000,11.706619,57.805262,11.870000 -> I got the error again, at last.

Then the last bbox is the case that can be used for debugging. I will now try to extend the zone on the west to not cut the coastline near the northern Göteborg archipelago. It might work before any fix, fingers crossed. I let you know.

**Comment by j3r3m1** [comment]
It seems the problem remains if I extend the zone, the problem probably comes from the limit between river and sea at the outlet of the Göta river:
https://www.openstreetmap.org/way/246569680

**Comment by ebocher** [comment]
Ok I'm on it and I confirm the issue due the  Göta river ;((((

**Comment by ebocher** [comment]
Ok I have a fix to improve sea/land mask extraction.

![guta_river](https://user-images.githubusercontent.com/1820572/166895329-3cb518ab-acae-4cb4-8273-bedbd1e1eb6f.png)

**Comment by ebocher** [comment]
Fixed an rocks !

**Comment by j3r3m1** [comment]
Still issues with the initial bbox:
http://bboxfinder.com/#57.596495,11.706619,57.805262,12.208557

**Comment by j3r3m1** [comment]
Actually all pieces of land and seas are fine except the bigger mainland which is identified as sea instead of land

**Comment by ebocher** [comment]
Fixed here https://github.com/orbisgis/geoclimate/pull/807
Note : new improvments to build RSU are on the pipe due to the size of the area
