### ISSUE TITLE
Add informations on building typologies at RSU scale in UTRF classification (ask for enhancement)

### ISSUE THREAD

**Issue by sfaraut** [orbisgis/geoclimate#748]
Hi Geoclimate team!

Actually,  Geoclimate's UTRF classification gives informations about building typologies at building and RSU scale.
At RSU's scale we only have "TYPO_MAJ"  which is the  "Main urban typology".

We would appreciate to get more informations, especially about what should be the "Secondary urban typology" (TYPO_SECOND) which are actually missing  (the same way they were generated by the OrbisGIS "MAPUCE Tool"). A value of "na" (or "-" like URTF classification) for "TYPO_SECOND" could indicate that there is only one main typology in this RSU.

This indicator is very usefull in case of many heterogeneous buildings in a same RSU.
A ratio of each TYPO_MAJ and TYPO_SECOND building's type should also be given.

An alternative should be to give the ratio for all ten different building's type in each RSU (like  "MAPUCE Tool")

Thanks.

**Comment by j3r3m1** [comment]
You have the distribution of each building type in each RSU based on:
- building area in the output table called rsu_utrf_area
- building floor area in the output table called rsu_utrf_floor_area

**Comment by j3r3m1** [comment]
This information is not in the wiki, we need to add that.
There is also a uniqueness_value which describe how unique is the typo_maj compare to the typo_second ((%typo_maj - %typo_second) / (%typo_maj + %typo_second))

**Comment by j3r3m1** [comment]
> This information is not in the wiki, we need to add that. 

Now updated

**Comment by ebocher** [comment]
Fixed by @j3r3m1 clap clap
