### ISSUE TITLE
Anormal calculation time for IProcess upperScaleAreaStatistics()

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#752]
This function never stops calculating when I try to rasterize LCZ for the following bbox:
http://bboxfinder.com/#57.596495,11.693000,57.805262,12.208557

Is the problem may come from the ST_FORCE2ST in the INTERSECT ("WHERE a.$lowerGeometryColumn && b.$upperGeometryColumn AND ST_INTERSECTS(st_force2d(a.$lowerGeometryColumn), st_force2d(b.$upperGeometryColumn));") (see https://github.com/orbisgis/geoclimate/blob/master/geoindicators/src/main/groovy/org/orbisgis/geoclimate/geoindicators/GenericIndicators.groovy#L1026)?

Note that the number of geometries is important but far from extreme (RSU_LCZ : 12'081 and GRID cells : 71'298).

**Comment by j3r3m1** [comment]
I have tried to remove the st_force2d thinking that it may affect the use of the index but no observable difference. This calculation is just really long.

If this behavior is normal, it could be interesting to divide the grid into several subarea of interest and make the calculation for each of them within the UpperScaleStatistic IProcess. I think it can be interesting because it is currently the only algorithm which is really long when applied to a large zone of interest.

**Comment by j3r3m1** [comment]
If anyone wants to debug or have a test:
[dataToDebug.zip](https://github.com/orbisgis/geoclimate/files/9100582/dataToDebug.zip)

**Comment by j3r3m1** [comment]
After discussion with @ebocher it seems the best way to solve that would be to use the existing IProcess called 'smallestCommunGeometry'.

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
Fixed here https://github.com/orbisgis/geoclimate/pull/807
