### ISSUE TITLE
json config file - proposal for enhancement

### ISSUE THREAD

**Issue by simogeo** [orbisgis/geoclimate#755]
According to me, locations should not be nested in _folder_ key but at the same level because it is not (or should not be) dependent from the dataset.

Now : 
```json
"input": {
        "folder": {"path": "C:\\mydirectory\\Geoclimate\\BD_TOPO_v2",
                   "locations":["12174"]
         }
}
```

And I think geoclimate should be able to proceed local data by passing BBox as well. I haven't tested but since the config file is organised as it is, I'm not sure it works ...

Proposed structure and ability -use of BDTOPO with BBox) : 
```json
"input": {
        "folder": {
            "path": "C:\\mydirectory\\Geoclimate\\BD_TOPO_v2"
        },
       "locations":[44.143013,3.063040,44.171924,3.145437]
}
```

Hope it is clear enough

**Comment by simogeo** [comment]
Sorry; I've just seen that it is possible to use BBox with BDTOPO here : 
https://github.com/orbisgis/geoclimate/wiki/Bounding-box-case-for-Windows#bounding-box-method-with-bdtopo-v22

And I see data as to be in meters in that case ...

**Comment by ebocher** [comment]
It seems reasonable

**Comment by ebocher** [comment]
@j3r3m1  ready for you ?

**Comment by j3r3m1** [comment]
> @j3r3m1 ready for you ?

Sure ! As long as we do not forget to update the wiki whenever it is changed ! =)

**Comment by ebocher** [comment]
Done
