### ISSUE TITLE
Error toRowResult while trying to play the BD_TOPO8v2 default case. 

### ISSUE THREAD

**Issue by MGousseff** [orbisgis/geoclimate#760]
I tried to run the Default case with BD_Topo_v2. I get the following error : 

`[main] ERROR org.orbisgis.process.Process - Error while executing the process.
groovy.lang.MissingMethodException: No signature of method: groovy.sql.GroovyResultSetProxy$DummyResultSet.toRowResult() is applicable for argument types: () values: []
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:50)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at org.orbisgis.geoclimate.geoindicators.GenericIndicators$_distributionCharacterization_closure5$_closure24$_closure27$_closure32.doCall(GenericIndicators.groovy:602)`

My config file is : 
``` 
{
    "description": "Processing BD Topo v2 data",
    "input": {
        "folder": {"path": "/home/gousseff/Documents/2_CodesSources/GeoClimate/GeoclimateDefaultCase/BD_TOPO_v2/",
                   "locations":["12174"]
                   }
				
    },
    "output": {
        "folder": "/home/gousseff/Documents/2_CodesSources/GeoClimate/GeoclimateDefaultCase/temp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ"
            ]
        },
        "grid_indicators": {
            "x_size": 100,
	      "y_size": 100,
	      "rowCol": false,
	      "output" : "geojson",
	      "indicators" :[
                 "BUILDING_FRACTION", 
                 "BUILDING_HEIGHT", 
                 "WATER_FRACTION",
                 "VEGETATION_FRACTION", 
                 "ROAD_FRACTION", 
                 "IMPERVIOUS_FRACTION", 
                 "LCZ_FRACTION"
             ]
         }
    }
}
```
(I removed indicators other than "LCZ" but the same error appeared with all the indicators)

My groovy version is 3.0.11

`java -version` returns `openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
`
I run the code in a Ubuntu 20.04 OS. 

Thanks for any idea how to fix this.

**Comment by ebocher** [comment]
Thanks a lot
There is a fix here https://github.com/orbisgis/geoclimate/pull/761

**Comment by ebocher** [comment]
Done

**Comment by MGousseff** [comment]
Thanks a lot, successfully tested here !
