### ISSUE TITLE
Change the name of the workflow process identifiers

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#765]
Currently the outputs of the identifiers have the names  : outputTableBuildingIndicators, outputTableBlockIndicators ...
I propose to change these names for more consistency and simplicity.

e.g : 
building_indicators instead of outputTableBuildingIndicators
block_indicators instead of  outputTableBlockIndicators
building instead of buildingTableName

From a GeoClimate workflow, you will have 

getResults().output["Pont-de-Veyle"]["road_traffic"]

["Pont-de-Veyle"] = identifier of the location

["road_traffic"] =  identifier for the result table

@j3r3m1  @ELSW56

**Comment by j3r3m1** [comment]
Sounds reasonable

**Comment by ELSW56** [comment]
To my mind, it's a good simplification, and the use of "_" instead of capital letters makes the name more readable.
