### ISSUE TITLE
Acoustic absorption coefficient and ground table

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#772]
As geoclimate proposes a method to estimate a reference traffic, it'd be nice to offer a way to return the sound absorption coefficient in a ground table. This will facilitate the link with NoiseModelling community (https://github.com/Universite-Gustave-Eiffel/NoiseModelling).
So we can add in the input config file

```json
"parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "UTRF"
            ],
            "svfSimplified": true,
            "estimateHeight": true
        },
        "noise_indicators": {
            "ground" : true
         }
    }
```
The ground table should contain water, vegetation and imprevious_areas.
The schema of the ground table should be defined with 3 columns : 

-  id_ground : unique identifier
- the_geom : polygon or multipolygon
- g : acoustic absorption coefficient 

@j3r3m1 @gpetit @nicolas-f  @pierromond

**Comment by ebocher** [comment]
Working with the NoiseModelling team offers new research opportunities in the field of "naturally ventilated buildings and noise mapping".

**Comment by j3r3m1** [comment]
If I understand well, the ground table is built according to OSM data and may become a table in the generic model (when "noise_indicators" is set to True) ?

**Comment by ebocher** [comment]
The final configuration file to produce data for noise simulation will be : 

```
"parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "UTRF"
            ],
        },
        "noise_indicators": {
            "ground" : true
         },
        "road_traffic": true
    }
```

where  

"indicatorUse": [  "UTRF"  ]
is used to estimate the OSM building height

"noise_indicators": { "ground" : true}
is used to set the noise indicators to compute. Currently only the ground table as described above

"road_traffic": true"
is used to set if the road_traffic table is build or not

IMPORTANT : 

GeoClimate does not format the column names for the output building and the road_traffic table as required by NoiseModelling.
Therefore, the NoiseModelling team needs to adapt the column names,
 e.g. replace height_roof with height

**Comment by ebocher** [comment]
Done ;)
I will write a page on the wiki asap
