### ISSUE TITLE
Some sea areas are incorrectly classified as low vegetation LCZ

### ISSUE THREAD

**Issue by dtzanos** [orbisgis/geoclimate#773]
I have just made a LCZ map on La Réunion island and some sea areas are incorrectly classified as low vegetation LCZ.
I use geoclimate-0.0.2-SNAPSHOT.jar on an Ubuntu 20.04 Linux PC.

Some tiles show an error message in the logfile but it's not always the case.
Two tiles are highlighted here:
![LCZ_REUNION_zoomNW_annote](https://user-images.githubusercontent.com/116001281/196201394-f2b4d46b-baba-4e78-ab68-4a64ec556e0e.png

1- Example with an error message in the logfile: the tile #1328
[config_1328_json.txt](https://github.com/orbisgis/geoclimate/files/9801433/config_1328_json.txt)
[log_1328.txt](https://github.com/orbisgis/geoclimate/files/9801457/log_1328.txt)

2- Example with no error message in the logfile: the tile #839
[config_839_json.txt](https://github.com/orbisgis/geoclimate/files/9801467/config_839_json.txt)
[log_839.txt](https://github.com/orbisgis/geoclimate/files/9801469/log_839.txt)

**Comment by ebocher** [comment]
Thanks for the feedback.

**Comment by ebocher** [comment]
Fixed here https://github.com/orbisgis/geoclimate/pull/807
