### ISSUE TITLE
issue related to impervious indicators ?

### ISSUE THREAD

**Issue by simogeo** [orbisgis/geoclimate#774]
I'm working on Lorient city area, in Britain / France.

And the area which is supposed to be the most impervious appears with very low impervious index.

When adding  IMPERVIOUS_FRACTION + ROAD_FRACTION from `grid_indicators.json` geoclimate result I get on that specific area, an index lower than 0.2. According to people who know the area - it should not ....

The area is on south part : 

![image](https://user-images.githubusercontent.com/154323/197246281-c9b71e29-f772-4eae-aeb7-6d770d11a2cb.png)

Zoom on concerned area  - it seems the Est part should be much darker : 
![image](https://user-images.githubusercontent.com/154323/197246355-1b43fd06-e616-4df7-b079-48d339fb036d.png)

legend : 

![image](https://user-images.githubusercontent.com/154323/197246462-04c2131b-9e18-4443-b6db-a597ed4ac996.png)

Clicking one cell, I can see that it is classified as undefined : 

![image](https://user-images.githubusercontent.com/154323/197246909-0f2816f5-5c85-4238-8c20-2fd0308a2866.png)

In red the selected cell : 
![image](https://user-images.githubusercontent.com/154323/197246981-3c2762e4-4c49-44f4-bf10-07cdcb73206f.png)

Not sure it is a bug or it is due to the data itself. I'm relying on BD TOPO 2.2 analysis.

Thanks for your feedback !

poke @ebocher

**Comment by j3r3m1** [comment]
Hi @simogeo 
Thank you for the feedback.
There is a real lack of data in BDTopo nor OSM to simply identify impervious area. However, we might use a trick to consider that by default, all surfaces of commercial or industrial areas (which are identified both in OSM and BDTopo) are impervious. Thus only if vegetation is identified we will replace impervious by vegetation.
This will be a future enhancement.
