### ISSUE TITLE
ability to call geoclimate-xxx.jar with 'verbose' option ? - feature request

### ISSUE THREAD

**Issue by simogeo** [orbisgis/geoclimate#780]
It would be nice to be able to specify to display processes when running geoclimate ?

Option a) by passing  '--verbose' argument when calling geoclimate-xxx.jar
Option b) by passing 'verbose' option in json file 

![image](https://user-images.githubusercontent.com/154323/200321934-1064e997-d0d5-4a20-a29c-e51fba087c60.png)

**Comment by ebocher** [comment]
Check     System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "TRACE");

**Comment by ebocher** [comment]
Done

**Comment by ebocher** [comment]
Here the doc https://github.com/orbisgis/geoclimate/wiki/Frequently-Asked-Questions#how-to-custom-log-messages-with-geoclimate-cli-
