### ISSUE TITLE
some material to compare and enhance OSM height building estimation

### ISSUE THREAD

**Issue by simogeo** [orbisgis/geoclimate#781]
You'll find attached data on buildings layers for Arsac in Gironde : 

- BD TOPO v2 : https://cloud.intermezzo-coop.eu/index.php/s/TtrJLgopwtYLGFx
- OSM : https://cloud.intermezzo-coop.eu/index.php/s/ZPSo5GYz7bpzEFf with link to [building_height_missing.csv](https://cloud.intermezzo-coop.eu/index.php/s/N2DrEdPPor8Kcdy)

https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=103234&class=boundary

Please download and archive data because I will probably remove it soon.

**Comment by ebocher** [comment]
Close it since a paper that adress the limit of the height model is available at  : https://doi.org/10.5194/gmd-15-7505-2022
