### ISSUE TITLE
Missing outputs in computeAllGeoindicators

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#782]
When executing the IProcess computeAllGeoindicators with building from BDTopo V2 and all other layers from OSM there are missing tables in the output (miss all UTRF related tables).

**Comment by simogeo** [comment]
From the groovy script, see outputs (_null_ values) : 

```
[block_indicators:block_indicators_52b69069_88b8_48a1_8d61_bee4d6b249aa, zone:OSM_zoneTable, building_utrf:null, rsu_utrf_area:null, rsu_indicators:rsu_indicators_cd51f765_8e98_4058_a17b_a3653da386a5, rsu_lcz:RSU_LCZ_c0b5d521_22f0_491e_87d9_1963bb942be9, building_indicators:building_indicators_a1df83a6_43c7_408b_99e2_d1906b3ef15a, rsu_utrf_floor_area:null, building:building_repro]
block_indicators_52b69069_88b8_48a1_8d61_bee4d6b249aa
OSM_zoneTable
rsu_indicators_cd51f765_8e98_4058_a17b_a3653da386a5
RSU_LCZ_c0b5d521_22f0_491e_87d9_1963bb942be9
building_indicators_a1df83a6_43c7_408b_99e2_d1906b3ef15a
building_repro
Result: [block_indicators:block_indicators_52b69069_88b8_48a1_8d61_bee4d6b249aa, zone:OSM_zoneTable, building_utrf:null, rsu_utrf_area:null, rsu_indicators:rsu_indicators_cd51f765_8e98_4058_a17b_a3653da386a5, rsu_lcz:RSU_LCZ_c0b5d521_22f0_491e_87d9_1963bb942be9, building_indicators:building_indicators_a1df83a6_43c7_408b_99e2_d1906b3ef15a, rsu_utrf_floor_area:null, building:building_repro]
```

**Comment by j3r3m1** [comment]
OK I have found the reason. In the computeAllGeoindicators IProcess, there is an input which is the name of the UTRF model to be used for the classification. 
https://github.com/orbisgis/geoclimate/blob/2b769b558d22855176d0292b8b35818381b90f22/geoindicators/src/main/groovy/org/orbisgis/geoclimate/geoindicators/WorkflowGeoIndicators.groovy#L1024

This model has a different name depending if it is dedicated to OSM or BDTopo use... Thus there is no default value and the user has to set the one corresponding to its dataset. The models are in the model folder (https://github.com/orbisgis/geoclimate/tree/master/models) and the last version should be used:
- for OSM, the current name is "UTRF_OSM_RF_2_2.model"
- for BDTopo, the current name is "UTRF_BDTOPO_V2_RF_2_2.model"

This string should be used like that in the IProcess declaration:
utrfModelName =  "UTRF_OSM_RF_2_2.model" or utrfModelName = "UTRF_BDTOPO_V2_RF_2_2.model"
