### ISSUE TITLE
Missing ways in OSM

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#783]
Some ways that we may assume to be impervious are not downloaded in the OSM workflow. Below is an example concerning the airport in Blagnac. The following way is an example of what is not downloaded by GeoClimate while it should probably be: 
https://www.openstreetmap.org/way/946980104

The following data are downloaded
![image](https://user-images.githubusercontent.com/13120405/200572274-a1dfbcd7-1046-4ece-9d3f-06e6000eaa49.png)

**Comment by ebocher** [comment]
We must check the area key tags 
https://wiki.openstreetmap.org/wiki/Key:area:aeroway?uselang=fr

**Comment by ebocher** [comment]
Fixed for aeroway surface. Now we must take into account linear aeroway and push it in road layer.

**Comment by j3r3m1** [comment]
wonderful !
