### ISSUE TITLE
Trouble with mappers

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#79]
I still have a problem with the mapper createScalesOfAnalysis.
I have a null table in the IProcess createScalesRelations between blocks and buildings. It seems that the mapper input inputLowerScaleTableName is null whereas it is well written as a string in input in my test.
Is this problem could come from the fact that I use several times the createScalesRelations and then the input is defined several times ? I do not get it. @SPalominos I am available for debugging if you have time.

**Comment by ebocher** [comment]
I'm on it
