### ISSUE TITLE
Erreur exécution geoclimate

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#796]
### Discussed in https://github.com/orbisgis/geoclimate/discussions/795

<div type='discussions-op-text'>

<sup>Originally posted by **LesMerlusFrits** December 21, 2022</sup>
Bonjour,

Nous avons un message d'erreur lors de l'exécution du fichier de configuration, que ce soit avec OSM ou la BD TOPO v2.

Message d'erreur pour le workflow de la BD TOPO : 
**"The input datasource must be defined with the name bdtopo_v2
Cannot execute the BDTOPO_V2.2 workflow"**

![Erreur BD TOPO](https://user-images.githubusercontent.com/121180173/208937064-257b38c9-c413-40eb-a2a4-7cec64be127f.png)

Erreur pour OSM :
![Erreur filtre OSM](https://user-images.githubusercontent.com/121180173/208946130-2338f9b1-7831-4f24-9ca3-3d3427e1f23c.png)

Merci par avance pour votre aide.
Les Merlus Frits (IGARUN)

</div>

**Comment by j3r3m1** [comment]
Can you share with us your config file ?

**Comment by ebocher** [comment]
Any input since @j3r3m1  answer's ?

**Comment by LesMerlusFrits** [comment]
> Can you share with us your config file ?

We sincerely apologize, the answer did not appear on the thread. 
We used the config files given as an exemple in the wiki for windows, to see if we could get the program started.
Here is the config file for OSM :
![Commande json](https://user-images.githubusercontent.com/121180173/211348964-2d9c2f81-df64-477b-98db-54ab2dfa1789.png)
Sorry for the wait.

**Comment by ebocher** [comment]
The configuration file seems good. 
Which version of GeoClimate are you using ?
The wiki documentation is aligned with the snapshot version, available here https://nightly.link/orbisgis/geoclimate/workflows/CI_snapshot/master/geoclimate-0.0.2-SNAPSHOT.zip

**Comment by LesMerlusFrits** [comment]
I downloaded the version you gave me, but there is a new problem.
![Capture d’écran 2023-01-09 173449](https://user-images.githubusercontent.com/121180173/211359709-bc250a6c-2828-4b2a-a30a-caa470958411.png)

**Comment by j3r3m1** [comment]
What is your Java version ? You should probably update to 11 or +

**Comment by LesMerlusFrits** [comment]
I upgraded java, now I have v11. Geoclimate has started successfully. Then when I start the workflow with the config file, the beginning of the program works, but an error occurs. This error prevents executing the OSM workflow
![Capture d’écran 2023-01-10 112145](https://user-images.githubusercontent.com/121180173/211525755-29660bde-04c0-43dc-863e-112ae27bb139.png)
![2](https://user-images.githubusercontent.com/121180173/211525773-6ffedc83-322d-4702-ae61-e7f866ad6a07.png)

**Comment by j3r3m1** [comment]
Your config file is mistaken. You should have 2 backslash for paths in Windows. In your case, you set as output directory "C:\temp" while you should use "C:\\temp"

**Comment by LesMerlusFrits** [comment]
Well, after taking to account your advice, I retry the process from the 1st stage, and it works. The OSM workflow has finally been successfully executed. I tried others cities, and the process works too.
Thank you for the time you spent for helping me.

**Comment by j3r3m1** [comment]
Fine to read that everything works well. Enjoy GeoClimate
