### ISSUE TITLE
Problem geoclimate while saving files

### ISSUE THREAD

**Issue by derrieni** [orbisgis/geoclimate#797]
Hello, 
One of my script executes Geoclimate in order to create a LCZ map. Execution step works, but then it cannot be saved in my folder, while I gave all the rights for writing. I let a screenshot of the error, and the screenshot of the config.json .
![geoclimate](https://user-images.githubusercontent.com/121953861/210576761-f3ce1142-187d-46d1-b468-7f7fcf0c9be0.png)
![image](https://user-images.githubusercontent.com/121953861/210577496-e5d63dc3-9f29-4550-adfe-f0e318818451.png)

Regards

**Comment by ebocher** [comment]
We are not able to reproduce this issue. Do you have the rights to write to the folder

**Comment by derrieni** [comment]
Yes i can write

**Comment by j3r3m1** [comment]
Can you share your database ? By default it should the file /tmp/geoclimate.db

**Comment by ebocher** [comment]
This issue was closed because it has been inactive since several weeks ago.
Please re-open it if necessary.
