### ISSUE TITLE
Rural LCZ partitionning

### ISSUE THREAD

**Issue by wurtzj** [orbisgis/geoclimate#798]
Hi everyone,

As comparing LCZ from Geoclimate to global LCZ from RUB, I saw that the partitioning of rural LCZ is too crude in Geoclimate. In fact Geoclimate identifies many times regions with crops and some patches of trees with the "scattered trees" LCZ (LCZ B) although it should be two seperated LCZ with one "low plants" (LCZ D) and one with dense trees (LCZ A).

Here a quick comparison over Melun between LCZ from Geoclimate, from RUB global map and from google Earth satellite. The more striking is east of Melun.

Maybe changing the minimal surface of high vegetation to derive USR may be enough to solve this issue and avoid large scattered trees areas ?
Maybe use the same minimal surface of for the one used to derive water surfaces ?

Geoclimate
![image](https://user-images.githubusercontent.com/99657196/210741624-90614c8f-3af9-4f85-9d60-b7fb9c6561e3.png)

RUB
![image](https://user-images.githubusercontent.com/99657196/210741796-fe4bd1f6-bcbd-4cbc-9d6f-dca237e3cdf8.png)

Google satellite view : 
![image](https://user-images.githubusercontent.com/99657196/210741893-21f2be2d-2588-41c2-afdd-3695a0d9a255.png)

Legend :
![image](https://user-images.githubusercontent.com/99657196/210741760-d5afb267-8fa1-4b8a-b4fc-a5531a09a9c5.png)

RUB LCZ :
Data: https://zenodo.org/record/6364594
Paper: https://essd.copernicus.org/articles/14/3835/2022/
Viewer: https://lcz-generator.rub.de/global-lcz-map

**Comment by j3r3m1** [comment]
Thank you for your message. Rural areas are definitely not well represented in GeoClimate, especially where you have really few roads on your territory. Which data are you processing with GeoClimate ? OSM or BDTopo ? I would be curious to see the LCZ at RSU scale since they are first calculated at RSU scale and then aggregated to grid scale. We might discuss technic to improve the results afterward.

**Comment by wurtzj** [comment]
Thank you @j3r3m1 for your answer. Data used by Geoclimate is OSM here.
I have not the RSU for the moment. But I think there are quite big as it seems that the results are very geometric in Geoclimate.

**Comment by ebocher** [comment]
Fix in the current SNAPSHOT with https://github.com/orbisgis/geoclimate/pull/853
Please test
