### ISSUE TITLE
[climate modeling] issue of landuse integration (Geoclimate LCZs) into WRF atmospheric model

### ISSUE THREAD

**Issue by FloBre33** [orbisgis/geoclimate#806]
Hi, 

Geoclimate works fine but I have an issue when trying to use the outputs (urban indicators, local climate zones) in my atmospheric model (WRF) to simulate the urban climate of Strasbourg (in France). 

The integration of Geoclimate urban indicators in WRF is relatively easy. I first do GIS processing to estimate representative values per urban class (e.g. 10,65m average building height for LCZ2), and then put these values in the WRF file containing urban parameters (URBPARM_LCZ.TBL). 

There is however an issue with the integration of the Geoclimate local climate zones (LCZs) in WRF. The Strasbourg area is represented in WRF by a grid of about 30kmx30km (1km resolution) and WRF expects a landuse category per gridpoint (e.g. LCZ2 or crop or forest). I first do GIS processing to intersect the WRF grid with the Geoclimate LCZs, and to determine one LCZ per gridpoint. The issue is that when I replace the old landuse in the WRF domain file (geo_em.d04.nc) by the new landuse (intersected Geoclimate LCZs), the netCDF file attributes are also changed, and WRF then refuses to use the new domain to do the climate simulation.

The landuse replacement was done using CDO (Climate Data Operators), but I'm looking at alternatives such as Python, in order to conserve the file attributes during the landuse replacement. 

This may have already happened to someone? Or this might be of interest to people who want to simulate urban climates at high resolution with Geoclimate indicators?

**Comment by j3r3m1** [comment]
If you need the LCZ at grid cell, you might also integrate "LCZ_FRACTION" and "LCZ_PRIMARY" to the list of indicators to calculate at grid scale. You will then obtain a fraction of each LCZ for each of the grid cell (that can be 1 km large) and also the mode of the LCZ fraction (LCZ primary). Does this help ? We might add that to the tuto if needed.

**Comment by j3r3m1** [comment]
> Actually, this matter might be more relevant to WRF than to Geoclimate.

I suppose it is relevant for both since it is a connection between two tools. It would be nice to have a brief tutorial of how to connect GeoClimate to WRF inputs. @ebocher what do you think ? It might be in an "Example of application cases" ?

**Comment by ebocher** [comment]
@FloBre33 
thank you for sharing the information
@j3r3m1 
excellent idea ! Ready for a full tutorial  and to add it as a use cases section in the wiki.

looking at the python code  , I think we could also add in the future an option to store wrf indicators in a NetCDF file ?

**Comment by j3r3m1** [comment]
> excellent idea ! Ready for a full tutorial and to add it as a use cases section in the wiki.
@FloBre33 would you help setting this tutorial ?

> looking at the python code , I think we could also add in the future an option to store wrf indicators in a NetCDF file ?

If the grid produced in geoClimate is the same as it is in WRF, yes but is it the case ? @FloBre33  ?

**Comment by FloBre33** [comment]
> @FloBre33 would you help setting this tutorial 
Sure. 

I see two ways of using Geoclimate for climate simulations with atmospheric models (such as WRF). 

Many people who use LCZs (local climate zones) in WRF first take the tool WUDAPT ([https://www.wudapt.org/](https://github.com/matthiasdemuzere/w2w)) to make a LCZ map and then the tool W2W ([https://github.com/matthiasdemuzere/w2w](https://github.com/matthiasdemuzere/w2w)) to put these LCZs in the WRF grid. 
Geoclimate can give good estimations of urban parameters for each LCZ , and can also provide a better urban mapping of LCZs (10m resolution, vs. 100m for WUDAPT).
For my current research project on the Strasbourg region (France), we compared LCZ maps done with WUDAPT and Geoclimate. Wudapt had better results for rural landuse (forests, crops) and Geoclimate had better results for urban landuse.

**Comment by j3r3m1** [comment]
OK so you are only using the LCZ for your WRF modelling ? You are not using the UCP parameters directly in WRF ? If I understand well, your steps are then:
1. Create the LCZ at 10 m resolution using GeoClimate (actually they are calculated at TSU scale and then rasterized at 10 m)
2. Convert the LCZ data from step 1 to the input data format needed by the W2W tool
3. Configure your WRF simulation and run it

What is interesting in our case are the last two cases I suppose. We might create a case in the tuto for these steps. I create the page and share it here if it is fine for you.

Ideally, in the future, it might be better using directly the UCP calculated by the GeoClimate tool. This is the strenght of using vector data: we calculate the WRF needed UCP parameters. Using the GeoClimate LCZ induce a data loss since you calculate UCP, you use them to calculate LCZ and then you derive standard UCP values from LCZ classes. We might think about a future tutorial where we directly include GeoClimate indicators into WRF.

**Comment by FloBre33** [comment]
Almost. The steps look like this:
1. Yes, actually this was done by students at the lab. They also generated a Wudapt mapping of LCZs. [https://lcz-generator.rub.de/](https://lcz-generator.rub.de/)
2. Since Wudapt is better for rural and Geoclimate for urban, I tried to use the best from each. There is a "nourban" file produced by the tool w2w for the WRF grid. [https://github.com/matthiasdemuzere/w2w](https://github.com/matthiasdemuzere/w2w)
I estimated on QGIS the dominant urban Geoclimate LCZ (and general urban fraction) per WRF gridpoint, and inserted them into the nourban grid. For each urban LCZ, I also estimated on GIS the urban parameters (e.g. building height, population density) based on Geoclimate outputs. 
3. Yes, putting the custom urban parameters in the configuration files. 

We ran a WRF sensitivity test in summer and winter with 2 configurations: good urban representation (as described above) vs. basic representation (default settings). The results showed reduced bias in temperature and wind by comparison to weather measurements, and also a larger difference between urban, periurban and rural weather conditions (for impact studies such as energy consumption or thermal comfort).

There are some manual steps here so I'm not sure I can translate it into code. It's more of an approach or method.

**Comment by magalietecher** [comment]
Hi, Thank you for these explanations. I'm interested by your methodology to integrate LCZ into WRF. I'm pretty novice  so could you explain how do you integrate the geoclimate LCZ and parameters and modify the geogrid file generated by W2W?

**Comment by j3r3m1** [comment]
@FloBre33 if you have further detail to share it would be nice. We can also grant you the access to the GeoClimate repo, thus you will be able to add a detailed tutorial in the wiki. What do you think ?

**Comment by FloBre33** [comment]
> I'm pretty novice so could you explain how do you integrate the geoclimate LCZ and parameters and modify the geogrid file generated by W2W?

To calculate the geoclimate LCZ and parameters for the WRF grid, see the explanation (2.) from my post above of last month. 

For the geogrid file modification, some methods (R, Python, CDO) can corrupt the file for metgrid use in WRF. A method that worked was using R to open both the file containing the new landuse (estimated on GIS) and the original geogrid file (nourban from Wudapt), then adding the urban classes to the landuse (modify the values at given gridpoints), and saving to .csv format, before using Python as in my post above from April 6. 

> @FloBre33 if you have further detail to share it would be nice. We can also grant you the access to the GeoClimate repo, thus you will be able to add a detailed tutorial in the wiki. What do you think ?

Since the overall approach combines several languages and tools, I would just advise to get familiar with them. The documentations are given below.

Tools:
- WRF -> [https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_v4/contents.html](https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_v4/contents.html)
- WUDAPT -> [https://www.wudapt.org/](https://www.wudapt.org/)
- w2w -> [https://github.com/matthiasdemuzere/w2w](https://github.com/matthiasdemuzere/w2w)
- Geoclimate -> [https://github.com/orbisgis/geoclimate/wiki](https://github.com/orbisgis/geoclimate/wiki)
- QGIS -> [https://www.qgis.org/en/site/index.html](https://www.qgis.org/en/site/index.html)

Languages:
- R -> [https://www.r-project.org/](https://www.r-project.org/)
- Python -> [https://www.python.org/](https://www.python.org/)

One part that may be difficult is specific to WRF and GIS, it's the estimation of some of the BEP-BEM urban parameters (e.g. population density), where you need to work with public databases on GIS. Local geographers helped me to do it. Let me know if you have issues.

FB
