### ISSUE TITLE
bbox method with osm error

### ISSUE THREAD

**Issue by 4estone** [orbisgis/geoclimate#829]
When running geoclimate with bbox option I get an error:
```
{'description': 'Processing OSM data', 'input': {'locations': [[[48.68338861999224, 7.628993170108124, 48.711842431126925, 7.672313245006061]]]}, 'output': {'folder': 'C:\\temp'}, 'parameters': {'rsu_indicators': {'indicatorUse': ['LCZ', 'TEB', 'URBAN_TYPOLOGY'], 'svfSimplified': True, 'estimateHeight': True}}}
Please set at least one OSM filter. e.g osm : ['A place name']
Cannot execute the OSM workflow
```
What is wrong ?
Thanks

**Comment by andreazonato** [comment]
Same error for me!

**Comment by ebocher** [comment]
Please share the full configuration file or input parameters.

**Comment by ebocher** [comment]
There is a unit test in GeoClimate code with the following parameters thats rocks !

```
{"description":Example of configuration file to run the OSM workflow and store the result in a folder, geoclimatedb:{"folder":/tmp/junit17351523886066929138/testOSMWorkflowFromPoint, name:geoclimate_chain_db;AUTO_SERVER=TRUE, "delete":true}, 
"input":{locations:[[48.78146, -3.01115, 48.78236, -3.0102515]]},
 "output": {"folder":/tmp/junit17351523886066929138/testOSMWorkflowFromPoint}}

```

**Comment by 4estone** [comment]
{
    "description": "Processing OSM data",
    "input": {
        "locations": [
            [
                48.68338861999224,
                7.628993170108124,
                48.711842431126925,
                7.672313245006061
            ]
        ]
    },
    "output": {
        "folder": "C:\\temp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "URBAN_TYPOLOGY"
            ],
            "svfSimplified": true,
            "estimateHeight": true
        }
    }
}

**Comment by ebocher** [comment]
What version of GeoClimate ?

**Comment by ebocher** [comment]
@4estone 
I'm not able to reproduce this issue with the current GeoClimate version 0.0.2-SNAPSHOT.

Here the LCZ with your area.

![area_osm](https://github.com/orbisgis/geoclimate/assets/1820572/521566c9-244e-4c45-9f3c-c30b907bd412)

**Comment by 4estone** [comment]
I use geoclimate-0.0.1.jar
Where I can get 0.0.2.jar?

**Comment by j3r3m1** [comment]
[here](https://nightly.link/orbisgis/geoclimate/workflows/CI_snapshot/master/geoclimate-0.0.2-SNAPSHOT.zip)

**Comment by 4estone** [comment]
Ok thanks
What's minimum Java version I can use?
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/orbisgis/geoclimate/Geoclimate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by j3r3m1** [comment]
minimum 11

**Comment by 4estone** [comment]
Thank you!
