### ISSUE TITLE
OSM: buildings are created when not exists

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#858]
I found a case which seems not consistent with the reality using the OSM data.

I have a building for [this object](https://www.openstreetmap.org/way/1172856149) while there should not be any building (cf. Google Street view: https://www.openstreetmap.org/way/1172856149).

Not sure how often this happens but it seems that in OSM the cartography of this object differs from the train stations. Is there any example of such key=value tag where we have a real building ?

**Comment by ebocher** [comment]
> I have a building for [this object](https://www.openstreetmap.org/way/1172856149) while there should not be any building (cf. Google Street view: https://www.openstreetmap.org/way/1172856149).

You mean . GeoClimate creates a building ?

**Comment by j3r3m1** [comment]
> You mean . GeoClimate creates a building ?

Yes this is it. I suppose this station is seen as a building according to [this line](https://github.com/orbisgis/geoclimate/blob/d8fc72a098833c008f74d30cc7d5d9dfcdf06112/osm/src/main/resources/org/orbisgis/geoclimate/osm/buildingParams.json#L5). My question is "do we have examples of stations which are buildings but declared as "railway:station" instead of "building:train_station" or other ?

**Comment by j3r3m1** [comment]
> > You mean . GeoClimate creates a building ?
> 
> Yes this is it. I suppose this station is seen as a building according to [this line](https://github.com/orbisgis/geoclimate/blob/d8fc72a098833c008f74d30cc7d5d9dfcdf06112/osm/src/main/resources/org/orbisgis/geoclimate/osm/buildingParams.json#L5). My question is "do we have examples of stations which are buildings but declared as "railway:station" instead of "building:train_station" or other ?

Here is a "building:yes" and "railwayroundhouse" for testing new version:
https://www.openstreetmap.org/way/110583434

**Comment by ebocher** [comment]
Fixe https://www.openstreetmap.org/way/1172856149
Add a new building type to identify shelter

![geoms](https://github.com/orbisgis/geoclimate/assets/1820572/27217dc6-d37f-4ba2-b44b-30715768843f)

**Comment by ebocher** [comment]
Fix https://www.openstreetmap.org/way/110581509

![geoms](https://github.com/orbisgis/geoclimate/assets/1820572/5227542a-6b7f-4d03-922d-70a267522714)
