### ISSUE TITLE
Building missing in OSM

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#859]
I have found a cinema which is not seen as a building by GeoClimate while I suppose it exists.

It is the [Pathe Wilson](https://www.openstreetmap.org/node/5549907184), tagged in OSM as "amenity:cinema". Should we add this one in the buildingParam.json file ?

Note that Google images show [an older version of the cinema](https://www.google.fr/maps/@43.6046642,1.4477393,3a,64.6y,134.37h,101.92t/data=!3m6!1e1!3m4!1sn7tmzaPxH0gZEt792AGsdA!2e0!7i13312!8i6656?entry=ttu) (Gaumont at that time). The image is more than 10 years old... But I suppose the building has not changed a lot. And it is represented as a building in OSM.

**Comment by j3r3m1** [comment]
Same for "building:theatre" or "amenity:theatre": https://www.openstreetmap.org/way/41968655

**Comment by j3r3m1** [comment]
Some other buildings (such as [this one](https://www.openstreetmap.org/way/875759493) and surroundings) but this time the reason of the absence is probably due to the zindex equal to -0.5... I know we have not considered buildings underground when zindex = -1 but I wonder whether we need to keep it for zindex=0.5 since they are slightly above ground (see [here](their top being the top of the stairs)).

In my opinion we should not consider them because they are very low above ground but is can be discussed.

@ebocher @wurtzj what do you think ?

**Comment by j3r3m1** [comment]
A [new one](https://www.openstreetmap.org/way/52498735#map=18/43.64147/1.43080) missing in OSM. It seems we do not get it since we use in [buildingParams](https://github.com/orbisgis/geoclimate/blob/d8fc72a098833c008f74d30cc7d5d9dfcdf06112/osm/src/main/resources/org/orbisgis/geoclimate/osm/buildingParams.json#L347) "building:market_place" instead of "building:marketplace" (however "building:marketplace" is not an existing combination for building: https://wiki.openstreetmap.org/wiki/FR:Key:building?uselang=fr but "marketplace" is a value for amenity)

**Comment by j3r3m1** [comment]
> Some other buildings (such as [this one](https://www.openstreetmap.org/way/875759493) and surroundings) but this time the reason of the absence is probably due to the zindex equal to -0.5... I know we have not considered buildings underground when zindex = -1 but I wonder whether we need to keep it for zindex=0.5 since they are slightly above ground (see [here](their top being the top of the stairs)).
> 
> In my opinion we should not consider them because they are very low above ground but is can be discussed.
> 
> @ebocher @wurtzj what do you think ?

@wurtzj it seems this big building is more complex than what we have faced now. And the way it has been created in OSM is not consistent with OSM recommandations (levels should not be -0.5 for example). However, this building area remains complex and our current code would not allow its consideration even though it would be correctly fullfilled. It has to be taken into account in future GeoClimate version if we want to deal with complex building stuctures such as podium and other types that are met in areas such as Hong-Kong (cf. #770). Let's consider this is a part of issue #770. This issue will then be solved once the three other cases are OK.

**Comment by wurtzj** [comment]
Hello @j3r3m1,
I read this about half levels : 'There is also an ongoing discussion on usage of fractional values, e.g. level=0.5 or level=1.5 for mezzanine floors and staircases. See the proposals for more examples. '

The complexity of such buildings seems difficult to take into account and to characterise. It seems there is a lack from additionnal informal for fully characterise such buildings. Fortunately there are not so numerous.

**Comment by ebocher** [comment]
Fixe this https://www.openstreetmap.org/node/5549907184

Result : 

![geoms](https://github.com/orbisgis/geoclimate/assets/1820572/7e5bacca-0db3-4ba4-8333-b7cd1a84944d)

Note :  There is on OSM raw a building tagged as apartements and also as a fountain ;-)

**Comment by ebocher** [comment]
Done for https://www.openstreetmap.org/way/41968655

![geoms](https://github.com/orbisgis/geoclimate/assets/1820572/98943114-b1d5-4dc6-a4cf-62e68db8162a)

**Comment by ebocher** [comment]
Done : https://www.openstreetmap.org/way/52498735#map=16/43.6413/1.4329

![geoms](https://github.com/orbisgis/geoclimate/assets/1820572/18a10dac-2d71-4b69-9988-474465ccf475)

**Comment by j3r3m1** [comment]
Supernice !
