### ISSUE TITLE
Wrong building table used by grid indicators ?

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#884]
It seems the grid indicator calculation is using buildings without the estimated height... It has to be checked. Might be a cache issue ?

**Comment by j3r3m1** [comment]
OK, indeed there is a major bug in the OSM workflow. The building table containing the updated height is not used by the grid indicator nor the the noise indicator !!

@ebocher I update the code and you validate ?

I wonder whether it would also be an opportunity to move some parts of the OSM workflow into a more generic functions (in the workflow indicator) instead of having to maintain OSM and BDT workflows. This is particularly the case for the future: if we have a script which makes the indicator calculation for any input data it would be easier if everything is generic (outside the data related workflows).

**Comment by j3r3m1** [comment]
@MelPoupelin do not use the grid indicators as long as this problem is not solved

**Comment by ebocher** [comment]
A mistake certainly due to the numerous reorganizations of the code in recent weeks.
I suggest fixing the table building problem first, before starting a major restructuring that may cause new problems.

**Comment by ebocher** [comment]
I will send a PR to fix that. You've just rescued GeoClimate ;-)

**Comment by ebocher** [comment]
Fix in #890
