### ISSUE TITLE
Problem with groovy request

### ISSUE THREAD

**Issue by balglave** [orbisgis/geoclimate#888]
Hi,
I am facing issues with a groovy command.
The command line I enter in the shell is the following one : groovy geoclimate_with_urban_sprawl.groovy Clamart
The geoclimate_with_urban_sprawl.groovy is below as well as the error message.
It looks the problem comes at line 115 in the runGeoclimate function -->  Map process = OSM.workflow(workflow_parameters) 
If anyone knows how to debug this, I'll take it !
And if anyone knows good tutorials to learn a bit more about groovy, I'll take it too.
See you,
Baptiste

---
**geoclimate_with_urban_sprawl.groovy**

@GrabResolver(name='orbisgis', root='https://oss.sonatype.org/content/repositories/snapshots/')
@Grab(group='org.orbisgis.geoclimate', module='geoclimate', version='0.0.2-SNAPSHOT')

/**
 *  This script is used to run geoclimate and compute the urban sprawl
 */

import org.orbisgis.geoclimate.osm.OSM
import org.orbisgis.data.H2GIS

String location = args[0]

//Directory to store all the results
String outputDirectory ="/home/balglave/Desktop/Research/geoclimate/res/"

if(!outputDirectory){
    println "The output directory to store the result cannot be null or empty"
}

File dirFile = new File(outputDirectory)
if(!dirFile.exists()){
    println "Create the output directory because it doesn't exist"
    dirFile.mkdir()
}

//Compute the BBOX of the ICU layer

def local_database_name = "geoclimate_sprawl"

def h2gis_db_parameters = [
        "folder": outputDirectory,
        "name"  : "${local_database_name};AUTO_SERVER=TRUE".toString(),
        "delete": false
]

if(!location){
    println("The location value cannot be null")
}

//Create before the local H2GIS database that will be used to compute the BBOX of the area
H2GIS h2GIS = H2GIS.open(h2gis_db_parameters.folder + File.separator + h2gis_db_parameters.name)
if(h2GIS==null){
    println("Cannot create the local H2GIS database")
    return
}

def outputTableNames = runGeoclimate(h2gis_db_parameters, location, outputDirectory )

if(!outputTableNames){
    println("Cannot compute the GeoClimate indicators")
}

def rsu_lcz = outputTableNames.rsu_lcz

//Extract sprawl area
String urbanSprawlH2GIS = computeUrbanSprawl(h2GIS, rsu_lcz )

if(!urbanSprawlH2GIS){
    println("Cannot compute the urban sprawl")
    return
}

//Save the data in a geojson file
h2GIS.save(urbanSprawlH2GIS, outputDirectory+File.separator+"osm_"+location+ File.separator+"urban_sprawl.geojson", true)

/**
 * Run the GeoClimate OSM worflow
 * @param h2gis_db_parameters
 * @param envelope
 * @return
 */
def runGeoclimate(def h2gis_db_parameters, def zone, def outputDirectory) {

    if (!zone) {
        println "The name of the zone to process cannot be null or empty"
    }

/*================================================================================
* Exemple with OSM input areas configuration
*/

    def input = ["locations": [zone], "delete": true, "area": 2800]

/*================================================================================
* Folder to store the results
*/
    def  output  = [
            "folder" : "$outputDirectory"
    ]

/*================================================================================
* WORKFLOW PARAMETERS
*/
    def workflow_parameters = [
            "description" : "Run the Geoclimate chain  and export result to a folder",
            "geoclimatedb": h2gis_db_parameters,
            "input"       : input,
            "output"      : output,
            "parameters"  : [
                    "rsu_indicators"        : [
                            "indicatorUse": ["LCZ"]
                    ], "worldpop_indicators": true
            ]
    ]

    Map process = OSM.workflow(workflow_parameters)
    return process.values().collectEntries()
}

/**
 * Compute the urban sprawl from the LCZ
 *
 * @param outputDirectory
 * @param h2GIS
 * @param lczTableName
 * @param save
 * @return
 */
String computeUrbanSprawl(H2GIS h2GIS, String lczTableName ){

    def mergingLcz = "merging_lcz"

    h2GIS.execute("""
DROP TABLE IF EXISTS $mergingLcz;
CREATE TABLE $mergingLcz as 
select EXPLOD_ID as id_rsu, the_geom from ST_EXPLODE('(
select st_removeholes(st_union(st_accum(the_geom))) as the_geom FROM $lczTableName where  LCZ_PRIMARY IN (1,2,3,4,5,6,7,8,9,10,105))')       
""".toString())

//Create a grid to generalize the urban areas
    h2GIS.execute(""" DROP TABLE IF EXISTS grid;
CREATE TABLE grid as select * from ST_MAKEGRID('$mergingLcz', 100,100);
""".toString())

    h2GIS.createSpatialIndex("grid")
    h2GIS.createSpatialIndex(mergingLcz)

//Compute the percentage by grid
    h2GIS.execute(""" DROP TABLE IF EXISTS grid_lcz, grid_lcz_area, grid_raster;
CREATE TABLE grid_lcz as select st_area(st_intersection(a.the_geom, b.the_geom)) as area, a.id  from grid as a, 
$mergingLcz as b where a.the_geom && b.the_geom and st_intersects(a.the_geom, b.the_geom);
CREATE TABLE grid_lcz_area as select sum(area) as sum_lcz, id from grid_lcz group by id;
CREATE INDEX ON grid_lcz_area (ID);
CREATE INDEX ON grid (ID);
CREATE TABLE grid_raster as select a.id, a.the_geom from grid as a left join grid_lcz_area as b on a.id=b.id where sum_lcz/(100*100) > 0.4
""".toString())

    def urban_sprawl = "urban_sprawl"

    h2GIS.execute("""
DROP TABLE IF EXISTS $urban_sprawl;
CREATE TABLE $urban_sprawl as 
select EXPLOD_ID as id_rsu, the_geom from ST_EXPLODE('(
select st_removeholes(st_union(st_accum(the_geom))) as the_geom FROM grid_raster)')     ;
DROP TABLE IF EXISTS  grid_lcz,  grid_raster, grid, grid_lcz_area, mergingLcz;
""".toString())

    return urban_sprawl
}

--------------------------
**Error message**

22:14:01.547 [main] DEBUG class org.orbisgis.geoclimate.osm.OSM -- Reading file parameters
22:14:01.549 [main] DEBUG class org.orbisgis.geoclimate.osm.OSM -- Run the Geoclimate chain  and export result to a folder
22:14:01.922 [main] INFO class org.orbisgis.geoclimate.osm.OSM -- 1 osm areas will be processed
22:14:02.477 [main] DEBUG class org.orbisgis.geoclimate.osmtools.OSMTools -- https://nominatim.openstreetmap.org/search?q=Clamart&limit=5&format=geojson&polygon_geojson=1&extratags=1
22:14:02.477 [main] DEBUG class org.orbisgis.geoclimate.osmtools.OSMTools -- Executing query... Clamart
22:14:02.553 [main] INFO class org.orbisgis.geoclimate.osmtools.OSMTools -- Downloading the Nominatim data.
22:14:02.877 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9603.
22:14:02.890 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.890 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.890 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.890 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.891 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.891 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9603.
22:14:02.891 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.891 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.891 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.891 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.891 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.892 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.892 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.892 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9603.
22:14:02.892 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9603.
22:14:02.892 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9603.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.893 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.894 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9603.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9603.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9603.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.895 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.899 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.899 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.899 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.899 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.899 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.899 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.899 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.900 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.901 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.902 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.903 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.904 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.905 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.906 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:1031.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.907 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.908 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.908 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.908 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.908 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.908 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9601.
22:14:02.908 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9602.
22:14:02.944 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9824.
22:14:02.945 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9824.
22:14:02.945 [main] DEBUG org.cts.CRSHelper -- A component has already been registered for key EPSG:9824.
22:14:03.226 [main] INFO class org.orbisgis.geoclimate.osmtools.OSMTools -- Extract the OSM data
Caught: groovy.lang.MissingMethodException: No signature of method: java.lang.String.digest() is applicable for argument types: (java.lang.String) values: [SHA-256]
Possible solutions: lines(), getAt(java.lang.String), toList(), toSet(), size(), next()
groovy.lang.MissingMethodException: No signature of method: java.lang.String.digest() is applicable for argument types: (java.lang.String) values: [SHA-256]
Possible solutions: lines(), getAt(java.lang.String), toList(), toSet(), size(), next()
	at org.orbisgis.geoclimate.osmtools.Loader.extract(Loader.groovy:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.orbisgis.geoclimate.osm.WorkflowOSM$_osm_processing_closure2.doCall(WorkflowOSM.groovy:446)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.orbisgis.geoclimate.osm.WorkflowOSM.osm_processing(WorkflowOSM.groovy:412)
	at org.orbisgis.geoclimate.osm.WorkflowOSM$osm_processing$1.callCurrent(Unknown Source)
	at org.orbisgis.geoclimate.osm.WorkflowOSM.workflow(WorkflowOSM.groovy:361)
	at org.orbisgis.geoclimate.osm.WorkflowOSM$workflow.call(Unknown Source)
	at org.orbisgis.geoclimate.osm.OSM.workflow(OSM.groovy:49)
	at org.orbisgis.geoclimate.osm.OSM$workflow.call(Unknown Source)
	at geoclimate_with_urban_sprawl.runGeoclimate(geoclimate_with_urban_sprawl.groovy:115)
	at geoclimate_with_urban_sprawl$runGeoclimate.callCurrent(Unknown Source)
	at geoclimate_with_urban_sprawl.run(geoclimate_with_urban_sprawl.groovy:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by ebocher** [comment]
This issue seems related to def queryHash = bboxUrl.digest('SHA-256')  (https://github.com/orbisgis/geoclimate/blob/a62146eb94e1b47e2902be7d4e8cf4296281b7d3/osmtools/src/main/groovy/org/orbisgis/geoclimate/osmtools/Loader.groovy#L205) when we geoclimate creates a hash text to name the downloaded osm file.

Can you give the result of these commands ?

java -version -> At least 11, not tested with java up to 17
groovy -version > Must be 3.0.19

**Comment by balglave** [comment]
**Java version**

openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

**groovy version**
Groovy Version: 2.4.21 JVM: 11.0.20.1 Vendor: Ubuntu OS: Linux

Then, it may be the groovy version...

**Comment by ebocher** [comment]
It's a very old version. You can install the good one with sdkman https://sdkman.io/

**Comment by balglave** [comment]
yep, I'm on it

**Comment by balglave** [comment]
Works fine ! The hardest part was to correct the path to groovy in R. But looks good now. Thanks !
