### ISSUE TITLE
Chaining processes trouble if mapping

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#89]
Sometimes IProcesses needs several indicators as inputs and these indicators should be in the same table. As only the indicator and the id of the geometry are the conserved columns in an IProcess, we need to make some "join" operations on the tables. Thus mapping would be complicated if we do not add an "inputField" in the input of each IProcesses.

**Comment by ebocher** [comment]
What about using a constant field name ?

**Comment by j3r3m1** [comment]
@ebocher will propose a process for the join

**Comment by ebocher** [comment]
yes I'm on it

**Comment by j3r3m1** [comment]
Done in #93 or #94.

**Comment by ebocher** [comment]
Done in #97
