### ISSUE TITLE
org.h2.jdbc.JdbcSQLNonTransientException: Exception lors de l'appel de la fonction définie par l'utilisateur

### ISSUE THREAD

**Issue by adwien** [orbisgis/geoclimate#923]
My case with BD_topo_V3 doesn't work:
the json file is:
'''{
    "description": "Processing BDTopo v3 data",
    "input": {
        "folder":  "/home/adrien/Documents/mes_scripts/Geoclimate/BD_TOPO_v3/Rouen",
        "locations":["76540"],
        "srid" : 76540
    },
    "output": {
        "folder": "/home/adrien/Documents/mes_scripts/Geoclimate/projet/Rouen"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "UTRF"
            ],
            "svfSimplified": true,
            "estimateHeight": true
        },
        "grid_indicators": {
            "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :["BUILDING_FRACTION", "BUILDING_HEIGHT", "BUILDING_POP",
                               "BUILDING_TYPE_FRACTION", "WATER_FRACTION", "VEGETATION_FRACTION",
                               "ROAD_FRACTION", "IMPERVIOUS_FRACTION", "FREE_EXTERNAL_FACADE_DENSITY",
                               "BUILDING_HEIGHT_WEIGHTED", "BUILDING_SURFACE_DENSITY",
                               "SEA_LAND_FRACTION", "ASPECT_RATIO", "SVF",
                               "HEIGHT_OF_ROUGHNESS_ELEMENTS", "TERRAIN_ROUGHNESS_CLASS",
                               "UTRF_AREA_FRACTION", "UTRF_FLOOR_AREA_FRACTION",
                               "LCZ_PRIMARY"]
         }
    }
}

this gives this error:
org.h2.jdbc.JdbcSQLNonTransientException: Exception lors de l'appel de la fonction définie par l'utilisateur: "intersection(GEOMETRYCOLLECTION (POLYGON ((561784.2 6926516.725000001, 561786.8 6926517.7, 561790.6 6926507.9, 561784.2 6926505.438461538, 561784.2 6926512.461538462, 561784.3 6926512.5, 561784.2 6926512.746666667, 561784.2 6926516.725000001)), POINT (561784.2 6926500.9)), POLYGON ((561684.2 6926496.4, 561784.2 6926496.4, 561784.2 6926596.4, 561684.2 6926596.4, 561684.2 6926496.4))): Overlay input is mixed-dimension"
Exception calling user-defined function: "intersection(GEOMETRYCOLLECTION (POLYGON ((561784.2 6926516.725000001, 561786.8 6926517.7, 561790.6 6926507.9, 561784.2 6926505.438461538, 561784.2 6926512.461538462, 561784.3 6926512.5, 561784.2 6926512.746666667, 561784.2 6926516.725000001)), POINT (561784.2 6926500.9)), POLYGON ((561684.2 6926496.4, 561784.2 6926496.4, 561784.2 6926596.4, 561684.2 6926596.4, 561684.2 6926496.4))): Overlay input is mixed-dimension"; SQL statement:

                              DROP TABLE IF EXISTS upper_table_join [90105-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:212)

I'm using the srid opton in the json file as explained on https://github.com/orbisgis/geoclimate/wiki/Frequently-Asked-Questions (if not it doesn't work and gives the "Cannot find a SRID value for the layer commune.shp.
Please set a valid OGC prj or use the parameter srid to force it.")

**Comment by ebocher** [comment]
It seems that your are using an invalid srid. Please replace "srid" : 76540 by "srid" : 2154

**Comment by adwien** [comment]
thnaks for this advice, but using srid :2154, I have the same error

**Comment by ebocher** [comment]
Fixed with #934 
Please test the last snaphot version

**Comment by j3r3m1** [comment]
@adwien is this problem solved ?
