### ISSUE TITLE
LCZ classification of Greenhouse horticulture

### ISSUE THREAD

**Issue by EmmanuelleKerjouan** [orbisgis/geoclimate#928]
I made an LCZ classification with OpenStreetMap data thanks to GeoClimate, on Montpellier Métropole. In several areas, greenhouses can be seen, identified on OSM as :  Greenhouse horticulture. These are buildings with a large footprint, but are identified as LCZ D (low plants). It might be worth classifying these areas as LCZ 8 (large low-rise).
Coordinates of the study area : 43.528820713, 3.764570181, 43.661347862, 3.996709717
Here is the OSM link for the area in question : https://www.openstreetmap.org/way/146465892
Here is the result of the classification : 
![greenhouse_horticulture2](https://github.com/orbisgis/geoclimate/assets/126885597/e436968f-1a2f-48d7-9220-042db9bd3a6b)
![greenhouse_horticulture](https://github.com/orbisgis/geoclimate/assets/126885597/86169c85-d11f-40a0-8090-642c43bb06e1)

**Comment by j3r3m1** [comment]
This is a quite complex question. The greenhouses are indeed large low and low-rise but we cannot really say that they behave as buildings. I think the classification is then really dependent of its dedicated use.
I would keep it to what it is, LCZ D but maybe others would have a different opinion.
@franetibe @wurtzj

**Comment by wurtzj** [comment]
Hi,

Hard to say as there are both buildings and plants... Also depends on the type on greenhouses (heated, glass, etc.)
So Yes I'd rather keep them in natural LCZ D **for now**.
