### ISSUE TITLE
 Problem in cutting RSUs (LCZ D)

### ISSUE THREAD

**Issue by EmmanuelleKerjouan** [orbisgis/geoclimate#930]
I work in the Montpellier Métropole area, with OpenStreetMap data. In some cases, we can see relatively large residential or suburban areas that are classified as LCZ D (low plants). If we look in detail at one of these zones, we can see that the shape of the RSU is very particular. This shape actually corresponds to two LCZ D RSUs linked by a road or path. There is therefore more low vegetation than residential, and the RSU is classified as D when it should be classified as LCZ 9. This phenomenon can be found in many areas, often at the edge of villages in rural areas. 
Coordinates of the area in 4326 : 43.532303287, 3.863152085, 43.539067883, 3.874990248
Link to the OSM object in question : https://www.openstreetmap.org/way/371706338
LCZ zone map : 
![RSU_form](https://github.com/orbisgis/geoclimate/assets/126885597/a02f85e1-25e7-490e-853f-160e5c8068db)
![RSU_form2](https://github.com/orbisgis/geoclimate/assets/126885597/6679e962-8fe9-45d4-83da-9500532b3ef9)

**Comment by j3r3m1** [comment]
Thanks @EmmanuelleKerjouan for reporting. It should normally be cut in two pieces. Can you share the resulting urban_areas.geojson as well as the rsu_lcz ?

**Comment by EmmanuelleKerjouan** [comment]
Yes, no worries 
[Montpellier.tar.gz](https://github.com/orbisgis/geoclimate/files/14114792/Montpellier.tar.gz)

**Comment by j3r3m1** [comment]
OK the splitting use well the urban area geometries, it is fine. But the RSUs which are created lead to a segmentation between two zones that should not be together.

![image](https://github.com/orbisgis/geoclimate/assets/13120405/820b0b61-0295-455e-bcf8-ec7630db7c35)

We did not have this behavior before integrating the urban areas into consideration for creating the RSU. The reason why this two zones are connected is that the whole city is considered as a single residential area, thus leading to strange strings in this region.
![image](https://github.com/orbisgis/geoclimate/assets/13120405/2f3d64b3-34db-44bf-b4e2-64b2a8e4cbb6)

This has also been identified in many places by some other colleagues. Maybe the road algorithm that @ebocher is developping may solve this issue in some cases but I am not sure it will solve all the cases.

@EmmanuelleKerjouan, this thread might be used to illustrate all the zones you find that present this problem. If you can give for each case you find like that:
- the name of the place
- a figure showing the RSU that are problematic as I showed above
it would be great (it would be test case for the @ebocher algorithm).
