### ISSUE TITLE
Sea/land mask issue with grid indicators

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#940]
Hi !

I have an issue when running the workflow on Linux with the OSM data. It happened with a particular city, Nantes (but not with the neighboring town, Rezé), and I can't figure out what could be wrong in that case. 

It gave me this alert : "Table "INPUT_SEA_LAND_MASK__BDAE592F_F077_4E4B_9B1D_B9A4764B4BC1" not found".

Should I add something in the config file to avoid this ?

Thanks !

(PS : the workflow run fine with BD Topo data)

![Capture d’écran 2024-02-22 à 21 04 28](https://github.com/orbisgis/geoclimate/assets/9679672/4cffe885-7965-4873-abd3-95240bd787c2)
[Hist_Terminal_Geoclimate_OSM_Nantes.txt](https://github.com/orbisgis/geoclimate/files/14379216/Hist_Terminal_Geoclimate_OSM_Nantes.txt)

_Originally posted by @Denis-Vannier in https://github.com/orbisgis/geoclimate/discussions/938_

**Comment by ebocher** [comment]
Please test the last snapshot

**Comment by j3r3m1** [comment]
@Denis-Vannier feel free to post a message in #936. Thanks !

**Comment by ebocher** [comment]
@Denis-Vannier Please take a moment to post a message in https://github.com/orbisgis/geoclimate/discussions/936.
