### ISSUE TITLE
Sea-land mask trouble

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#952]
Here is what we obtain using the last GeoClimate version near Veneto:
![image](https://github.com/orbisgis/geoclimate/assets/13120405/605df9fb-f569-4859-baa6-649ba2f5105f)
![image](https://github.com/orbisgis/geoclimate/assets/13120405/6db21a87-df98-4794-b05e-2cb0449bdbef)

I do not think this is a major bug since there is only a single geometry on the East side that should be water instead of land. I think this land will be surrounded by water (I do not have the cells beside yet) so it is manageable as a postprocess. Other nearby water cells I have investigated are very well defined

**Comment by ebocher** [comment]
I will check this area

**Comment by ebocher** [comment]
The GeoClimate sea/land mask algorithm works well to extract and format the sea/land areas. 
I'm checking the workflow.


Input location : [44.795480,12.323227,45.004622,12.627411]

![geoms_pb](https://github.com/orbisgis/geoclimate/assets/1820572/667e0f3f-2022-4431-a796-64dd49cbb005)

**Comment by ebocher** [comment]
Fixed with this PR https://github.com/orbisgis/geoclimate/pull/958
