### ISSUE TITLE
Do not substring column names

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#96]
The process unweightedOperationFromLowerScale and weightedAggregatedStatistics received a set of column names that will be selected to run the aggregate function. Currently, the three first column letters are used to create the name of the indicator. I think we must keep the whole name.

**Comment by j3r3m1** [comment]
OK no problem for me. Maybe several IProcess tests will have to be modified then but it should not take too long. I can do it tonight but not before. If you need it before, feel free to make the modifications. Enjoy !

**Comment by j3r3m1** [comment]
I think it has been done and can be closed
