### ISSUE TITLE
Problem with the SNAPSHOT-1.0.1

### ISSUE THREAD

**Issue by SamuelMarsault** [orbisgis/geoclimate#960]
Hello,

currently I’m trying to use GéoClimate thanks to maven with the SNAPSHOT-1.0.1. For now, I put in my . groovy a raw configuration file : 

```
def config = [
  "description" :"GeoClimate configuration file",
  "input": ["locations": ["Saint-Jean-la-Poterie"]],
  "output": ["folder": ["path": "$outputDirectory",
    "name": "geoclimate_chain_db;AUTO_SERVER=TRUE",
    "tables": ["building", "road_traffic", "ground_acoustic", "zone"]],
    "srid": 2154],
  "parameters": ["rsu_indicators": ["indicatorUse": ["LCZ"],
    "estimateHeight": true],
    "distance": 500,
    "road_traffic": true,
    "worldpop_indicators" : true,
    "noise_indicators": ["ground_acoustic": true]]
]
```

and I make a "org.orbisgis.geoclimate.osm.OSM.workflow(config)" to see if it compiles. All of it goes right until I get this error:

```
[main] INFO GeoClimate - All geoindicators have been computed
Caught: java.lang.NullPointerException: Cannot invoke method getMinY() on null object
java.lang.NullPointerException: Cannot invoke method getMinY() on null object
	at org.orbisgis.geoclimate.osm.WorkflowOSM$_osm_processing_closure2.doCall(WorkflowOSM.groovy:581)
	at org.orbisgis.geoclimate.osm.WorkflowOSM.osm_processing(WorkflowOSM.groovy:416)
	at org.orbisgis.geoclimate.osm.WorkflowOSM.workflow(WorkflowOSM.groovy:364)
	at org.orbisgis.geoclimate.osm.OSM.workflow(OSM.groovy:48)
	at Main.run(Main.groovy:17)
```

In the WorkflowOSM.groovy file on line 581 we see that it is marked:
```
zones.envelope.getMinY()
```
and when we look at the content of the variable "zones" in the line in line 783 there are actually no fields "envelope" which create the error. Is it a forget ? That at line 581 it is mistaken variable name and its should be: "osm_envelope_extented" ? the file was not push ?

Thank you in advance for the answers you can give me !

**Comment by ebocher** [comment]
Thanks a lot @SamuelMarsault 
This issue is fixed.
