### ISSUE TITLE
Sea/Land Mask Error when processing large OSM boundingbox

### ISSUE THREAD

**Issue by Jukjuk-boop** [orbisgis/geoclimate#980]
I'm trying to use the OSM workflow with a bounding box covering a large area (47.1962588,4.8664953,47.4598755,5.2368395).
The process get stuck at Sea/Land formatted and send me this error :
[main] WARN GeoClimate - The zone 47.1962588_4.8664953_47.4598755_5.2368395 has not been processed. Please check the log table to get more informations.
Cannot execute the OSM workflow

Here is the Logs table content :
Table "INPUT_SEA_LAND_MASK__0CAB8BE1_7C29_45B5_8C1E_18D47B0EB078" non trouvée
Table "INPUT_SEA_LAND_MASK__0CAB8BE1_7C29_45B5_8C1E_18D47B0EB078" not found; SQL statement:
select count(*) rowcount from INPUT_SEA_LAND_MASK__0CAB8BE1_7C29_45B5_8C1E_18D47B0EB078 [42102-224]

And here is my config file :
```
{
    "description": "Processing OSM data",
    "input": {
    	"area" : 100000,
    	"timeout": 9000,
	"maxsize":4294967296,
        "locations": [
            [47.1962588,4.8664953,47.4598755,5.2368395]
        ]
    },
    "output": {
        "folder": "/tmp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "UTRF"
            ],
            "svfSimplified": true,
            "estimateHeight": true
        },
        "grid_indicators": {
            "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :["BUILDING_FRACTION", "BUILDING_HEIGHT", "BUILDING_POP",
                               "BUILDING_TYPE_FRACTION", "WATER_FRACTION", "VEGETATION_FRACTION",
                               "ROAD_FRACTION", "IMPERVIOUS_FRACTION", "FREE_EXTERNAL_FACADE_DENSITY",
                               "BUILDING_HEIGHT_WEIGHTED", "BUILDING_SURFACE_DENSITY",
                               "SEA_LAND_FRACTION", "ASPECT_RATIO", "SVF",
                               "HEIGHT_OF_ROUGHNESS_ELEMENTS", "TERRAIN_ROUGHNESS_CLASS",
                               "UTRF_AREA_FRACTION", "UTRF_FLOOR_AREA_FRACTION",
                               "LCZ_PRIMARY"]
         }
    }
}
```

I tested with a light config file (only "LCZ" parameter), and also tried changing the "area", "timeout" and "maxsize" value. Yet the logs table always shows the same information.

**Comment by j3r3m1** [comment]
I could not reproduce your error using the last GeoClimate version. Can you have a try to update and let us know ?

**Comment by Jukjuk-boop** [comment]
It works with the new update. Thanks for helping me sort this out.
